### ISSUE TITLE
Vagrant Post-Install Message

### ISSUE THREAD

**Issue by storm2k** [roots/trellis#1005]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a feature request
- [] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums
---

**What is the current behavior?**

Upon running `vagrant up` for the first time, the following message comes up at the end of provisioning:

```
==> default: Machine 'default' has a post `vagrant up` message. This is a message
==> default: from the creator of the Vagrantfile, and not from Vagrant itself:
==> default: 
==> default: Your Trellis Vagrant box is ready to use!
==> default: * Composer and WP-CLI commands need to be run on the virtual machine
==> default:   for any post-provision modifications.
==> default: * You can SSH into the machine with `vagrant ssh`.
==> default: * Then navigate to your WordPress sites at `/srv/www`
==> default:   or to your Trellis files at `/home/vagrant/trellis`.

```

This contradicts the [docs](https://roots.io/trellis/docs/local-development-setup/), which say that anything you do locally is synced back to the VM. I've always run composer and wp-cli commands directly from my host (MacOS in this case) and had the changes properly reflected back. I'm wondering if this is due to the way that Trellis handles [Windows](https://roots.io/trellis/docs/windows/), where due to the issues with how things run, these things should only happen from within the VM as they may not sync back properly. If this is not the case, the docs need to be updated to reflect that changes made to your site that will use composer or wp-cli need to happen within the VM via `vagrant ssh` more clearly.

**What is the expected or desired behavior?**

Should not receive this message, unless specific conditions are true (running on Windows?)

---

## Bug report

**Please provide steps to reproduce, including full log output:**

1. Configure the development environment variables under group_vars
2. Run `vagrant up` to provision the local environment.

**Please describe your local environment:**

- Ansible version: 2.5.5
- OS: Mac
- Vagrant version: 2.1.1

---

## Feature Request

**Please provide use cases for changing the current behavior:**

This messaging is confusing and contradictory to the docs. Either the message needs to be removed, or the docs should be updated to reflect that the commands should be run from the VM and why.

**Comment by retlehs** [comment]
the message is accurate, i've updated the local dev docs with a couple sentences

it's not possible to run wp-cli commands from your host machine that are affecting your dev site on the VM unless you're using wp-cli aliases...

but please avoid using github for questions and open up a topic on roots discourse if you'd like to discuss things further
