### ISSUE TITLE
Update to ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by hemangajmera** [roots/trellis#1016]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [ ] This is a bug report
- [X ] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

Currently the trellis is configured for Ubuntu 16.04

**What is the expected or desired behavior?**

To use latest ubuntu LTS version

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

X

**Please describe your local environment:**

Ansible version: X

OS: X

Vagrant version: X

**Where did the bug happen? Development or remote servers?**

X

**Please provide a repository or your `wordpress_sites` config (if possible):**

X

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

---

## Feature Request

(delete this section if not applicable)

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

X

**Comment by swalkinshaw** [comment]
There's already a PR in progress for this https://github.com/roots/trellis/pull/992
