### ISSUE TITLE
project_copy_folders are always copied to the root

### ISSUE THREAD

**Issue by mockey** [roots/trellis#1026]
## Bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

When you add a folder to `project_copy_folders` like `- web/app/languages` it is copied to root after the deploy. Makes sense if you look at the code:
`cp -rp {{ deploy_helper.current_path }}/{{ item.item }} {{ deploy_helper.new_release_path }}`

**What is the expected or desired behavior?**

The folder should be copied to where it was. I guess:
`cp -rp {{ deploy_helper.current_path }}/{{ item.item }} {{ deploy_helper.new_release_path }}/{{ item.item }}`
would do.

---

**Please provide steps to reproduce, including full log output:**

Add a non-root folder to `project_copy_folders` and see where it ends. `vendor` works beause it is in root.

**Please describe your local environment:**

Ansible version: 2.7.1

OS: Linux Mint 17

Vagrant version: 2.2.0

**Where did the bug happen? Development or remote servers?**

Remote (after deploy)

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

Just posted it here:
https://discourse.roots.io/t/adding-wp-language-files-on-deploy/9212/26

**Comment by swalkinshaw** [comment]
This sounds like a good improvement. Want to do a PR for it?

**Comment by mockey** [comment]
Sure, but I'm wondering: Wouldn't it be better to use the `synchronize` (or `copy`) ansible module here? Or is there a special reason for using `cp -rp`?
The code above with `cp -rp` doesn't work if the target folder already exists. E.g. when you have an empty `web/app/languages` in your deploy, you end up with `web/app/languages/languages`.
I think `synchronize` or `copy` would work then if `project_copy_folders` ends with a `/`.

**Comment by swalkinshaw** [comment]
I don't remember any great reason. Could just be an oversight so it's worth trying out.

**Comment by mockey** [comment]
I'm not an ansible expert. The docs (https://docs.ansible.com/ansible/latest/modules/copy_module.html) say that `synchronize` (based on rsync) should be preferred to `copy` for folders with lots of files.
I see trellis uses `copy` in a couple of places, `synchronize` is only used in the build-before deploy-hook. What do you think?

**Comment by mockey** [comment]
I see. I wasn't aware of that local -> remote scheme. But that makes sense for ansible of course. I think I'll try to get `copy` working then. It might be useful to be able to copy something to an existing folder.
