### ISSUE TITLE
OpenLiteSpeed

### ISSUE THREAD

**Issue by partounian** [roots/trellis#1032]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---
This seems like a very interesting technology, obviously different from Trellis's usage of Nginx and I don't expect us to jump ship, but thought I'd post it here for anyone who might be interested. https://blog.litespeedtech.com/2018/03/05/compare-openlitespeed-to-nginx-and-apache/ 

Maybe we could even look into their implementations and port them over.

**Comment by swalkinshaw** [comment]
Interesting, thanks. Hadn't heard of this before.

> Maybe we could even look into their implementations and port them over.

Looks like there's two parts to this:

* OpenLiteSpeed web server itself
* LSCache WP plugin

The plugin seems to have a ton of features and roughly equivalent with other popular caching plugins which Trellis doesn't use by default anyway. But it also has features which only work OpenLiteSpeed itself, so I'm not sure there's anything we can really borrow from it.
