### ISSUE TITLE
Server provision failed - Python error.

### ISSUE THREAD

**Issue by Jensderond** [roots/trellis#1034]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

## Bug report

**Please provide steps to reproduce, including full log output:**

Clone the current master branch and try to provision on a stock version of Ubuntu 16.04.

**Please describe your local environment:**

Ansible version: 2.5.3

OS: Ubuntu 18.01.1

**Where did the bug happen? Development or remote servers?**

Remote server

**Output**
```
TASK [mariadb : Install MySQL server] *****************************************************************************************************************************************************************************
ok: [116.203.20.73]

TASK [mariadb : Disable MariaDB binary logging] *******************************************************************************************************************************************************************
ok: [116.203.20.73]

TASK [mariadb : Set root user password] ***************************************************************************************************************************************************************************
System info:
  Ansible 2.5.3; Linux
  Trellis version (per changelog): "Python 3 support"
---------------------------------------------------
The MySQL-python module is required.
failed: [116.203.20.73] (item=116.203.20.73) => {"changed": false, "item": "116.203.20.73"}
---------------------------------------------------
The MySQL-python module is required.
failed: [116.203.20.73] (item=127.0.0.1) => {"changed": false, "item": "127.0.0.1"}
---------------------------------------------------
The MySQL-python module is required.
failed: [116.203.20.73] (item=::1) => {"changed": false, "item": "::1"}
---------------------------------------------------
The MySQL-python module is required.
failed: [116.203.20.73] (item=localhost) => {"changed": false, "item": "localhost"}
	to retry, use: .....

PLAY RECAP ********************************************************************************************************************************************************************************************************
116.203.20.73              : ok=47   changed=1    unreachable=0    failed=1   
localhost                  : ok=0    changed=0    unreachable=0    failed=0 
```

**My current hotfix**
When I put back the task that installs Python 2.x the provision works.
[Change that broke the provision](https://github.com/roots/trellis/commit/d4c26a6b5488c031a579cbf2a93e1fd667f3e777#diff-5298527722e08565e24fc65523f41cfb)

**Comment by Jensderond** [comment]
So the remote server now is 16.04 my local environment is 18.04.1

**Comment by swalkinshaw** [comment]
Yeah that's completely fine. I just meant I missed that those changes are needed for Python 2/3 support independently of the 18.04 work.

**Comment by Jensderond** [comment]
Just to confirm, once the first two files changes where added to my setup the provisioning worked again.

**Comment by kyleoliveiro** [comment]
Running into this error as well. Hotfix proposed by @Jensderond seems to work.

**Comment by swalkinshaw** [comment]
I'm fixing this in #1036 by removing the part in `server.yml` where we change the Python interpreter.

**Comment by swalkinshaw** [comment]
The main issue here is that Python 3 is actually installed on a Trellis Ubuntu 16.04 build. It's a dependency of some other package. So that interpreter change was only meant to take effect on 18.04, but it would also set the interpreter on 16.04 and then we'd have missing packages as you ran into.
