### ISSUE TITLE
Upgrade to PHP 7.3 PPA

### ISSUE THREAD

**Issue by adamtomat** [roots/trellis#1037]
## Submit a feature request

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a feature request
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

Will Trellis look at supporting PHP 7.3? If so, when is this likely to occur (e.g. soon, a year, when 7.2 is EOL)?

**What is the current behavior?**

Trellis installs a PHP **7.2** PPA

**What is the expected or desired behavior?**

Trellis installs a PHP **7.3** PPA

## Feature Request

**Please provide use cases for changing the current behavior:**

There's some useful features in PHP 7.3 that would be useful to the community (JSON error handling I'm looking at you).

**Other relevant information:**

PHP will need to be upgraded at some point. Wondering what sort of timescale we are looking at?

What needs to happen in order to switch to PHP 7.3 too?

**Comment by swalkinshaw** [comment]
Generally we just need to make sure that WordPress itself can support a new PHP version.

Found this: https://make.wordpress.org/core/2018/10/15/wordpress-and-php-7-3/

Looks like 5.0 *should* be compatible, but there's also one or two small issues assigned for 5.0.1
