### ISSUE TITLE
PHP 7.3 throws Warning: "continue" targeting switch is equivalent to "break"

### ISSUE THREAD

**Issue by marko-bws** [roots/trellis#1056]
## Submit a feature request or bug report

- [ X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

Running a deploy script with current version of trellis halts at TASK [deploy : WordPress Installed?] with: 
non-zero return code
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you
mean to use "continue 2"?

**What is the expected or desired behavior?**

Deploy happens

---

## Bug report

After digging some on the net this is a common complaint for php 7.3 - seems that it needs to be fixed by Wordpress itself - just a note that you might want to halt using php 7.3 untill it is compatible...

**Please provide steps to reproduce, including full log output:**

run a standard deploy script - halts at:
TASK [deploy : WordPress Installed?] *********************************************************************************************************************************************************************************************************
System info:
  Ansible 2.4.2.0; Darwin
  Trellis 1.0.0: December 27th, 2018
---------------------------------------------------
non-zero return code
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you
mean to use "continue 2"? in
/srv/www/allpro.space/releases/20190104105730/web/wp/wp-includes/pomo/plural-
forms.php on line 210
Warning: "continue" targeting switch is equivalent to "break". Did you mean
to use "continue 2"? in /srv/www/allpro.space/releases/20190104105730/web/wp
/wp-includes/pomo/plural-forms.php on line 210
fatal: [staging_host]: FAILED! => {"changed": false, "cmd": ["wp", "core", "is-installed", "--skip-plugins", "--skip-themes", "--require=/srv/www/allpro.space/shared/tmp_multisite_constants.php"], "delta": "0:00:00.576651", "end": "2019-01-04 10:58:35.445056", "failed_when_result": true, "rc": 1, "start": "2019-01-04 10:58:34.868405", "stderr_lines": ["PHP Warning:  \"continue\" targeting switch is equivalent to \"break\". Did you mean to use \"continue 2\"? in /srv/www/allpro.space/releases/20190104105730/web/wp/wp-includes/pomo/plural-forms.php on line 210", "Warning: \"continue\" targeting switch is equivalent to \"break\". Did you mean to use \"continue 2\"? in /srv/www/allpro.space/releases/20190104105730/web/wp/wp-includes/pomo/plural-forms.php on line 210"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/Users/marko/Dev/Buzzworthy/trellis/deploy.retry

**Where did the bug happen? Development or remote servers?**

remote- DO dropplet - Ubuntu 18.04

**Comment by LeoColomb** [comment]
> halt using php 7.3 untill it is compatible

WordPress is 100% compatible with php 7.3 without warning since v5.0 (in your case: https://github.com/WordPress/WordPress/commit/76ef0432c0ce8f560c9bf474fa52314697f7da68) and without notice since v5.0.2.

Anyway this is nothing with Trellis...

**Comment by marko-bws** [comment]
I solved it by reverting back to php 7.2 - since this was a clean install (fresh server, fresh trellis clone) maybe it will appear again...

**Comment by swalkinshaw** [comment]
Judging from the error the issue was with a non-compatible plugin with 7.3.

Trellis defaults to 7.3, but it's up to you to ensure your WP version and plugins are compatible. What you did is likely the only solution in your situation for now 👍
