### ISSUE TITLE
New Relic Support

### ISSUE THREAD

**Issue by mAAdhaTTah** [roots/trellis#106]
Would adding support for New Relic monitoring be outside of the scope of this project?

**Comment by s3w47m88** [comment]
While I understand and respect there are Ansible Playbooks already setup for this. Monitoring servers is essential for managing the health of a server IMO. So would adding a reference, of some kind, in the docs be within scope?

Ex. Heading for "Server Monitoring" subtext says something like "While this is currently beyond the scope of Trellis, we recommend New Relic for server monitoring software. You can find existing Ansible Playbooks for including it here: {link to somewhere}."

**Comment by swalkinshaw** [comment]
@s3w47m88 docs page sounds useful 👍

**Comment by s3w47m88** [comment]
I'm glad to hear! I will contribute this and submit it as a PR when I'm done. To those who care: I'll try to do it in the next few days but no promises. :)
