### ISSUE TITLE
Change the virtualbox default memory size

### ISSUE THREAD

**Issue by aryaroudi** [roots/trellis#1065]
The virtual machine is eating my memory so I tried to change the memory size by changing the Vagrantfile in trellis folder but it seems it is not working the changes.

```
  # VirtualBox settings
  config.vm.provider 'virtualbox' do |vb|
    vb.name = config.vm.hostname
    vb.customize ['modifyvm', :id, '--cpus', vconfig.fetch('vagrant_cpus')]
    vb.customize ['modifyvm', :id, '--memory', vconfig.fetch('vagrant_memory')]
    vb.customize ['modifyvm', :id, '--ioapic', vconfig.fetch('vagrant_ioapic', 'on')]

    # Fix for slow external network connections
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', vconfig.fetch('vagrant_natdnshostresolver', 'on')]
    vb.customize ['modifyvm', :id, '--natdnsproxy1', vconfig.fetch('vagrant_natdnsproxy', 'on')]
  end
```

I have seen that the `vagrant_memory` is set on 1024 but it is still making the virtualbox:

> default: [vagrant-faster] Setting CPUs: 4, Memory: 4096

couldn't find where this `default` coming from

---

**What is the current behavior?**

The changes don't apply

**What is the expected or desired behavior?**

Be able to set the resources manually.

---

**Please describe your local environment:**

Ansible version: 2.7.5

OS: macOS Mojave

Vagrant version: 2.2.3

**Comment by swalkinshaw** [comment]
> but it is still making the virtualbox:

Can you on confirm what you did after changing that config value? Did you `destroy` + `up` again? Or `reload`?

**Comment by swalkinshaw** [comment]
The default comes from here: https://github.com/roots/trellis/blob/bd05a61d4c00e99db9332b431ead1cec248a7889/vagrant.default.yml#L4 and it's 1GB so I'm not sure where 4GB would be coming from.

**Comment by swalkinshaw** [comment]
Ah so looking at your output, it appears you're using a plugin called `vagrant-faster` and the setting is coming from there: https://github.com/rdsubhas/vagrant-faster.

So this isn't a Trellis issue.

**Comment by aryaroudi** [comment]
Hi @swalkinshaw I asked the question in roots forum and true it was because of `vagrant-faster` and after uninstalling it, everything worked fine.
