### ISSUE TITLE
Anyone have thoughts on MariaDB vs MySQL 8?

### ISSUE THREAD

**Issue by partounian** [roots/trellis#1067]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

I'm not too informed with the differences but have read MySQL 8 is reportedly 2x faster. https://www.mysql.com/products/enterprise/database/

If this is truly the case then it might be better for Trellis to go back to MySQL and use >= MySQL 8.

Anyone have some thoughts to this?

EDIT: Another useful resource http://dimitrik.free.fr/blog/archives/2018/04/mysql-performance-80-and-utf8-impact.html

**Comment by swalkinshaw** [comment]
> Up to 2x faster

"Up to" being the key words here 😄 

Anyway, MariaDB is mostly used because it's full open source and not owned by Oracle. Performance characteristics should be roughly equivalent I'd think for most WP sites.

**Comment by partounian** [comment]
@swalkinshaw did you look at the post in the edit?
