### ISSUE TITLE
Trellis fails if vault_mysql_root_password, db_password or .vault_pass contain special characters

### ISSUE THREAD

**Issue by schnerring** [roots/trellis#1069]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

## Bug report

**Please provide steps to reproduce, including full log output:**

I'm using a password generator to generate `vault_mysql_root_password`, `db_password` and the `ansible-vault` password (`.vault_pass` file).
The passwords consist of [_Printable 7-Bit ASCII_](https://keepass.info/help/base/pwgenerator.html) characters and have a length of 128. Following characters are included:
```
excluded ' since that character is used in yaml to enclose the password strings
A-Z, a-z, 0-9, !"#$%&()*+,-./:;<=>?@[\]^_`{|}~
```
When using _Mixed-Case Alphanumeric_ characters everything goes fine.

I reproduced the issue within the _development_ environment using the following passwords (`development/vault.yml`):
```
vault_mysql_root_password: '%-(."U8p.lXIk/c9zcvb&E<jE}QBhVWvr,3/F.JQfI|}:+;2i<k>hpGQIbZt4QI/9@3reb9A"^K13f,anlY~^HwZL;FY"BT$g:9nRK_c6|u7D6Uk&ym=P\4RNe%3wQJa'

...

      db_password: 'gf?[nTm>J:VI`ga#N_{4_h!,EsUco%JGAy9BYU$H6fr;R2PY-WT3lMAp^Pq5u=;qb*,eu}"GcvN9~`t9+#m:Bxn*1}Y99B}]1@s"k/8&v9AQ(o\ko}kKYN7=R1tdj?IF'

```
causing the following error when running `vagrant up`
```
TASK [wordpress-install : Install WP] ******************************************
System info:
  Ansible 2.7.7; Vagrant 2.2.3; Linux
  Trellis 1.0.1: January 16th, 2019
---------------------------------------------------
non-zero return code
PHP Warning:  mysqli_real_connect(): (HY000/1045): Access denied for user 'redacted'@'localhost' (using password: YES) in /srv/www/redacted/current/web/wp/wp-includes/wp-db.php on line 1531
Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'redacted'@'localhost' (using password: YES) in /srv/www/redacted/current/web/wp/wp-includes/wp-db.php on line 1531
Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `localhost`. This could mean your host’s database server is down.
failed: [default] (item=redacted) => {"changed": true, "cmd": ["wp", "core", "install", "--allow-root", "--url=http://redacted.test", "--title=redacted", "--admin_user=admin", "--admin_password=admin", "--admin_email=admin@redacted.test"], "delta": "0:00:00.130703", "end": "2019-02-10 20:59:51.522495", "item": {"key": "redacted", "value": {"admin_email": "admin@redacted.test", "cache": {"enabled": false}, "local_path": "../site", "multisite": {"enabled": false}, "site_hosts": [{"canonical": "redacted.test", "redirects": ["www.redacted.test"]}], "ssl": {"enabled": false, "provider": "self-signed"}}}, "rc": 1, "start": "2019-02-10 20:59:51.391792", "stderr_lines": ["PHP Warning:  mysqli_real_connect(): (HY000/1045): Access denied for user 'redacted'@'localhost' (using password: YES) in /srv/www/redacted/current/web/wp/wp-includes/wp-db.php on line 1531", "Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'redacted'@'localhost' (using password: YES) in /srv/www/redacted/current/web/wp/wp-includes/wp-db.php on line 1531", "Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `localhost`. This could mean your host’s database server is down."], "stdout": "", "stdout_lines": []}
```

Issues with the Ansible Vault passwords are not reproducible locally.
For provisioning and deploying, I run the playbooks inside a Docker executor on Gitlab CI, so maybe it has to do with the Ansible version used inside the Docker environment.
For the [Ubuntu Docker image](https://hub.docker.com/_/ubuntu) (18.04) in question the following version was installed:
```
Get:47 http://archive.ubuntu.com/ubuntu bionic/universe amd64 ansible all 2.5.1+dfsg-1 
```
Here's the error:

```
PLAY [Test Connection and Determine Remote User] *******************************
 [WARNING]: Failure using method (v2_playbook_on_play_start) in callback plugin (<ansible.plugins.callback.vars.CallbackModule object at 0x7f453bc4b790>):
Decryption failed (no vault secrets were found that could decrypt) on
/builds/redacted/trellis/group_vars/staging/vault.yml

ERROR! Decryption failed (no vault secrets were found that could decrypt) on /builds/redacted/trellis/group_vars/staging/vault.yml
ERROR: Job failed: exit code 1
```

**Please describe your local environment:**

Ansible version: 3.7.2 (local) / 2.5.1 (CI environment)

OS: Arch Linux (local) / Linux 18.04 Bionic (CI environment)

Vagrant version: 2.2.3

**Where did the bug happen? Development or remote servers?**

Development and remote servers

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

* [#73](https://github.com/roots/trellis/issues/73)

**Comment by swalkinshaw** [comment]
I would drop double quotes as well. https://roots.io/salts.html uses Ascii 33-1126 and drops `'`, `"`, '\`

**Comment by swalkinshaw** [comment]
https://github.com/roots/trellis/pull/1071 may help with this?
