### ISSUE TITLE
Update h5bp to version 3

### ISSUE THREAD

**Issue by nlemoine** [roots/trellis#1073]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

## Feature Request

Trellis uses h5bp 2.0. Version 3.0 was released a few days ago and adds/fixes some things, details here : https://github.com/h5bp/server-configs-nginx/releases/tag/3.0.0

**Comment by retlehs** [comment]
related discourse topic: https://discourse.roots.io/t/depreciating-tls-1-0-and-1-1/14905

**Comment by nlemoine** [comment]
Hi @retlehs 

I updated h5bp to the latest stable version. I tried to replicate the actual configuration but the file organization has changed so I can't get an exact match.

I didn't do anything about the SSL policies because my knowledge about SSL is very basic (that's why the PR is marked as a WIP). 

I included by default the config files of the basic conf here: https://github.com/h5bp/server-configs-nginx/blob/3.1.0/h5bp/basic.conf

Let me know if I can help.

**Comment by swalkinshaw** [comment]
Thanks @nlemoine 😄. Took a quick look and it seems like a good start.

Right now Trellis is basically using [policy_deprecated](https://github.com/h5bp/server-configs-nginx/blob/3.1.0/h5bp/ssl/policy_deprecated.conf) for SSL which isn't great...

The biggest difference is supporting TLSv1.1. Ideally we should move to 1.2 only. Here's the browser support: https://caniuse.com/#feat=tls1-2

**Comment by nlemoine** [comment]
@swalkinshaw Just came back from holidays, is there anything I can do to to move this topic forward?

What's Trellis policy regarding h5bp server configs? Adopt their entire server conf? Or just pick up some elements?

**Comment by swalkinshaw** [comment]
Closing this since we've been doing smaller updates to h5bp configs instead of all at once. https://github.com/roots/trellis/pull/1406 will update more of it as well.
