### ISSUE TITLE
wp_cli_version not ensured (just installed (once))

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#1080]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
Trellis only ensures that `wp` (phar) is installed, not its version.

## Steps to reproduce

1. Run trellis playbook, at time of writing, the `wp_cli_version` in `master` is `2.0.1` by default.
2. Set a newer `wp` version, e.g. by adding `wp_cli_version: 2.2.0` to `group_vars/all/main.yml`.
3. Run trellis playbook again, you can run just the tag `wp-cli` (using `--tags=wp-cli`) for the important part.
Notice that trellis doesn't see any changes needed and that `wp` is still in version `2.0.1`.

**Expected behavior:**
trellis updating (or even downgrading) `wp` to specified version `2.2.0`.

**Actual behavior:**
trellis doesn't update/change `wp` although its version is different to the version set in `wp_cli_version`.

**Reproduces how often:**
It always reproduces because the version of `wp` is not ensured, just its presence.

## Versions
1.0.2

## Additional information
Updating to right `wp` version is important, as I ran into an issue currently where 
older `wp` versions don't support installing/updating languages for all plugins/themes.

**Comment by swalkinshaw** [comment]
Really? 🤔 

https://github.com/roots/trellis/blob/f293d7aed7389805ddfe8e69346df5e9d2894de4/roles/wp-cli/tasks/main.yml#L27-L32

Because this task is version specific, it *should* get the new version properly. Are you able to debug this more to see where it's going wrong?

Or paste the output of the wp-cli role?

**Comment by strarsis** [comment]
I just tried it again, switching between versions and it works. 😼
