### ISSUE TITLE
Deployng to DigitalOcean returns ansible.utils.unsafe_proxy.AnsibleUnsafeText object

### ISSUE THREAD

**Issue by frivolta** [roots/trellis#1081]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
When trying to deploy to a Digital Ocean Droplet in production mode with `./bin/deploy.sh production example.com`, after provisioning the droplet I keep getting the error: 

`
The task includes an option with an undefined variable. The error was:
'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'name'

The error appears to have been in '/trellis/roles/deploy/tasks/update.yml': line 8,
column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Add known_hosts
  ^ here

fatal: [remote_ip]: FAILED! => {}
`

## Steps to reproduce

1. Provision the VM on Digital Ocean Droplet
2. Setup group vars, vault and git repo
3. Deploy using `./bin/deploy.sh production example.com`

**Expected behavior:** The process should end up deploying the latest commit to the production server

**Actual behavior:** The process exit with failed=1 and the error above

**Reproduces how often:** Always

## Versions

You can get this information from referencing `CHANGELOG.md`. Also, please include the OS and what version of the OS you're running.
• Trellis 1.0.2
• Ansible 2.7.10
• MacOs as localhost, Ubuntu 18.04 as remote server

**Comment by retlehs** [comment]
This is a personal support request that should be posted on the Roots Discourse community
