### ISSUE TITLE
"vagrant up" command returns "Cannot translate name. @ rb_sysopen - /etc/os-release (Errno::ELOOP)"

### ISSUE THREAD

**Issue by Swennet** [roots/trellis#1083]
## Description

I'm receiving the following error when running "vagrant up" inside the Trellis folder.

```
Bringing machine 'default' up with 'virtualbox' provider...
C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/hosts/suse/host.rb:20:in `initialize': Cannot translate name. @ rb_sysopen - /etc/os-release (Errno::ELOOP)
```

## Steps to reproduce

1. I followed the entire Windows guide on [Windows Basic Setup](https://roots.io/getting-started/docs/windows-basic-setup/).
2. I created a directory ~/sites/example.test in which I installed Trellis and Bedrock.
3. In VS Code I cd into the trellis folder inside my project, and run "vagrant up" from the bash terminal.
4. After "Bringing machine 'default' up with 'virtualbox' provider..." I receive the error above.

## Additional information

Full version of the error.

```
Bringing machine 'default' up with 'virtualbox' provider...
C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/hosts/suse/host.rb:20:in `initialize': Cannot translate name. @ rb_sysopen - /etc/os-release (Errno::ELOOP)
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/hosts/suse/host.rb:20:in `open'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/hosts/suse/host.rb:20:in `open'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/hosts/suse/host.rb:20:in `detect?'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/capability_host.rb:148:in `block (2 levels) in autodetect_capability_host'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/capability_host.rb:143:in `each'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/capability_host.rb:143:in `block in autodetect_capability_host'  
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/capability_host.rb:142:in `each'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/capability_host.rb:142:in `autodetect_capability_host'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/capability_host.rb:36:in `initialize_capabilities!'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/host.rb:13:in `initialize'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:544:in `new'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:544:in `host'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:207:in `block in action_runner'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:34:in `run'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:527:in `hook'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:776:in `unload'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:185:in `ensure in <main>'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:185:in `<main>'
```

**Comment by roots-ladybug** [comment]
Hi @Swennet,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).

**Comment by swalkinshaw** [comment]
Your error backtrace is all from Vagrant itself and nothing Trellis related. Did you search in the Vagrant issues for this error?

I'm not sure there's much we can do to help here unfortunately.

**Comment by Swennet** [comment]
@swalkinshaw Sorry I'm new to all of this. I will try looking for a solution in Vagrant. Thank you!

**Comment by connerbw** [comment]
I am having the same problem. 

The Trellis docs are saying to alias vagrant.exe: https://roots.io/getting-started/docs/windows-development-environment-trellis/

The vagrant docs say *not* to do this: https://www.vagrantup.com/docs/other/wsl.html

"Cannot translate name" problem goes away if Vagrant docs are followed.

**Comment by swalkinshaw** [comment]
We've updated the docs to reference the official Vagrant ones. Thanks for letting us know 👍
