### ISSUE TITLE
can't clone repo 

### ISSUE THREAD

**Issue by v3nt** [roots/trellis#1084]
* [1 ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [1 ] This request isn't a duplicate of an existing issue
* [1 ] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [1 ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

[Description of the issue]

## Steps to reproduce

can't clone repo on macos

> Cloning into 'trellis'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by swalkinshaw** [comment]
You need to be authenticated to a GitHub account to clone via the git protocol. Otherwise you can use `git clone https://github.com/roots/trellis.git`.
