### ISSUE TITLE
Error installing pip while running 'vagrant up'

### ISSUE THREAD

**Issue by hartey11** [roots/trellis#1095]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

I run `vagrant up` for the first time and get the below error message during installation:

```
==> default: Running provisioner: ansible_local...
    default: Installing Ansible...
    default: Installing pip... (for Ansible installation)
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

pip install  --upgrade ansible==2.7.5

Stdout from the command:



Stderr from the command:

bash: line 5: pip: command not found
```

I've disabled FileVault as the documentation says it doesn't work with an encrypted disk - (can I enable this?)

## Steps to reproduce
run `vagrant up` for the first time.

**Expected behavior:** [What you expect to happen]
Not sure this is the first time using trellis

**Actual behavior:** [What actually happens]
I get the above error message

**Reproduces how often:** [What percentage of the time does it reproduce?]
every time after I run `vagrant destroy` first to delete the instance and start again.

## Versions
MacOS = 10.14.5
Trellis = 1.0.3

## Additional information

**Comment by retlehs** [comment]
**This is a personal support request that should be posted on the Roots Discourse community**

dupe #1095...

this is also covered in the docs you acknowledged reading: https://roots.io/getting-started/docs/macos-development-environment-trellis/
