### ISSUE TITLE
Dynamically include present deploy hook files

### ISSUE THREAD

**Issue by circuuz** [roots/trellis#1112]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

For each deploy hook, check if the deploy hook file exist and automatically include it. Making it unnecessary to modify `/roles/deploy/defaults/main.yml` to enable the rest of the deploy hooks.

## Motivation

Main motivation would be that hopefully people would be less confused about why one of their deploy hook files aren't loading while `/deploy-hooks/build-before.yml` is working fine without any modification to the `deploy` role.

**Comment by QWp6t** [comment]
You don't need to modify the role. The role just contains the defaults. You can override those defaults in anywhere within `group_vars`. Our docs recommend `group_vars/all/main.yml` or `group_vars/all/deploy-hooks.yml`.

https://roots.io/trellis/docs/deploys/#custom-tasks
