### ISSUE TITLE
Docker as Provider

### ISSUE THREAD

**Issue by pentatonicfunk** [roots/trellis#1122]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request, my previous issue got closed directly by github but ?
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

This is probably similar with #384 , but the focus is instead of using stacking / composing docker, we use single box as base. 

## Motivation

Not all people using VirtualBox for whatever reason, so allowing docker as provider might expand trellis compatibility.

## Additional context

I've been using Vagrant in VVV with docker as provider ( i know its totally different architecture with trellis, duh). This is more or less the vagrant config i've been using :
```
provider: docker
box: tknerr/baseimage-ubuntu-18.04
```
There were some known issues in my experience, such as bash commands compat etc. Also possibly unforseen issue with ansible as mentioned in #384 , as my lack of understanding about it. So, is it worth to visit/re-visit ?, i will try to experimenting with it.

**Comment by swalkinshaw** [comment]
> So, is it worth to visit/re-visit ?, i will try to experimenting with it.

Yes I think it's worth it. I looked into this as well earlier in the year but ran into multiple issues which weren't trivial to solve. Honestly I kind of forget the details 😞

**Comment by swalkinshaw** [comment]
Nothing has progressed and the only thing I've learned over the years is that Trellis is not a good fit for Docker and would have to rely on hacks to get around fundamental differences in how Docker expects things to work.
