### ISSUE TITLE
Disable TLS 1.0 and 1.1

### ISSUE THREAD

**Issue by austinpray** [roots/trellis#1126]
https://github.com/roots/trellis/blob/3eff48a99706e0367325cb46b783812e3b84b180/roles/nginx/templates/h5bp/directive-only/ssl.conf#L3

https://blog.qualys.com/ssllabs/2018/11/19/grade-change-for-tls-1-0-and-tls-1-1-protocols

This will cap ssllabs scores to B starting january 2020

**Comment by swalkinshaw** [comment]
This came up a bit in https://github.com/roots/trellis/issues/1073

**Comment by austinpray** [comment]
:+1: 

Definitely makes sense to have the issue separated out for implementation and discussion though.
