### ISSUE TITLE
Question: Why `git archive` instead of `rsync` during deploy?

### ISSUE THREAD

**Issue by TangRufus** [roots/trellis#1154]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Background

```sh-session
$ ansible-lint --version
ansible-lint 4.2.0

$ ansible-lint deploy.yml
[306] Shells that use pipes should set the pipefail option
roles/deploy/tasks/prepare.yml:24
Task/Handler: Run git archive to populate new build dir

[306] Shells that use pipes should set the pipefail option
roles/deploy/tasks/prepare.yml:30
Task/Handler: Run git archive with subdirectory to populate new build dir
```

The related tasks:
https://github.com/roots/trellis/blob/f11a7cefbc978831d1ff6b4156298e618ff2ff80/roles/deploy/tasks/prepare.yml#L24-L34

## Questions

Why `git archive` instead of `rsync` ([synchronize](https://docs.ansible.com/ansible/latest/modules/synchronize_module.html)) during deploy?

> There can also be conflicts if your subtree directory contains
directories with the same name as directories in the repo's root.
>
> https://github.com/roots/trellis/pull/451/

Do you have an example of the conflict?

cc @swalkinshaw

**Comment by swalkinshaw** [comment]
Main two issues:

1. we had to keep a list of files to manually clean up after instead of just relying on `git archive`'s feature of auto ignoring the `.gitattributes` file.
2. the conflicts can be if a folder named `web` existed in both the repo root *and* in the subtreet path

**Comment by mAAdhaTTah** [comment]
For what it's worth, I have a project now that uses synchronize to deploy instead of using git, and it's caused issues deploying files that weren't intended to be, or node_modules being synchronized, etc. It's not a WordPress project, but does use ansible, so some relevant experience.

**Comment by TangRufus** [comment]
Thank you both.
I will [add `pipefail` option](https://github.com/roots/trellis/pull/1153) instead of changing them.
