### ISSUE TITLE
Exclude non-production environments from being indexed by search engines (since WP 5.3))

### ISSUE THREAD

**Issue by adamtomat** [roots/trellis#1157]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

WordPress 5.3 has moved away from using the "robots.txt" to **discourage** search engines to adding a meta tag to prevent a site from being **listed** in search engines.

As part of this, it is also recommended that the HTTP Header `X-Robots-Tag: noindex, nofollow` is added to **ALL** requests (including images, pdfs, videos etc). I believe this should be something Trellis should handle out-of-the-box.

## Motivation

This impacts every non-production environment. WordPress will add this meta tag to all pages it renders but it will not be applied to any assets etc. 

I suggest that this header should be added by default to non-production environments (e.g. staging) on all requests.

This solution is **recommended by one of the core team working on WordPress**. At the bottom of [this article he says](https://make.wordpress.org/core/2019/09/02/changes-to-prevent-search-engines-indexing-sites/):

> **Excluding development servers from search engines.**
>
> The most effective method to exclude development sites from being indexed by search engines is to include the HTTP Header `X-Robots-Tag: noindex, nofollow` when serving all assets for your site: images, PDFs, video and other assets.
>
> As most non-HTML assets are served directly by the web server on a WordPress site, the core software is unable to set this HTTP header. You should consult your web server’s documentation or your host to ensure these assets are excluded on development sites.

## Additional context

Here is a link to the core WP ticket discussing this:
https://core.trac.wordpress.org/ticket/43590

**Comment by retlehs** [comment]
good call! we should adapt the existing mu-plugin in bedrock for this

https://github.com/roots/bedrock/blob/ff5e28ac74f1e9aac1b44f8d197054a34eb85079/web/app/mu-plugins/disallow-indexing.php

**Comment by adamtomat** [comment]
It's not (just) a Bedrock issue though. From my understanding that mu-plugin is still doing the right thing?

That won't be called when requesting assets (e.g. a PDF) as nginx handles this as it's a file rather than routing it through WP (at least that's my understanding of how Trellis has setup nginx).

**Comment by swalkinshaw** [comment]
@adamtomat do you want to try contributing this change? It shouldn't be too bad and I can help direct you to the right place if you want.

**Comment by adamtomat** [comment]
@swalkinshaw yeah I'm up for that. Think this should be on by default, but can be disabled via config?

And I assume it's just optionally adding the header to the nginx conf under certain envs? (As opposed to conditionals within the config itself?

**Comment by swalkinshaw** [comment]
> Think this should be on by default, but can be disabled via config?

Yep 👍 

> And I assume it's just optionally adding the header to the nginx conf under certain envs? (As opposed to conditionals within the config itself?

Yeah I'd just use a conditional like this: https://github.com/roots/trellis/blob/76337fd20e1a137be6487d473d2d8d4ee7997e9e/roles/wordpress-setup/templates/wordpress-site.conf.j2#L28-L30

Maybe define a named `block` for it as well to make it easier to override.

I might be even be okay with skipping an explicit config option for this and just making people override the template since I assume it would be *quite* rare? 🤷‍♂

**Comment by TangRufus** [comment]
Instead of `{% if env == 'development' -%}`, we can make a variable for that, similar to `h5bp_cache_file_descriptors_enabled`

https://github.com/roots/trellis/blob/76337fd20e1a137be6487d473d2d8d4ee7997e9e/roles/wordpress-setup/defaults/main.yml#L42-L44

**Comment by adamtomat** [comment]
Do you mean something like this? @TangRufus 

```
not_prod: "{{ env != 'production' }}"
robots_tag_header: "{{ item.value.robots_tag_header | default({}) }}"
robots_tag_header_enabled: "{{ robots_tag_header.enabled | default(not_prod) }}"
```

**Comment by TangRufus** [comment]
I mean:

```
not_prod: "{{ env != 'production' }}"
robots_tag_header_enabled: "{{ robots_tag_header.enabled | default(not_prod) }}"
```

Add the `robots_tag_header` if you see fit.

**Comment by swalkinshaw** [comment]
Closed by https://github.com/roots/trellis/pull/1158.

Thanks for bringing this up and implementing it @adamtomat 😄

**Comment by nickkeenan** [comment]
The check for "any env other than production" ended up causing some issues on my last round of Trellis upgrades.  In one of my projects, I have a number of different "production" client sites that use an environment name other than "production" - these all got flagged as noindex and caused not a small amount of havoc as a result until we could address the issue.  

Would it be possible to tie this logic to the wp_env value in group_vars (which IS 'production') rather than the 'env' name?

**Comment by adamtomat** [comment]
@nickkeenan Interesting idea. Will let one of the devs answer that directly as I'm not sure if you can get that variable out at the nginx level.

In the meantime, you can enable this behaviour per site by setting this in your site config (as the 'production' check is only the default behaviour if this flag is not set):

```yaml
wordpress_sites:
  example.com:
    ...
    robots_tag_header:
      enabled: true
```

**Comment by swalkinshaw** [comment]
`{{ site_env.wp_env }}` should be available within the Nginx template 👍  but it defaults to `env` anyway...

@nickkeenan I guess you manually override to always be `production` while `env` varies?

**Comment by nickkeenan** [comment]
@swalkinshaw For sure, that's what we've done on this project, which is a fine permanent solution for our use case. Just thought I'd mention that this use case exists!  

Thanks for the reminder about adjusting robots_tag_header directly in group_vars @adamtomat, that's helpful.  This just struck me as a gotcha that could cause surprising issues in some situations so I wanted to pass it along.

Many thanks!

**Comment by TangRufus** [comment]
Perhaps we should promote [`not_dev`](https://github.com/roots/trellis/blob/17430191bb7211545eb63ba3ba989ee95c262c5f/roles/wordpress-setup/defaults/main.yml#L41) and [`not_prod`](https://github.com/roots/trellis/blob/17430191bb7211545eb63ba3ba989ee95c262c5f/roles/wordpress-setup/defaults/main.yml#L53) to [`group_vars/all/main.yml`](https://github.com/roots/trellis/blob/17430191bb7211545eb63ba3ba989ee95c262c5f/group_vars/all/main.yml).

Or, allow users to define `dev_envs` and `prod_envs` lists, then let Trellis and other 3rd-party roles calculate `not_dev` and `not_prod` accordingly.
