### ISSUE TITLE
Add environment variable `WP_DEBUG_LOG=/srv/www/example.com/logs` to `.env`

### ISSUE THREAD

**Issue by TangRufus** [roots/trellis#1159]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

Add environment variable `WP_DEBUG_LOG=/srv/www/example.com/logs` to `.env`

> Reminder: Any values set to WP_DEBUG_LOG and WP_DEBUG_DISPLAY will be ignored unless WP_DEBUG is set to true.
>
> -- https://make.wordpress.org/core/2019/01/23/miscellaneous-developer-focused-changes-in-5-1/

---

Bedrock will need to be updated when this is implemented.

**Comment by swalkinshaw** [comment]
Agreed it should be set to `/logs` 👍
