### ISSUE TITLE
Add nvm support / switch back to npm in build-deploy script

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#1162]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary
NPM/composer package versions of a theme are already locked, but the node version is not.
Builds can fail when the wrong node version (e.g. system version) is used for building.

## Motivation
Also locking the node version (using nvm as an appropriate tool) alleviates the issue of failing builds due to incompatible node version.

## Additional context
Related discussion in roots.io discourse: https://discourse.roots.io/t/how-to-update-node-dependencies-in-sage-8/17813

## PR
https://github.com/roots/trellis/pull/1161

**Comment by swalkinshaw** [comment]
@strarsis mentioned it on the PR but ideally this is added to our docs. Do you want to contribute it?

**Comment by strarsis** [comment]
@swalkinshaw: This docs page would make most sense to have the example code added to?:
https://github.com/roots/docs/blob/docs/docs/trellis/master/deployments.md

**Comment by strarsis** [comment]
I just noticed that just prefixing the `node` related commands with `$NVM_DIR/nvm-exec` adds nvm support! `command: $NVM_DIR/nvm-exec  npm install` and `command: $NVM_DIR/nvm-exec  npm run build:production`.

**Comment by strarsis** [comment]
```yml
# Placeholder `deploy_build_before` hook for building theme assets on the
# host machine and then copying the files to the remote server
#
# ⚠️ This example assumes your theme is using Sage 9
# An example for themes built with Sage 8 can be found at: https://git.io/vdgUt
#
# Uncomment the lines below and replace `sage` with your theme folder
#
# ---
# - name: Install npm dependencies
#   command: $NVM_DIR/nvm-exec  npm install
#   delegate_to: localhost
#   args:
#     chdir: "{{ project_local_path }}/web/app/themes/sage"
#
# - name: Install Composer dependencies
#   command: composer install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader --no-scripts --classmap-authoritative
#   args:
#     chdir: "{{ deploy_helper.new_release_path }}/web/app/themes/sage"
#
# - name: Compile assets for production
#   command: $NVM_DIR/nvm-exec  npm run build:production
#   delegate_to: localhost
#   args:
#     chdir: "{{ project_local_path }}/web/app/themes/sage"
#
# - name: Copy production assets
#   synchronize:
#     src: "{{ project_local_path }}/web/app/themes/sage/dist"
#     dest: "{{ deploy_helper.new_release_path }}/web/app/themes/sage"
#     group: no
#     owner: no
#     rsync_opts: --chmod=Du=rwx,--chmod=Dg=rx,--chmod=Do=rx,--chmod=Fu=rw,--chmod=Fg=r,--chmod=Fo=r

````

**Comment by swalkinshaw** [comment]
Nice solution!

🤔 we should really have a "Sage Integration" page in our docs. It can mention the default `deploy_build_before` and how to use it. Then it could contain this nvm usage too.

**Comment by swalkinshaw** [comment]
Closed by https://github.com/roots/docs/pull/225
