### ISSUE TITLE
Update to PHP 7.4

### ISSUE THREAD

**Issue by markjaquith** [roots/trellis#1163]
## Summary

Trellis should install PHP 7.4.

## Motivation

Support for the latest PHP features.

## Additional context

- [PHP 7.3 was merged into Trellis][merge-7.3] about two week after its release.
- [PHP 7.4 has been out][php-releases] since November 28, 2019.
- [WordPress 5.3 fully supports PHP 7.4][wp] and has been out since November 12, 2019.

[merge-7.3]: https://github.com/roots/trellis/pull/1052
[php-releases]: https://www.php.net/supported-versions.php
[wp]: https://wordpress.org/news/2019/11/kirk/

**Comment by swalkinshaw** [comment]
Yeah tbh I only realized we forgot about this recently 🙈 

Do you want to take a crack at it?

**Comment by markjaquith** [comment]
>Do you want to take a crack at it?

@swalkinshaw Sure!
