### ISSUE TITLE
Problem with user restrictions when updating to 1.4.0 

### ISSUE THREAD

**Issue by vdrnn** [roots/trellis#1165]
I updated from 1.3.0 to 1.4.0. Provisioning runs through smoothly. 
When I try to deploy though I'm receiving this issue: 

`Sorry, user web is not allowed to execute '/usr/sbin/service php7.4-fpm
reload' as root on staging.verybestof.ch.
fatal: [staging.verybestof.ch]: FAILED! => {"changed": true, "cmd": "sudo service php7.4-fpm reload", "delta": "0:00:00.018269", "end": "2020-04-02 19:48:55.775262", "rc": 1, "start": "2020-04-02 19:48:55.756993", "stderr_lines": ["Sorry, user web is not allowed to execute '/usr/sbin/service php7.4-fpm reload' as root on staging.verybestof.ch."], "stdout": "", "stdout_lines": []}`

**Comment by Log1x** [comment]
You might need to update your [sudoers](https://github.com/roots/trellis/blob/6959e3ec0e7c4095ea4d19340ed5b394f278ea60/group_vars/all/users.yml#L21)
