### ISSUE TITLE
what changes are needed to use mysql 5.7 / mysql 8 in place of mariadb?

### ISSUE THREAD

**Issue by vesper8** [roots/trellis#1174]
Hi there, been using Trellis for years now. I run a few Wordpress sites but I also run lots of Laravel sites. My current project requires the use of ST_Distance_Sphere which unfortunately is not supported by MariaDB at all https://mariadb.com/kb/en/mysqlmariadb-spatial-support-matrix/

but is supported by Mysql 5.7+

I understand the charm of using MariaDB for its open-source license but I have no choice here and I am dealing with a server that has already been provisioned with the latest version of Trelis (PHP 7.4 and all that).

I'm sure this request is at least somewhat out of scope, but I would really appreciate it if someone knowledgeable could explain what changes I would need to make in order to successfully migrate from Mariadb to Mysql (either 5.7 or 8 is ok by me). In the worst-case scenario I am also willing to have to dump/restore all of my MySQL tables. But I would like to perform this migration (and any further server provisioning) using Ansible and Trellis rather than doing it manually.

Although the commands for doing it manually would also be much appreciated.

Many thanks for your time and for this awesome project

**Comment by swalkinshaw** [comment]
Have you looked into how/where MariaDB is used? It's very minimal.

See https://github.com/roots/trellis/blob/master/roles/mariadb/tasks/main.yml

You'd probably only have to change these two variables: https://github.com/roots/trellis/blob/0d4b2611a3ca5b02d47f46290ada7fd439a84f6a/roles/mariadb/defaults/main.yml#L5-L6

**Comment by vesper8** [comment]
thanks for the advice. I just had a lot of trouble switching over but now I know what was wrong. On top of replacing those two packages, it's important that you manually remove the installed ppa by running `sudo rm /etc/apt/sources.list.d/nyc2_mirrors_digitalocean_com_mariadb_repo_10_2_ubuntu.list`

And that you comment out / remove this block from `roles/mariadb/tasks/main.yml`

```
# - block:
#   - name: Add MariaDB APT key
#     apt_key:
#       keyserver: "{{ mariadb_keyserver }}"
#       id: "{{ mariadb_keyserver_id }}"

#   - name: Add MariaDB PPA
#     apt_repository:
#       repo: "{{ mariadb_ppa }}"
#       update_cache: yes
```

I also manually uninstalled mariadb and then I ran the playbook and let it install Mysql, which defaulted to the 5.7.29 version

Not sure if this would have worked if I hadn't manually uninstalled mariadb first

**Comment by swalkinshaw** [comment]
Ah yeah that all sounds correct if you had previously provisioned a server with MariaDB 👍 thanks for sharing
