### ISSUE TITLE
`ip_whitelist` does not whitelist correct IP on development 

### ISSUE THREAD

**Issue by raph-topo** [roots/trellis#1181]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

In `group_vars/all/main.yml`:
```yaml
ip_whitelist:
  - "{{ (env == 'development') | ternary(ansible_default_ipv4.gateway, ipify_public_ip | default('')) }}"
```
When setting up development, this does not recognize the developer's local IP.

I detected this when testing Fail2ban ban actions, which do `Ignore` the correct IP on staging and production, but not on development. Yet, the above statement shows Trellis' intention to actually whitelist the developer's local IP.

## Steps to reproduce

1. Ensure `hosts/development` contains:
```ini
[development]
192.168.50.5 ansible_connection=local

[web]
192.168.50.5 ansible_connection=local
```
2. Add the following to `roles/fail2ban/tasks/main.yml`:
```yaml
- name: Debug
  debug:
    var: ip_whitelist
```
3. Run `ansible-playbook dev.yml --tags fail2ban`
4. Read:
```
TASK [fail2ban : Debug] ************************************************************************************************
ok: [development_host] => {
    "ip_whitelist": [
        "xxx.xxx.xxx.xxx"
    ]
}
````

**Expected behavior:**
The debug statement should read:

```
"ip_whitelist": [
        "192.168.50.1"
    ]
```

This is confirmed by Fail2ban reading `Ban 192.168.50.1` when I try to brute-force on development.

**Actual behavior:**
In my case, the debug statement instead reads:
```
"ip_whitelist": [
        "10.0.2.2"
    ]
```
`10.0.2.2` does not correspond to any IP range on my network.
**Reproduces how often:** always when setting up development.
## Versions
HEAD (1.4.0+) on Windows WSL

## Additional information
This might be an Ansible bug, but either way this produces an unexpected behavior in Trellis.
Maybe Trellis should use another fact than `ansible_default_ipv4.gateway`?

**Comment by swalkinshaw** [comment]
`10.0.2.2` is from the Vagrant VM. So it makes sense why that's the value from `ansible_default_ipv4.gateway` but agreed that it's wrong and not helpful 🤔 I don't know if something changed at some point with Ansible... otherwise I'm not sure how it was ever really supposed to work.

It seems like `ip_whitelist` in development should use `ansible_all_ipv4_addresses`. It's an array of all IPs including `192.168.50.5` when I just tested it.

Could you try that out too and see if it works?

**Comment by raph-topo** [comment]
Yes, issue solved.

**Comment by raph-topo** [comment]
@swalkinshaw  I have to backtrack on this, I missed one digit.
As you said, `192.168.50`**`.5`** gets added to the whitelist, but that's the development vagrant's own IP, not that of the host machine. 
We need `192.168.50`**`.1`** in the whitelist.
