### ISSUE TITLE
No usable default provider could be found for your system.

### ISSUE THREAD

**Issue by chrish-d** [roots/trellis#1182]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

After following the steps to install on the Github README, I get the following error when running `trellis up`

> No usable default provider could be found for your system.

## Steps to reproduce

1. Install latest version of Vagrant and Virtualbox
1. Run `trellis new example.test`
2. `cd` into the example.test directory
3. Run `trellis up`

**Comment by TangRufus** [comment]
Do you have vagrant and virtualbox installed?
If yes, what versions?

Besides the readme, there are more docs at https://roots.io/docs/getting-started/macos/

**Comment by chrish-d** [comment]
@TangRufus Yeah, `Vagrant 2.2.9` and `Virtualbox 16.1`. I've also tried with an older version of Virtualbox, which was `15.something`

**Comment by swalkinshaw** [comment]
There's not much we can help with here since that's a Vagrant issue. You can google "Vagrant No usable default provider could be found for your system" to find a lot of resources about it and hopefully find a solution.

I just set up a new computer myself and used Homebrew to install Vagrant + Virtualbox and everything worked as expected.

**Comment by aterreno** [comment]
Still happening, latest Vagrant and Virtualbox. 
It's not a vagrant problem @swalkinshaw , if I run `trellis up` it shows that error, if I run `vagrant up` it works

**Comment by swalkinshaw** [comment]
Oh interesting! Okay this is really a trellis-cli issue then but I'll look into it, thanks.
