### ISSUE TITLE
when: web_sudoers | bool evaluates to false

### ISSUE THREAD

**Issue by nextgenthemes** [roots/trellis#1199]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

I am just wanted to deploy trellis on 20.04 with server setup with this PR #1197 but it failed because on the restart php fpm task.

I noticed that the sudoers entry was missing and then found out that the task is actually skipped. This `| bool` changes come because of deprecation warnings like this right?

> [DEPRECATION WARNING]: evaluating 'web_sudoers' as a bare variable, this behaviour will go away and you might need to add |bool to 
the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle. This feature will be removed in version 2.12. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

But it seems that actually doing what they say is **not** working. At least not for 2.9.9. I removed the `| bool` and the sudoers file gets created as expected.

I think there were other changes recently to get rid of the warnings. The one I removed to get it to work was this #1195

## Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

## Versions

ansible 2.9.9
Trellis: #1197

## Additional information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by swalkinshaw** [comment]
FIxed by #1200

**Comment by swalkinshaw** [comment]
I searched the codebase and couldn't find any other uses of ` | bool` on lists.

**Comment by raph-topo** [comment]
Thanks for catching and correcting this! Surprisingly, I did not get an error on restart PHP FPM… 😯
