### ISSUE TITLE
Re-provisioning existing server on 16.04 fails on Add Nginx APT key task.

### ISSUE THREAD

**Issue by dalepgrant** [roots/trellis#1213]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [ ] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Re-provisioning existing server using 16.04 fails on Add Nginx APT key task.

## Steps to reproduce

1. `vagrant reload --provision`
2. Ruh roh, error.

**Expected behavior:** 
Successful re-provision

**Actual behavior:** 

Error readout:
```
TASK [nginx : Add Nginx APT key] ***********************************************
System info:
  Ansible 2.9.12; Vagrant 2.2.9; Darwin
  Trellis version (per changelog): "Switch to official Nginx Ubuntu package"
---------------------------------------------------
Error fetching key ABF5BD827BD9BF62 from keyserver:
https://nginx.org/keys/nginx_signing.key
gpg: requesting key 7BD9BF62 from https server nginx.org
gpg: no handler for keyserver scheme `https'
gpg: keyserver receive failed: keyserver error
fatal: [default]: FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key adv --no-tty --keyserver https://nginx.org/keys/nginx_signing.key --recv ABF5BD827BD9BF62", "rc": 2, "stderr_lines": ["gpg: requesting key 7BD9BF62 from https server nginx.org", "gpg: no handler for keyserver scheme `https'", "gpg: keyserver receive failed: keyserver error"], "stdout": "Executing: /tmp/tmp.vFZ4RMyTg2/gpg.1.sh --no-tty\n--keyserver\nhttps://nginx.org/keys/nginx_signing.key\n--recv\nABF5BD827BD9BF62\ngpgkeys: protocol `https' not supported\n", "stdout_lines": ["Executing: /tmp/tmp.vFZ4RMyTg2/gpg.1.sh --no-tty", "--keyserver", "https://nginx.org/keys/nginx_signing.key", "--recv", "ABF5BD827BD9BF62", "gpgkeys: protocol `https' not supported"]}
```

**Reproduces how often:** 100%

## Versions

Trellis 1.5.0, Switch to official Nginx Ubuntu package
macOS Catalina 10.15.6

## Additional information

Change introduced in c6f648f30b91bf5444a17ef27de5699617eff0a2.

I did manage to find a quick solution, which was to `vagrant ssh` and run `sudo apt install gnupg-curl`. Solution taken from https://github.com/MicrosoftDocs/azure-docs/issues/29354#issuecomment-610638298

>To be able to use https on Ubuntu 16.04, I had to run sudo apt install gnupg-curl as per this website before running the apt-key command.

**Comment by swalkinshaw** [comment]
Ah yeah 16.04 doesn't handle https apt keyservers unfortunately. I'm inclined to leave this be since 16.04 is fairly old and we don't guarantee compatibility with new Trellis versions.

**Comment by dalepgrant** [comment]
Roger that! Just came back here to mention this also affects re-provisioning staging and production servers - my initial report was only for development. If anyone else ends up here, the same steps above work, only instead of `vagrant ssh` you're using `ssh admin@yourserverIP`. Then you can run `sudo apt install gnupg-curl` and use the password set in your vault ([see here](https://github.com/roots/trellis/blob/master/group_vars/production/vault.yml#L7)).

**Comment by swalkinshaw** [comment]
Closing this since there's already a workaround.

Another fix is to just override the default variable and use `http`:

```yaml
nginx_keyserver: "http://nginx.org/keys/nginx_signing.key"
```

**Comment by broskees** [comment]
@swalkinshaw Where would you place that?

**Comment by swalkinshaw** [comment]
`group_vars/all/main.yml` works

**Comment by mariusmateoc** [comment]
@swalkinshaw Same problem seems to appear on 20.04 now: https://discourse.roots.io/t/error-during-provision-on-local-vm-add-nginx-apt-key/21506

When I followed steps in documentation using trellis-cli I've encountered the same error. The workaround from above fix that issue. Also one o the following works:

1. To keep using `https` we need to change the `keyserver` with `url` on [nginx_task](https://github.com/roots/trellis/blob/master/roles/nginx/tasks/main.yml#L4) what is used in [Official Ansible role for NGINX](https://github.com/nginxinc/ansible-role-nginx/blob/main/tasks/keys/setup-keys.yml#L23)

2. We can also change `nginx_keyserver: "keyserver.ubuntu.com"` to fix that error. Taken from [nginx.com](https://www.nginx.com/resources/wiki/start/topics/tutorials/install/#official-debian-ubuntu-packages)

**Comment by eriteric** [comment]
Same thing happening with 22.04 now, overwriting it to keyserver.ubuntu.com still works.
