### ISSUE TITLE
site_env in deploy/vars/main.yml overwrites provided vars

### ISSUE THREAD

**Issue by mAAdhaTTah** [roots/trellis#1218]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

In `roles/deploy/vars/main.yml`, `site_env` is defined is basically the exact same way it's defined in `deploy.yml`. However, because it's defined in `vars`, it "wins" when creating the `.env` file.

I'm using Trellis alongside a Gatsby site and am borrowing the `deploy` role to do so. And it mostly works! The role gets all the files into place and the hooks do the app-specific logic (in my case, running the build, hence needing the .env file–yes, I've installed node on the server to do this). But the wrong .env file is created cuz I've set a custom `site_env` in my playbook that gets overriden.

## Steps to reproduce

1. Create a new playbook using the `deploy` role and a custom `site_env`.
2. Run the deployment
3. Note that the `.env` file created uses the `site_env` from the role.

**Expected behavior:** [What you expect to happen]

`site_env` from my playbook should overwrite the role's `site_env`.

**Actual behavior:** [What actually happens]

`site_env` from the role is used.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always.

## Versions

I'm running Trellis 1.3.0 but it's def present in master.

## Additional information

The fix is fairly easy: remove or move to `defaults`. Happy to open a PR but wondering which you'd prefer. There's also a bit of duplication in this area (`wordpress_env_defaults` is also present in box the `deploy.yml` & `deploy` roles, and overridden in the same way).

**Comment by swalkinshaw** [comment]
Can you post your playbook (or an edited version of it)? I want to know how the vars are being defined exactly.

**Comment by mAAdhaTTah** [comment]
@swalkinshaw Sure, I'll get that when I'm back at my desktop. The short version is I'm merging in variables from one of the `wordpress_sites` in with the variables from this frontend deploy.

I realize now I may have an old version of the `deploy.yml` as well, cuz I have a version where most of the deploy variables are defined in the playbook, so I was following that, which is why I was surprised it was getting overwritten.

**Comment by swalkinshaw** [comment]
Okay well feel free to submit a PR. I'm still a little confused 😄

**Comment by mAAdhaTTah** [comment]
This is my frontend.yml playbook. It's responsible for deploying the Gatsby front-end. It's mostly a copy of the `deploy.yml` but has a few variables defined specifically for the FE deploy:

```
---
- import_playbook: variable-check.yml
  vars:
    playbook: deploy.yml

- name: Test Connection
  hosts: web:&{{ env }}
  gather_facts: false
  vars:
    dynamic_user: false
  roles:
    - { role: connection, tags: [connection, always] }

- name: Deploy WP site
  hosts: web:&{{ env }}
  remote_user: "{{ web_user }}"
  vars:
    site: "jamesdigioia.com"
    project: "{{ wordpress_sites[site] | combine(frontend) }}"
    project_root: "{{ www_root }}/frontend"
    site_env: "{{ frontend.env | combine(wordpress_sites[site].env, vault_frontend.env, wordpress_sites[site].env) }}"
    deploy_build_after: "{{ playbook_dir }}/deploy-hooks/build-after-frontend.yml"
    deploy_finalize_before: []
    deploy_finalize_after: []
    deploy_share_after: "{{ playbook_dir }}/deploy-hooks/share-after-frontend.yml"
  pre_tasks:
    - name: Ensure site is valid
      delegate_to: localhost
      fail:
        msg: "Site `{{ site | default('') }}` is not valid. Available sites to deploy: {{ wordpress_sites.keys() | join(', ') }}"
      when: wordpress_sites[site | default('')] is not defined
    - name: Ensure repo is valid
      delegate_to: localhost
      fail:
        msg: |
          Invalid Git repository.
          Ensure that your site's `repo` variable is defined in `group_vars/{{ env }}/wordpress_sites.yml` and uses the SSH format (example: git@github.com:roots/bedrock.git)
          More info:
          > https://roots.io/trellis/docs/deploys/
      when: project.repo is not defined or project.repo is not match("^ssh://.+@.+|.+@.+:.+")
  roles:
    - deploy
```

The main thing to note is the inclusion of the `site_env` variable, which merges in a new variable (`frontend`) into the "jamesdigioia.com" wordpress site configuration. The suggestion is just to move `site_env` from `vars/main.yml` to `defaults/main.yml`. I can open a PR for this though.

**Comment by mAAdhaTTah** [comment]
Closing as `wontfix`. See #1220.
