### ISSUE TITLE
mount.nfs: requested NFS version or transport protocol is not supported. How to change mount options?

### ISSUE THREAD

**Issue by nextgenthemes** [roots/trellis#1219]
```
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 192.168.50.1:/uncrypted/websites/nextgenthemes.com /vagrant-nfs-nextgenthemes.com

Stdout from the command:



Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
```

I know this is mainly a vagrant issue but there is an issue that suggests I may be able to fix this directly from the vagranfile.

My issue is I do not speak ruby and vagrant config. I tried a few things but they all failed. What part of the config do I need to change?

I do not understand the `folder.fetch` thing or what part of the config I need to change. I like to try to switch of protocol 4 over TCP so it mounts like this `mount -o vers=4,tcp`. Or would there be an issue using protocol 4 with Trellis? I have no idea about NFS. I just hold packages back for ages now to prevent this and I just updated again.

Not sure about changing Trellis config if this works out probably best keeping it that way for other older systems.

**Comment by TangRufus** [comment]
Can you give https://github.com/roots/docs/pull/207/files a try?

**Comment by nextgenthemes** [comment]
I already asked and answered my own question on discourse. Not on maxOS but openSUSE tumblewweed.

I figured it out: I edited both lines that end with type: ‘nfs’ in the vagrantfile to

`type: 'nfs', mount_options: ["vers=4,tcp"]`

Based on configs it should also support protocol version 3, not sure why it does not work, but I am glad I finally solved this, I hold a bunch of package updates back for a long time because if this.

Maybe it makes sense to use version 4 by default in trellis or detect tumbleweed and use it only on that.

**Comment by swalkinshaw** [comment]
I'm assuming openSUSE tumbleweed usage for a host is quite rare so I don't think it's worth it to detect it.

I'd welcome a change to make it easier to set the mount options in the vagrant yml configs though. Glad you got it fixed 😄

**Comment by slackday** [comment]
I get the same error on every box using macOS Big Sur and Vagrant 2.2.14. Destroy/up does not work. Have also tried to check out brand new project and trellis/bedrock with same result. Have tried every fix I could find with same error as above.

I got my computer back from repair and they have installed Big Sur which seems to be completely broken with Trellis. 

Any fix for this on macOS or a hint what the underlying issue can be? Else I might have to downgrade OS.

**Comment by swalkinshaw** [comment]
@slackday some people in https://discourse.roots.io/t/big-sur-11-0-1-20b29/19510/15 had an issue with Vagrant but 2.2.14 should have fixed it... either way you could try downgrading ~2 vagrant versions.
