### ISSUE TITLE
Error on initial vagrant up

### ISSUE THREAD

**Issue by nikitasol** [roots/trellis#1224]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Trying to figure out the issue. After destroying vagrant box to update, I ran into an issue when vagrant up reached TASK: [wordpress-install : Install WP]. Here is the message:

```
The conditional check ''WordPress is already installed.' not in
wp_install.stdout and 'The network already exists.' not in wp_install.stdout'
failed. The error was: error while evaluating conditional ('WordPress is
already installed.' not in wp_install.stdout and 'The network already
exists.' not in wp_install.stdout): Unable to look up a name or access an
attribute in template string ({% if 'WordPress is already installed.' not in
wp_install.stdout and 'The network already exists.' not in wp_install.stdout
%} True {% else %} False {% endif %}).
Make sure your variable name does not contain invalid characters like '-':
argument of type 'AnsibleUndefined' is not iterable
fatal: [default]: FAILED! => {}
```

I solved it for the existing projects adding site_install: false.

Now I have started a new project just following normal and usual steps a per installation instructions and have run into the same error. All required dependences are installed and up to date: composer, wp-cli, vagrant, virtualbox.

## Steps to reproduce

Just followed installation instructions.

## Versions

1.5.0

**Comment by nikitasol** [comment]
Also it's important to note that though the task fails, the vagrant up does create the needed environment and I can access the dev page, install wordpress and from what I can see everything works and I can re-provision without any errors later on.

**Comment by swalkinshaw** [comment]
Honestly I have no idea what the problem could be 🤔 I don't think I've ever seen this error before which implies it's quite rare and something weird is going on
