### ISSUE TITLE
"Enable or disable Nginx sites" task doesn't work with ansible 2.10.1

### ISSUE THREAD

**Issue by mockey** [roots/trellis#1225]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

"Enable or disable Nginx sites" task in wordpress-setup role doesn't work with ansible 2.10.1

## Steps to reproduce

1. Provision

**Expected behavior:** Finish provisioning

**Actual behavior:** Error: src option requires state to be 'link' or 'hard'

**Reproduces how often:** Always

## Versions
trellis: HEAD
OS: Linux Mint 20 Cinnamon
ansible 2.10.1
vagrant 2.2.10

The problem seems to be: 
`state: "{{ item.enabled | default(true) | ternary('link', 'absent') }}"`
According to the docs:
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#parameter-src
only `link` or `hard` are allowed as state when a src parameter is defined.

I created two separate tasks for enable and disable using `when: item.enabled | default(true)` for enable and `when: not item.enabled | default(false)` for disable. Seems to work but I'm not sure if that's the best solution. I can make a PR if you want.

**Comment by TangRufus** [comment]
Perhaps we should separate the task into 2 tasks - one for `item.enabled` is `true`; one for not `true`.

Pull requests are always welcomed.

**Comment by MWDelaney** [comment]
Here's a quick-and-dirty fix for current projects:

https://github.com/roots/trellis/pull/1226
