### ISSUE TITLE
Certificate generation error (empty cert file)

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#1236]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
The domains of a newly added site are not validated, the Trellis playbook fails at the point where the certificate renewal script is invoked:
````
TASK [letsencrypt : Generate the certificates] ***************************************************************************************************************
System info:
  Ansible 2.9.10; Linux
  Trellis version (per changelog): "Allow WP cron intervals to be configurable"
[WARNING]: Failure using method (v2_runner_on_failed) in callback plugin (<ansible.plugins.callback.output.CallbackModule object at 0x7f51b9e1e280>): 'bright
black'
````
Manually invoking the cert renewal script shows the error:
````
Traceback (most recent call last):
  File "./renew-certs.py", line 49, in <module>
    bundled_hashed_cert_file.write(new_bundled_cert)
TypeError: write() argument must be str, not bytes
````
The cert file for that site just is empty and HTTPS doesn't work.

## Steps to reproduce
Not sure how to reproduce this. Latest Trellis and adding a new site to it.
One thing that stands out is that I have swapped its only canonical domain from something.example.com to just example.com.

**Expected behavior:**
That the certificate is correctly signed and HTTPS works for that site.

**Actual behavior:**
Trellis playbook run fails, manually invoking the cert renewal script shows an error.

**Reproduces how often:**
The bug reproduces unless HTTPS is disabled and self-signing is used for that particular site.

## Versions
````
Allow WP cron intervals to be configurable ([#1222](https://github.com/roots/trellis/pull/1222))
````

## Additional information
IPv4 resolves fine for the domains of that site. IPv6 has been removed and no AAAA records resolve for the domains.
ansible 2.9.10

**Comment by swalkinshaw** [comment]
> TypeError: write() argument must be str, not bytes

I remember this coming up during Python 3 compatibility work. What Ubuntu version are you using? You can try one thing quickly if you want:

```diff
diff --git roles/letsencrypt/templates/renew-certs.py roles/letsencrypt/templates/renew-certs.py
index 1dc215f..72106e3 100644
--- roles/letsencrypt/templates/renew-certs.py
+++ roles/letsencrypt/templates/renew-certs.py
@@ -39,7 +39,7 @@ for site in {{ sites_using_letsencrypt }}:
         ).format(csr_path)

         try:
-            new_bundled_cert = check_output(cmd, stderr=STDOUT, shell=True)
+            new_bundled_cert = check_output(cmd, stderr=STDOUT, shell=True, universal_newlines=True)
         except CalledProcessError as e:
             failed = True
             print('Error while generating certificate for {}\n{}'.format(site, e.output), file=sys.stderr)
```

**Comment by strarsis** [comment]
Ubuntu on ansible workstation/provisioner:
````
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
````

Ubuntu on Trellis server/target system:
````
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
````

**Comment by strarsis** [comment]
@swalkinshaw: Thanks, I will try this fix.

ansible fails always with the same generic error mesage, for any kind of error (like network timeout):
````
[WARNING]: Failure using method (v2_runner_on_failed) in callback plugin (<ansible.plugins.callback.output.CallbackModule object at 0x7f51b9e1e280>): 'bright
black'
````
The error handler doesn't output the actual error but causes an error on its own.

**Comment by strarsis** [comment]
@swalkinshaw: So there is a bug in Trellis domain handling for certs:
When the canonical domain is changed, the renewal script doesn't notice that change and doesn't update the cert for the new canonical domain.

**Comment by strarsis** [comment]
@swalkinshaw: A combination of using your fix/workaround and manually removing the cert file of that site fixed the issue, a proper cert has been generated for the new canonical domain of the site and HTTPS works now for that site.

**Comment by swalkinshaw** [comment]
That's strange if true because we generate cert IDs that take into account *all* hosts:

https://github.com/roots/trellis/blob/86b75343f5178ef70f2341e1b2238b6e34c1f7e5/roles/letsencrypt/tasks/certificates.yml#L16-L28

`site_hosts` includes both canonical and redirect hosts. So any change to either should trigger a new ID and a new certificate renewal.

**Comment by strarsis** [comment]
@swalkinshaw: Hm, right. Then it was probably the workaround. I don't want to retry this on a production server, so I would have to set up a VM and try to reproduce this issue (though it would be a bit harder to try this with LE and a domain).

**Comment by swalkinshaw** [comment]
I merged in the `universal_newlines` fix in https://github.com/roots/trellis/pull/1246.

I'll consider this closed since the other issue brought up isn't really actionable. But feel free to open another issue if something similar happens again.
