### ISSUE TITLE
Small issue with nginx mainline repo and apt update

### ISSUE THREAD

**Issue by mockey** [roots/trellis#1239]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

The current nginx mainline repo causes a warnng with `apt update`:
```
N: Skipping acquire of configured file 'nginx/binary-i386/Packages' as repository 'http://nginx.org/packages/mainline/ubuntu bionic InRelease' doesn't support architecture 'i386'
```

## Steps to reproduce

1. run `apt update`

**Expected behavior:** No warning/error message.

**Actual behavior:** Warning/error message.

**Reproduces how often:** 100%

## Versions

HEAD
OS: Linux Mint 20

## Additional information

I guess adding `[arch=amd64]` should fix this, i.e.:
`nginx_ppa: "deb [arch=amd64] http://nginx.org/packages/mainline/ubuntu {{ ansible_distribution_release }} nginx"`
in `roles/nginx/defaults/main.yml`

**Comment by swalkinshaw** [comment]
👍 do you want to make that change?

**Comment by mockey** [comment]
Yes, I can make a PR tomorrow.
