### ISSUE TITLE
Upgrading from Xdebug 2 to 3

### ISSUE THREAD

**Issue by kennyr87** [roots/trellis#1255]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Thanks for all the great work on Trellis.

Xdebug 3 is out and includes major changes in functionality and configuration compared to Xdebug 2. Trellis ships with default support for Xdebug 2 style options, no default support for Xdebug 3 style config options yet.

## Motivation

Why are we doing this? 

Provide default support for Xdebug 3 config options.

What use cases does it support? 

Debugging with Xdebug.
 
What is the expected outcome?

Default Xdebug 3 config options set in `roles/xdebug/defaults/main.yml`

## Additional context

[Xdebug 3 Upgrade Guide](https://xdebug.org/docs/upgrade_guide)

**Comment by adambrgmn** [comment]
It would be great to get xdebug v3 out of the box. But for those who end up here – it doesn't take much to actually get it working with your current setup, here's the changes I needed to do:

`group_vars/development/php.yml`:

```diff
- xdebug_remote_enable: 1
- xdebug_remote_autostart: 1
- xdebug_remote_connect_back: 1
+ xdebug_mode: "debug"
+ xdebug_start_with_request: "yes"
+ xdebug_discover_client_host: 1
```

`roles/xdebug/templates/xdebug.ini.j2`

```diff
- xdebug.remote_enable={{ xdebug_remote_enable }}
- xdebug.remote_connect_back={{ xdebug_remote_connect_back }}
- xdebug.remote_autostart={{ xdebug_remote_autostart }}
+ xdebug.mode={{ xdebug_mode }}
+ xdebug.start_with_request={{ xdebug_start_with_request }}
+ xdebug.discover_client_host={{ xdebug_discover_client_host }}
```

And also xdebug changes the default port which it connects to, so for example if you're using the VSCode xdebug extension you also need to update your debug config:

`.vscode/launch.json`

```diff
    {
      "name": "Xdebug",
      "type": "php",
      "request": "launch",
-      "port": 9000,
+      "port": 9003,
      "pathMappings": {
        "/srv/www/www.example.com/current": "${workspaceRoot}"
      }
    }
```

**Comment by swalkinshaw** [comment]
@adambrgmn would you be up for doing a PR for the upgrade changes?

**Comment by adambrgmn** [comment]
> @adambrgmn would you be up for doing a PR for the upgrade changes?

@swalkinshaw absolutely! I can take a stab at it once the holidays are over ☺️
