### ISSUE TITLE
Upgrade WP-CLI?

### ISSUE THREAD

**Issue by mAAdhaTTah** [roots/trellis#126]
I think the problem here is with the hosted box, not bedrock ansible, which comes with WP-CLI 0.15.0 installed by default. [0.18.0](http://wp-cli.org/blog/version-0.18.0.html) has `wp cli update`, which means you wouldn't have to keep it updated on the box going forward, as users can update it themselves (or we can run it during provision). Can the box be updated?

**Comment by swalkinshaw** [comment]
It's outdated in many other ways as well :( I'll work on getting it updated soon and this will be part of it.

**Comment by austinpray** [comment]
I thought WP CLI was installed when ansible runs? Why is it included in the box?

**Comment by mAAdhaTTah** [comment]
Faster provisioning, I think? There's a couple things included by default in the box.

**Comment by swalkinshaw** [comment]
Not valid anymore. See https://github.com/roots/trellis/pull/260.
