### ISSUE TITLE
No tag for v1.7.1

### ISSUE THREAD

**Issue by andronocean** [roots/trellis#1272]
Can we get a new release tag for Trellis? The last tag was v1.7.0 in November, but the changelog has moved along a good bit.

I try to pull my upgrades from tagged versions, since it makes it much easier to keep tabs on changes.

**Comment by andronocean** [comment]
Can you please reopen this @swalkinshaw? Bug or feature issue template didn't really fit...

**Comment by swalkinshaw** [comment]
Yeah I'll tag it this weekend

**Comment by swalkinshaw** [comment]
🤦 I misread this at first and didn't even realize I forgot to tag/release 1.7.1 😬 sorry about that

https://github.com/roots/trellis/releases/tag/v1.7.1
