### ISSUE TITLE
Is PHP 8 support right around the corner?

### ISSUE THREAD

**Issue by vesper8** [roots/trellis#1281]
I notice that PHP 7.4 support was added in early April last year so is it safe to assume we can expect a similar release for PHP 8 in the coming weeks? I ask because I need PHP 8 support for a new project but it's not urgent and I can put it off for a few more weeks and of course I'd love to use Trellis to provision/manage my server as usual.

Many thanks!

**Comment by TangRufus** [comment]
Can you give https://github.com/roots/trellis/pull/1284 a try, @vesper8 ?

**Comment by swalkinshaw** [comment]
Closed by #1284
