### ISSUE TITLE
wp-cli install (signature check) stuck in case of incorrect download

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#1295]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

When a wp cli phar file was downloaded (to `/tmp`) that doesn't match the signature file, e.g. a failed/corrupted download or using a development phar, the ansible task for installing wp-cli fails at the signature verification step.
It can only be manually fixed by renaming/removing the non-matching wp-cli phar file.

## Steps to reproduce

1.. Simulate an incorrect wp cli phar in `/tmp` (e.g. download the nightly build phar).
2. Apply the trellis playbook.
Notice that the playbook run fails now as the wp cli phar doesn't match the signature file.
3. After manually renaming/removing the `/tmp/wp-cli-*.phar` and/or cleaning up the signature file `/tmp/wp-cli-*.phar.asc`, 
the playbook is applied and the specific WP CLI release is installed successfully.

**Expected behavior:** `ansible-playbook` applies correctly, installing the specified WP CLI release.

**Actual behavior:** `ansible-playbook` fails to apply in specific instances where the wp cli phar file is corrupted/changed/nightly.

**Reproduces how often:** When this issue happened, the issue reproduces until the wp cli phar file is renamed/cleaned up.

## Versions
`Fix #1284 - Update logrotate postrotate Nginx command (#1293)`

**Comment by TangRufus** [comment]
#1296 looks good. 

Alternatively, we can `force` the two `get_url` tasks.
See: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html#parameter-force

**Comment by strarsis** [comment]
This is a nice way to recover from this issue.
