### ISSUE TITLE
"Something may be wrong with WordPress.org or this server’s configuration" warning

### ISSUE THREAD

**Issue by austinpray** [roots/trellis#13]
I am getting: 

```
Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /srv/www/test.dev/current/web/wp/wp-includes/update.php on line 287
```

After simply following the instructions exactly from the readme. Everything works amazing except I just get this warning at the top constantly. 

Steps to reproduce: follow exactly the instructions in the readme with install a fresh copy of wordpress with the default theme.

**Comment by carbontwelve** [comment]
Thanks for this, really helps.

**Comment by panchalmukundak** [comment]
I tried everything as mentioned on this post, but nothing has effected into my WordPress fresh installation. Its still showing `An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the [support forums](https://wordpress.org/support/).`

**Comment by Serumo** [comment]
Hello Mr. swalkinshaw  Please Help me. 
I have a problem when installed theme woodpress. This is the error message : 


Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in C:\xampp\htdocs\serumpun media\wp-includes\update.php on line 130

Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in C:\xampp\htdocs\serumpun media\wp-includes\update.php on line 320

Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in C:\xampp\htdocs\serumpun media\wp-includes\update.php on line 500
