### ISSUE TITLE
Support for M1 mac through docker images

### ISSUE THREAD

**Issue by Digital-Nomad** [roots/trellis#1302]
Can we get support for m1 macs through docker? It looks like virtualbox and even vmware are dragging their feet on support the macs and some people got vagrant working on docker:
https://dev.to/taybenlor/running-vagrant-on-an-m1-apple-silicon-using-docker-3fh4

It would be great if we could flip a flag and spin up a docker image instead of a virtualbox machine, not sure how hard this would be in practice though.

**Comment by TangRufus** [comment]
Continue on https://github.com/roots/trellis/issues/1253
