### ISSUE TITLE
Bug: Docs are broken

### ISSUE THREAD

**Issue by pdebruic** [roots/trellis#1305]
### 

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [Trellis docs](https://roots.io/docs/trellis/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

The trellis docs site gives a 404 error.  Search is also broken

#### What have you tried?
going to the docs via google search and also clicking the links on the home page

#### What insights have you gained?
There probably aren't tests covering this.

#### Possible solutions
Umm.  
#### Temporary workarounds
Use the wayback machine

### Steps To Reproduce

1. Go to roots.io
1. Click the "Docs" link in the top nav
1.

### Expected Behavior

See the docs

### Actual Behavior

Not Found is shown instead of the docs

### Trellis Version

NA

### Ansible Version

```shell
NA
```

**Comment by QWp6t** [comment]
Thanks for bringing this to our attention. We're looking into it.

In the meantime if you need searchable docs, you can check out the [docs repo](https://github.com/roots/docs/tree/docs/docs/trellis/master).

**Comment by swalkinshaw** [comment]
Fixed 🚀 thanks
