### ISSUE TITLE
Feature Request: Add `null` or blank password support to composer HTTP basic authentication

### ISSUE THREAD

**Issue by TangRufus** [roots/trellis#1306]
### 

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

Add `null` or blank password support to composer HTTP basic authentication

#### Why are we doing this? What use cases does it support?

There are composer repositories using `null` or blank passwords, e.g: https://wpmudev.com/docs/getting-started/download-wpmu-dev-plugins-themes/#installing-wpmu-dev-plugins-via-composer

#### What is the expected outcome?

Generating `auth.json` like:

```json
{
    "http-basic": {
        "null.example.com": {
            "username": "me",
            "password": null
        },
        "blank.example.com": {
            "username": "you",
            "password": ""
        }

    }
}
```

#### Potential conflicts / foreseeable issues

Backward compatibility for `packagist_token` will break.

https://github.com/roots/trellis/blob/b6fde51906a5a8a6fad2860a8db585c7a0c4ae1a/group_vars/all/helpers.yml#L24-L25

https://github.com/roots/trellis/blob/b6fde51906a5a8a6fad2860a8db585c7a0c4ae1a/roles/wordpress-install/tasks/composer-authentications.yml#L9-L12

https://github.com/roots/trellis/pull/1091#issuecomment-504694388

### Additional Context

Props to @tomektomczuk reported this issue at https://github.com/roots/trellis/pull/1091#issuecomment-894608739

**Comment by swalkinshaw** [comment]
@tomektomczuk could you let me know if an `auth.json` file with this contents works for you?

Just update the `username` to be correct please.

```json
{
    "http-basic": {
        "wpmudev.com": {
            "username": "myuser",
            "password": ""
        }
    }
}
```

I want to know if `""` will work for the password or not.

**Comment by swalkinshaw** [comment]
Still need to validate this will actually work on repos like wpmu, but it makes sense: https://github.com/roots/trellis/pull/1408

If `auth.json` actually needs `password: null`, I don't think Trellis can ever support it?

**Comment by TangRufus** [comment]
From https://github.com/composer/composer/blob/03e4d1926661dcd3acad021bf67cffc71523886c/src/Composer/Util/AuthHelper.php#L267-L269, `"password": null` and `"password": ""` result in the same authorization header.

Thus, no need to worry about `null`.

**Comment by swalkinshaw** [comment]
Turns out we've supported this all along and there's no fixed needed 😅 

This will work:

```yaml
composer_authentications:
  - { hostname: example.com, username: user, password: "''" }
```

Trellis will rightfully skip `""` because this would result in the `composer` command not being valid (it requires a second CLI arg, which is the password).

`"''"` will result in `"password": ""` in `auth.json` which is what we want 🎉

**Comment by swalkinshaw** [comment]
Docs update: https://github.com/roots/docs/pull/416

**Comment by TangRufus** [comment]
It makes me wonder whether we should `{{ xxx | quote }}` the variables.
Use case: A password with whitespaces.

[shell_module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html) and  [command_module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html) docs recommand always use the quote filter to avoid injection issues. But, I couldn't see anything about quoting on [composer_module](https://docs.ansible.com/ansible/latest/collections/community/general/composer_module.html)

**Comment by swalkinshaw** [comment]
TIL about `quote`!

Here's another attempt which is an improvement: https://github.com/roots/trellis/pull/1412
