### ISSUE TITLE
Enhancement: Do we want to manage journalctl --disk-usage

### ISSUE THREAD

**Issue by MikeiLL** [roots/trellis#1307]
### 

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [Trellis docs](https://roots.io/docs/trellis/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

On a year-old (ish) DO droplet, the `journalctl` logs are taking up 1.5Gig of space.

#### What have you tried?

Not much, yet.

#### What insights have you gained?

It looks like you can [set a SystemMaxUse in your systemd configuration file](https://unix.stackexchange.com/a/130802/68860).

#### Possible solutions

It doesn't look like Trellis includes systemd configs. Wondering if this would be a useful feature to include.

### Steps To Reproduce

1. Run `journalctl --disk-usage` on server and see:
  Archived and active journals take up 1.4G in the file system.

### Expected Behavior

I would expect the default journal space to be smaller.

### Actual Behavior

The reason I'm looking is that the server is operating very slowly. I imagine the size of the journal logs aren't the cause, but though it was worth bringing up anyway. To solve my current problem, I'm going to look for other memory issues, try restarting nginx and adjusting [buffer count and size](https://discourse.roots.io/t/110-connection-timed-out/4321/6). 

### Trellis Version

Officially support Ubuntu 20.04 (and default Vagrant to it) ([#1197]

### Ansible Version

```shell
2.10.6
```

### Trellis CLI Version

canary

**Comment by swalkinshaw** [comment]
Sorry for the delay on this. 

Yeah I think it would be nice to set a better default. 500MB would be a good starting point.

Is this something you'd want to contribute?
