### ISSUE TITLE
Feature Request: Add variable to use default branch.

### ISSUE THREAD

**Issue by hemangajmera** [roots/trellis#1312]
### 

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

Currently if branch is not defined, `master` is used as default branch for all the sites. This can be made configurable as now-a-days `main` is the default branch instead of master. We can easily add this at all sites, but it might be good to have it in variable outside.

#### Why are we doing this?
May be in future the default for trellis itself can change from `master` to `main`. This will helpful

#### What use cases does it support?
One can use `main` as default branch instead of `master`

#### What is the expected outcome?
Default branch is configurable.

#### Potential conflicts / foreseeable issues
None

### Additional Context

https://www.thehindubusinessline.com/info-tech/microsoft-google-to-replace-coding-terms-such-as-masterslave-amid-black-live-matters-movement/article31831832.ece

**Comment by swalkinshaw** [comment]
The branch can be customized through the `branch` variable already. It's used here: https://github.com/roots/trellis/blob/17430191bb7211545eb63ba3ba989ee95c262c5f/roles/deploy/defaults/main.yml#L5

https://github.com/roots/trellis/pull/1204

That should satisfy this feature request unless I'm missing something.

**Comment by hemangajmera** [comment]
@swalkinshaw Thanks. was expecting `default_branch`. But this should also server the purpose.
