### ISSUE TITLE
Bug: (Cannot provision) The repository does not have a Release file.

### ISSUE THREAD

**Issue by jan-muller** [roots/trellis#1321]
### 

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [Trellis docs](https://roots.io/docs/trellis/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
I'm trying to provision a new server (Ubuntu 20.04) and getting the following error:

```
TASK [mariadb : Add MariaDB PPA] ***********************************************
System info:
  Ansible 2.10.15; Darwin
  Trellis 1.8.0: February 12th, 2021
---------------------------------------------------
Failed to update apt cache: E:The repository
'http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.5/ubuntu focal Release'
does not have a Release file.
fatal: [64.225.70.109]: FAILED! => {"changed": false}
```
![image](https://user-images.githubusercontent.com/11882893/141279698-7633b567-fec7-4af3-b745-7d947caa15e6.png)

#### What have I tried?
- I saw a commit from @swalkinshaw from 30th of October (https://github.com/roots/trellis/commit/32b1b6fcec8cb9fe14c6ec43cc1fccd3851fac2f)
I tried to remove `[arch=amd64]` in `/roles/mariadb/defaults/main.yml` and `roles/nginx/defaults/main.yml`

- Tried to provision with `trellis provision staging` and with `ansible-playbook server.yml -e env=staging`
- Tried to provision a completely new droplet.
- Tried it on a new droplet with Ubuntu 18.04
- Tried it on a new droplet with Ubuntu 20.04

### Steps To Reproduce

1. Just try to provision a fresh new server.

### Expected Behavior

Provision the server.

### Actual Behavior

Fatal error

### Relevant Log Output

See description

### Trellis Version

1.8.0

### Ansible Version

```shell
ansible 2.10.7
  config file = **PATH_TO_PROJECT**/trellis/ansible.cfg
  configured module search path = ['/Users/**USERNAME**/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/3.2.0/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.4 (default, Apr  5 2021, 01:50:46) [Clang 12.0.0 (clang-1200.0.32.29)]
```

### Trellis CLI Version

1.0.0

**Comment by jan-muller** [comment]
Maybe relates to https://discourse.roots.io/t/mariadb-repo-path/19411/2. But his solution did not work for me.

**Comment by swalkinshaw** [comment]
Fixed in https://github.com/roots/trellis/pull/1320

The Digitalocean mirror is still broken

**Comment by jakobmeusburger** [comment]
I get the same error with the most recent version of trellis (1.14.0): `Failed to update apt cache: E:The repository
'http://mirrors.gigenet.com/mariadb/repo/10.5/ubuntu focal Release' does not
have a Release file.
fatal: [default]: FAILED! => {"changed": false}`. It seems that the gigenet mirror is broken.

As a workaround I replaced the value of `mariadb_ppa` in _trellis/roles/mariadb/defaults/main.yml_ with `deb http://mariadb.mirror.globo.tech/repo/10.5/ubuntu {{ ansible_distribution_release }} main`. 

Could you please update the mirror to a working one?

**Comment by retlehs** [comment]
@jakobmeusburger would you mind submitting a PR?

**Comment by jakobmeusburger** [comment]
> @jakobmeusburger would you mind submitting a PR?

done: #1384
