### ISSUE TITLE
Split group_vars/ENVIRONMENT into smaller files

### ISSUE THREAD

**Issue by nathanielks** [roots/trellis#133]
Hey all-

Was reading up on group variables and realized they can be split into smaller files. Feast your eyeballs: http://docs.ansible.com/intro_inventory.html#splitting-out-host-and-group-specific-data. 

This would be great in the context of wanting to separate things out for security concerns as we could set the project up to more easily be used by ansible-vault. Just a thought!

**Comment by swalkinshaw** [comment]
Any proposals for new files?

**Comment by austinpray** [comment]
@swalkinshaw prs accepted

**Comment by nathanielks** [comment]
@austinpray LOL.

@swalkinshaw I've been thinking about this and have a few different ideas. First would be the simplest, have a `main.yml` and an `encrypted.yml`. Store everything you don't mind in plaintext in main, everything that needs to be secure in encrypted ( could solve our nginx ssl storage issue? ). Second would be scope it based on roles. If a role doesn't need vars overridden, don't add another file. Examples below.

First:
```
group_vars/development/main.yml
group_vars/development/encrypted.yml
```

Second:
```
group_vars/development/wordpress-sites.yml
group_vars/development/php.yml
group_vars/development/nginx.yml
```

**Comment by swalkinshaw** [comment]
We'll revisit this once the deploys PR and some cleanup is done. Roles/playbooks are changing due to deploys anyway but I think it makes sense to have the vars split up more.
