### ISSUE TITLE
Bug: The new "Disallow Indexing" plugin does not show up.

### ISSUE THREAD

**Issue by nextgenthemes** [roots/trellis#1357]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

I guess this spans across Trellis and Bedrock, I recently updated both and both contain chainges that supposedly should show up this plugins in "active" or in "mu-plugins"? With a *

Foremost, I have to disagree with the inclusion of your "allow normal plugins to be loaded at mu-plugins" thing in default setup. I get that it's a cool project for people who like to build sites with normal plugins as mu-plugins but for this purpose it's just bloat. I think it should be optional and not use by default and not for this trivial plugin of a few lines that is the perfect candidate for a good old single php file mu-plugin. I know I can just move it to the mu-plugins root and remove the bedrock-autoloader from composer.json and be done with it, but I just wanted to let you know I do not see it working.

#### What have you tried?

Tried locally and on staging server, nothing.

#### What insights have you gained?

autoload happens  in wp-config
vendor/roots/bedrock-autoloader is there
mu-plugins/bedrock-disallow-indexing is there

Plugin does not show up in plugins
New message not appears, I guess the plugin does not get loaded.

### Steps To Reproduce

Merged in new changes

### Expected Behavior

Plugins to show up in "mu" or "active"

### Actual Behavior

Do not find any plugin with *

### Versions

Bedrock 1.18.1, Trellis 1.18.1

**Comment by swalkinshaw** [comment]
Do you mind opening this on the bedrock repo please? It's entirely related to Bedrock and not at all Trellis
