### ISSUE TITLE
Bug: `'fail2ban_filters' is not a directory`

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#1389]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Ansible warning during Trellis provision of existing Trellis installation:
````
TASK [fail2ban : build list of fail2ban filter templates] **********************
[WARNING]: Skipped 'fail2ban_filters' path due to this access issue:
'fail2ban_filters' is not a directory
````

#### What have you tried?
Re-provisioned the Trellis server multiple times.

#### What insights have you gained?
Despite multiple re-provisions the warning persists.

#### Possible solutions
A directory is missing? Or this warning can be safely ignored? Though then the task that causes the warning should be conditionally handled to avoid the warning at each provisioning run.

#### Temporary workarounds
Ignoring the warning for now.

### Steps To Reproduce

1. Use an older version of Trellis (2 months ago).
2. Provision a server with it.
3. Update to the latest version of Trellis (now).
4. Re-provision the server with it.
Notice the warning.

### Expected Behavior

No warnings.

### Actual Behavior

Warning at each provision:
````
TASK [fail2ban : build list of fail2ban filter templates] **********************
[WARNING]: Skipped 'fail2ban_filters' path due to this access issue:
'fail2ban_filters' is not a directory
````

### Relevant Log Output

```shell
TASK [fail2ban : build list of fail2ban filter templates] **********************
[WARNING]: Skipped 'fail2ban_filters' path due to this access issue:
'fail2ban_filters' is not a directory
```

### Versions

Add built-in fail2ban filters (#1375)

**Comment by swalkinshaw** [comment]
> A directory is missing? Or this warning can be safely ignored? Though then the task that causes the warning should be conditionally handled to avoid the warning at each provisioning run.

Yeah that's all correct. Ansible produces the warning but just ignores that missing path so everything works as expected.

There's no built-in way to handle/ignore this warning afaik. Unfortunately I think the only solution is to add a task to check if the path exists or not first 🤔
