### ISSUE TITLE
Bug: `galaxy.yml` is non-standard and breaks `ansible-lint`

### ISSUE THREAD

**Issue by codepuncher** [roots/trellis#1401]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Using `ansible-lint` on Trellis doesn't work.

#### What have you tried?
1. Reporting a bug to [`ansible-lint`](https://github.com/ansible/ansible-lint/issues/2228)
2. Renaming `galaxy.yml` -> `requirements.yml` and fixing syntax issues

#### What insights have you gained?
I believe the decision to rename `requirements.yml` to `galaxy.yml` was not the best move; `galaxy.yml` seems to be reserved for defining project meta data and also **collections** which Trellis is not

#### Possible solutions
Revert the rename and fix syntax

Before:

```yml
# galaxy.yml
- name: composer
  src: geerlingguy.composer
  version: 1.9.0
  # More roles
```

After:

```yml
# requirements.yml
---
roles:
  - name: composer
    src: geerlingguy.composer
    version: 1.9.0
  # More roles
```

#### Temporary workarounds
As above

### Steps To Reproduce

1. `pip3 install ansible-lint`
2. `cd path/to/trellis`
3. `ansible-lint`

### Expected Behavior

To lint the project correctly without error

### Actual Behavior

It doesn't lint and throws a Python error

### Relevant Log Output

```shell
Traceback (most recent call last):
  File "/home/lee/.local/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/home/lee/.local/lib/python3.10/site-packages/ansiblelint/__main__.py", line 252, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/home/lee/.local/lib/python3.10/site-packages/ansiblelint/__main__.py", line 165, in main
    app = get_app(offline=options.offline)
  File "/home/lee/.local/lib/python3.10/site-packages/ansiblelint/app.py", line 252, in get_app
    _perform_mockings()
  File "/home/lee/.local/lib/python3.10/site-packages/ansiblelint/_mockings.py", line 77, in _perform_mockings
    namespace = yaml.get("namespace", None)
AttributeError: 'list' object has no attribute 'get'
```

### Versions

e497cfe002fa00fc33447131c0eb2570634453af

**Comment by codepuncher** [comment]
On second thought, simply fixing the syntax of the file should suffice to solve the linting issue.

**Comment by swalkinshaw** [comment]
Following up from https://github.com/roots/trellis/pull/1402, I'm inclined to only update the format of `galaxy.yml` to the new one for a few reasons:

1. the yml file can be named anything and its `ansible-lint`s limitation for hardcoding it and not supporting another name
2. Trellis itself doesn't even use `ansible-lint` anymore
3. you can configure it to skip that file with `--exclude galaxy.yml`

**Comment by codepuncher** [comment]
PR updated.
