### ISSUE TITLE
Setup Renovate to automatically bump Ansible Galaxy roles

### ISSUE THREAD

**Issue by retlehs** [roots/trellis#1423]
We've been using Renovate instead of Dependabot for other projects recently. Renovate happens to also provide support for Ansible Galaxy:

https://docs.renovatebot.com/modules/manager/ansible-galaxy/

Let's try adding Renovate to automatically bump these dependencies whenever possible

**Comment by swalkinshaw** [comment]
Not sure if it's working or not https://github.com/roots/trellis/blob/master/.github/renovate.json
