### ISSUE TITLE
Feature Request: Support Ubuntu 22 deployments

### ISSUE THREAD

**Issue by acalvino4** [roots/trellis#1425]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

Currently when trying to provision trellis on an Ubuntu server, we get the following in the output:
```
TASK [sshd : Create a secure sshd_config] **************************************
System info:
  Ansible 2.13.4; Linux
  Trellis 1.16.0: July 18th, 2022
---------------------------------------------------
failed to validate
/home/ubuntu/.ansible/tmp/ansible-
tmp-1663358076.488673-13634-196017568872396/source line 9: no argument after
keyword "AcceptEnv"
/home/ubuntu/.ansible/tmp/ansible-
tmp-1663358076.488673-13634-196017568872396/source: terminating, 1 bad
configuration options
fatal: [localhost]: FAILED! => {"changed": false, "checksum": "ebb534a0a55caff91cde2c9129f07ad81c5e0c3a", "exit_status": 255, "stderr_lines": ["/home/ubuntu/.ansible/tmp/ansible-tmp-1663358076.488673-13634-196017568872396/source line 9: no argument after keyword \"AcceptEnv\"", "/home/ubuntu/.ansible/tmp/ansible-tmp-1663358076.488673-13634-196017568872396/source: terminating, 1 bad configuration options"], "stdout": "", "stdout_lines": []}
```
[This discourse](https://discourse.roots.io/t/error-on-task-sshd-create-a-secure-sshd-config/23597) identifies the issue as something to do with Ubuntu 22.

In general, I would think it the goal to support the latest Ubuntu LTS. Currently that is Ubuntu 22, hence the feature request.

#### Why are we doing this?
Best practice is generally to run the latest LTS. This feature would enable it being possible.

#### What use cases does it support?
Running Trellis on Ubuntu 22.

**Comment by swalkinshaw** [comment]
Agreed we should support it! https://github.com/roots/trellis/issues/1392 already exists so let's keep that issue as the main one.
