### ISSUE TITLE
Bug: uploads subfolders ownership

### ISSUE THREAD

**Issue by LucasDemea** [roots/trellis#1446]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
In a very specific use case (installing a fresh wp instance in a circleCI environment), I run the wordpress-install role.
WP is installed with the `--allow-root` flag, which leads to the creation of a empty subfolder in `uploads`, corresponding to the current month (eg: `uploads/2022/11`). This folder is owned by root because of the `--allow-root` flag.

In my use case I want to do some changes in this folder afterwards, being the default user (`circleci`), and I can't because the folder is owned by `root`.

#### What have you tried?
Running the role again, with  `--tags=wordpress-install-directories` flag enabled, solves the issue. The `uploads/2022/11` is then owned by the default user.

#### Possible solutions
In the wordpress-install role, we could run `- import_tasks: directories.yml` after the `wp core install` part. This would prevent such issues.

### Steps To Reproduce

Run the wordpress-install role in another environment than the development VM.

### Expected Behavior

Wordpress files and folder are owned by the default user.

### Actual Behavior

uploads subfolders are owned by root.

### Versions

trellis 1.9.1

**Comment by swalkinshaw** [comment]
I think just setting `become: no` to the "Install WP" task might fix it as well if you want to try it. Because then root won't be used.

> In the wordpress-install role, we could run - import_tasks: directories.yml after the wp core install part. This would prevent such issues.

If not, I'd be open to this fix as well.
