### ISSUE TITLE
cron missing

### ISSUE THREAD

**Issue by LucasDemea** [roots/trellis#1498]
### Version

1.21.0

### What did you expect to happen?

Trellis checks that cron is installed

### What actually happens?

On some systems (a CI env in my case), cron could be missing by default, causing `wordpress-setup` job to fail on S`etup WP system cron` task.

### Steps to reproduce

Provision a server.

### Please confirm this isn't a support request.

Yes

**Comment by swalkinshaw** [comment]
> On some systems (a CI env in my case),

Any more details on this system? Trellis requires Ubuntu which should always come with cron.

**Comment by LucasDemea** [comment]
This happens with a custom docker image based on [cimg/php:8.1.21-browsers](https://circleci.com/developer/images/image/cimg/php). Cron was not missing in the `8.1.9` version.

**Comment by LucasDemea** [comment]
`docker run -it ubuntu:22.04 crontab`
=>
`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "crontab": executable file not found in $PATH: unknown.`

**Comment by strarsis** [comment]
+1, I encountered the same issue with a minimal Ubuntu 22.04 LTS install.
Manually installing the `cron` package fixed the issue.

However, the current Ubuntu 22.04 LTS minimal installation does not contain `cron`, so for 
Trellis supporting the default Ubuntu 22.04 LTS minimal install, Trellis should also ensure that the `cron` package is being present?
There are golden images for Ubuntu 22.04 LTS minimal that also contain `cron`, but these being custom additions by the image creator/cloud provider. And there were images for Ubuntu LTS minimal in the past that contained additional services that actually interfered with the Trellis setup. IMHO only the default Ubuntu minimal system should be considered authoritative.
And just ensuring the presence of the `cron` package should not interfere with systems with `cron` already installed.

**Comment by swalkinshaw** [comment]
@strarsis was `cron` the only other package missing when using the minimal version?

**Comment by strarsis** [comment]
@swalkinshaw: Yes, after having manually installed `cron` the provisioning worked fine.

**Comment by swalkinshaw** [comment]
Seems reasonable to add then in that case 👍

**Comment by strarsis** [comment]
On first glance, it should be sufficient to add `cron` to [`apt_packages_default`](https://github.com/roots/trellis/blob/ef2de218d5cd6fc2a8a57f8eedff8df5f96331ea/roles/common/defaults/main.yml#L23)?

**Comment by swalkinshaw** [comment]
Yep that should be it 👍

**Comment by strarsis** [comment]
@swalkinshaw: https://github.com/roots/trellis/pull/1506

**Comment by strarsis** [comment]
IMHO, as the PR is now merged, this issue can be closed.

**Comment by strarsis** [comment]
(This other PR is now redundant: https://github.com/roots/trellis/pull/1499)
