### ISSUE TITLE
PHP `8`: Enable `JIT` (`PHP` `INI` option)

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#1504]
### Summary

PHP `8` comes with `JIT` optimization, but it is disabled by default. For enabling `JIT`, the `opcache.jit_buffer_size` option has to be set to some value (e.g. `256M`).
Also `opcache.jit` in `/etc/php/8.1/fpm/conf.d/10-opcache.ini` must be set from `off` (apparently an Ubuntu 22.04 LTS default) to `tracing` (the PHP default, enables JIT).

Apparently there is no option yet for setting these options in Trellis/Ansible, it may be a good addition.

### Additional context

https://stitcher.io/blog/php-8-jit-setup
https://medium.com/@edouard.courty/make-your-php-8-apps-twice-as-fast-opcache-jit-8d3542276595

**Comment by swalkinshaw** [comment]
This would be great 🚀 . Do you want to contribute the addition @strarsis ?

**Comment by strarsis** [comment]
@swalkinshaw: Sure! I prepare a PR for this.

**Comment by strarsis** [comment]
@swalkinshaw: https://github.com/roots/trellis/pull/1505

**Comment by swalkinshaw** [comment]
closed by https://github.com/roots/trellis/pull/1505
