### ISSUE TITLE
MariaDB 10.6.18 release requires action

### ISSUE THREAD

**Issue by nikitasol** [roots/trellis#1517]
### Version

1.22.0

### What did you expect to happen?

Seamless sync between production/staging and development

### What actually happens?

MariaDB 10.6.18 adds sandbox comman as per [release notes](https://mariadb.com/kb/en/mariadb-10-6-18-release-notes/) and the new line at the top of the db export breaks syncing.

### Steps to reproduce

Just re-provision production/staging so the new MariaDB is installed there and then try exporting/importing db either through the amazing sync.sh or manually.

The line which is added is this:

`/*!999999\- enable the sandbox mode */`

### Please confirm this isn't a support request.

No

**Comment by retlehs** [comment]
MariaDB breaking database dumps in a patch release is wild 😞 

Other relevant discussions/issues:

https://github.com/ddev/ddev/issues/6249
https://github.com/wp-cli/db-command/issues/254

**Comment by nikitasol** [comment]
Just to add a few possible solutions:

- if you use sync.sh (or some other shell script) add `tail -n +2` in between db export and db import so that the script may eliminate the first line (tested and works)
- update vm to latest mariadb version (haven't tested yet, but should work)

**Comment by nikitasol** [comment]
And to confirm that rebuilding vm with updated MariaDB also works too.

**Comment by strarsis** [comment]
For my local development (Docker-based) setup I had to use `curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | bash -s -- --mariadb-server-version="mariadb-11.2"` and installed the `mariadb-client` package as a drop-in for `mysql-client`. The `11.2` version is much newer and has the issue fixed.

**Comment by retlehs** [comment]
If you're a sync script user landing on this issue, take a look at this solution from @joshuafredrickson:

https://discourse.roots.io/t/sync-script-fix-for-error-at-line-1-unknown-command/27734

We've also upgraded MariaDB in Trellis (https://github.com/roots/trellis/pull/1520) which will be in the next release
