### ISSUE TITLE
Split out deploy role

### ISSUE THREAD

**Issue by swalkinshaw** [roots/trellis#157]
Now that #95 has been merged in, I realized that it makes sense to split that role out into it's own project and it can be added to Ansible Galaxy.

With the intention of removing the Capistrano configs from Bedrock, we'll be documenting and recommending using this project for deploys. However there will be a good amount of people that only want deploys, and not the whole project meant for provisioning.

It will also make our job easier to document using the deploy role only with Bedrock without having to explain the entire project.

/cc @retlehs @fullyint 

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)

**Comment by callerc1** [comment]
@swalkinshaw That would be cool. Especially helpful when working with a CI tool that automates deploys or even working on other projects etc.

**Comment by strarsis** [comment]
This also would help dockerizing Trellis as a whole, ansible can be used for provisioning docker images, too.

**Comment by swalkinshaw** [comment]
Closing old/stale issues
