### ISSUE TITLE
add http://rkhunter.sourceforge.net/ package

### ISSUE THREAD

**Issue by rstormsf** [roots/trellis#182]
I saw from
https://github.com/al3x/sovereign/blob/3ff928c7624a39b56e3ad9bc5d15eda2cfbeff9b/roles/common/tasks/security.yml

the package - rkhunter

monit could be also useful and some backup role as well

**Comment by swalkinshaw** [comment]
Finally remembered to look into rkhunter. It's interesting but not something I'm comfortable having in Trellis by default. It needs to be run on a schedule and constantly updated. Just like antivirus software it also wouldn't catch the latest root kits. Thanks for bringing it to our attention though.
