### ISSUE TITLE
Rename project to Trellis

### ISSUE THREAD

**Issue by retlehs** [roots/trellis#220]
We're giving this project a proper name thanks to @Foxaii: 

### Trellis

I'll be working on creating the appropriate pages along with documentation on https://roots.io/. Project logo is in the works!

This repo will be renamed — GitHub redirects everything so we shouldn't have any issues.

**Comment by kalenjohnson** [comment]
![Mother of God]
(http://i.imgur.com/3o396JZ.jpg)

**Comment by mAAdhaTTah** [comment]
Oh awesome. Can't say I was ever a huge fan of the name "bedrock-ansible"

**Comment by retlehs** [comment]
![image](https://cloud.githubusercontent.com/assets/115911/7773259/e3ef154a-0068-11e5-8d2f-af49d1248711.png)

**Comment by MikeiLL** [comment]
Nice!

**Comment by mAAdhaTTah** [comment]
:+1:

**Comment by evanfuture** [comment]
Yeah!  Works well!  Will we be seeing that in the roots.io menu bar soon?

**Comment by retlehs** [comment]
:rocket:

**Comment by ptibbetts** [comment]
Just a heads up, the Discourse menu bar also needs updating

**Comment by c2itllc** [comment]
Thanks for the note @ptibbetts, I got that added in there on Discourse.
