### ISSUE TITLE
TASK: [deploy | Copy project folders] creates duplicates

### ISSUE THREAD

**Issue by metaarts** [roots/trellis#226]
During the Deploy process for remote servers (mentioned below) the source folder is copied to the destination folder on the selfsame location. This produced every time a duplicate.

```
- name: Copy project folders
  command: cp -rp {{ deploy_helper.current_path }}/{{ item.item }} {{ deploy_helper.new_release_path }}/{{ item.item }}
  with_items: project_folder_paths.results
  when: item.stat.exists == True
```

**Comment by swalkinshaw** [comment]
Those are actually different paths:

`cp -rp {{ deploy_helper.current_path }}/{{ item.item }} {{ deploy_helper.new_release_path }}/{{ item.item }}`

Note `deploy_helper.current_path` and `deploy_helper.new_release_path`. "current" in this **during** the deploy is the last deploy. So it's coping the folders from the last/current release to the new release.

**Comment by metaarts** [comment]
In my case it's coping the folders from the current release into the existent folder to the new release.

example:
```
cp path_to_current/vendor path_to_new/vendor
```
creates `path_to_new/vender/vendor/`

**Comment by swalkinshaw** [comment]
Ah that's different. I'll look into it.

**Comment by swalkinshaw** [comment]
@metaarts I can't duplicate this. Tried deploys on a test VM and on roots.io. You're using Ubuntu 14.04 I assume?

**Comment by swalkinshaw** [comment]
Closing since there's no update

**Comment by johnvh** [comment]
I'm seeing this too. I've got lots of nested vendor directories, 1 for every deploy I've made it seems:

```
root@tw-wp-prod-web-1:/srv/www/thrivewire/current/vendor# pwd
/srv/www/thrivewire/current/vendor
root@tw-wp-prod-web-1:/srv/www/thrivewire/current/vendor# find . -iname vendor -type d
./vendor
./vendor/vendor
./vendor/vendor/vendor
./vendor/vendor/vendor/vendor
./vendor/vendor/vendor/vendor/vendor
./vendor/vendor/vendor/vendor/vendor/vendor
./vendor/vendor/vendor/vendor/vendor/vendor/vendor
./vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor
./vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor
./vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor
./vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor
./vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor
./vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor
./vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor
./vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor
./vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor/vendor
```

I copied bedrock-ansible into my project a while ago - several weeks at least - so it's possible this has since been fixed.

**Comment by louim** [comment]
you are right, I juste checked a site deployed. I have the nested `vendor` as well. I get one "nest" for each deploy, More than 75 in my case. Last commit I have from Trellis is 5f97284dff3079563f5dcd811b9f27611a627135.

**Comment by johnvh** [comment]
I'm seeing exactly what OP @metaarts saw. Here's the output from an ansible deploy with `-vvv`:

```bash
TASK: [deploy | Copy project folders] *****************************************
<111.111.111.1> ESTABLISH CONNECTION FOR USER: web
<111.111.111.1> REMOTE_MODULE command cp -rp /srv/www/thrivewire/current/vendor /srv/www/thrivewire/releases/20150710152511/vendor
```

This results in `/srv/www/thrivewire/releases/20150710152511/vendor/vendor`.

My version of `Copy project folders` step in `roles/deploy/tasks/main.yml` hasn't changed from what's in master now - https://github.com/roots/trellis/blob/8679312194dca96b3271fc1a1a886989e6bdde26/roles/deploy/tasks/main.yml

**Comment by austinpray** [comment]
Yep I'm seeing this as well with the latest roots-example-project.

**Comment by austinpray** [comment]
https://github.com/roots/trellis/pull/270 fixes it on this specific production example I am working with but have yet to test on trellis master.
