### ISSUE TITLE
Make the MySQL (MariaDB) role idempotent

### ISSUE THREAD

**Issue by louim** [roots/trellis#237]
Currently, on the Vagrant `development` environment, it is impossible to change the mysql root password, because it is already set in the base box. On `staging`and `production`, it's only possible to set the password the first time because it is not already defined. Any attempt to change it afterward will fail.

To make the playbook idempotent, the root password should be stored in the `~/my.cnf` file as recommended by Ansible: http://docs.ansible.com/mysql_user_module.html#notes

See https://github.com/geerlingguy/ansible-role-mysql/blob/master/tasks/secure-installation.yml#L2-L22 for a working implementation, although I'm not sure if all of it is needed.

**Comment by swalkinshaw** [comment]
This a known, long-standing issue as seen [here](https://github.com/roots/bedrock-ansible/issues/73#issuecomment-59358289). Basically I ran that role while creating the base box and I shouldn't have. I've been lazy and haven't updated the base box in forever but I'll put that on my list for this week.

**Comment by austinpray** [comment]
- [ ] update base box
- [ ] transfer from Austin's DO box to roots DO box

**Comment by mAAdhaTTah** [comment]
@swalkinshaw if you're updating the base box: #126

**Comment by swalkinshaw** [comment]
Not valid anymore. See https://github.com/roots/trellis/pull/260.
