### ISSUE TITLE
PHPUnit

### ISSUE THREAD

**Issue by getdave** [roots/trellis#251]
Would it be possible to provision the VM with a copy of PHPUnit? As you need to be SSH'd into the box to run WPCLI it would help with the WordPress Unit Test scaffolding.

**Comment by swalkinshaw** [comment]
Of course. It would be nice to have and should be a pretty simple role to add. Would you be interested in doing this?

**Comment by getdave** [comment]
That's great. Interested yes but not quite up to speed on Ansible. Could you outline the approach you would take so I can absorb the workflow?

**Comment by louim** [comment]
Shouldn't this just be added as a dev dependency of the project you want to run test on? I may be wrong since I never used phpunit. I would do it like this: `composer require-dev "phpunit/phpunit=4.7.*"`. What is the benefit of installing it globally?

**Comment by swalkinshaw** [comment]
:+1: to what @louim said

**Comment by austinpray** [comment]
You definitely want to install it locally. The phpunit binary should be available in /vendor/bin

**Comment by kalenjohnson** [comment]
The benefit of installing globally is not needing phpunit required in your composer.json file, although if you have tests for each project it doesn't hurt. I would also say it's much easier to type `phpunit` than `./vendor/bin/phpunit` every time :joy:

**Comment by nathanielks** [comment]
PATH could also be updated to include `./vendor/bin`.

—

**Comment by kalenjohnson** [comment]
So it'll always work where your `composer.json` file is which has phpunit installed? I suppose that's an option too

**Comment by nathanielks** [comment]
Yup! That way wherever you’re at you’re using that projects dependencies and not what’s available globally.


—

**Comment by austinpray** [comment]
>The benefit of installing globally is not needing phpunit required in your composer.json file

Right, but phpunit can have breaking changes that affect your tests. You want to lock down the version just like any other package installed via composer.

**Comment by nathanielks** [comment]
> You want to lock down the version just like any other package installed via composer.

This.

**Comment by mAAdhaTTah** [comment]
> PATH could also be updated to include `./vendor/bin`.

+1 for including this as an update. Might be a good start for someone new to Ansible (like me :) ).

**Comment by getdave** [comment]
Agree with keeping it as a local dependency and updating `PATH` to include `./vendor/bin`. Makes more sense. 

Ansible pros - what's the best method for updating `PATH`?

**Comment by louim** [comment]
@getdave it should be set globally. On Ubuntu the recommended file to set global environment variable is `/etc/environment`. More info here: https://help.ubuntu.com/community/EnvironmentVariables#System-wide_environment_variables. Be aware that it is not a script file, so you would have to print the whole path in here to append the vendor bin path. (You can't use `$PATH` in this file). 
Another alternative even if it's not suggested as the best way to do it would be to use the `/etc/bash.bashrc` which allow variable expansion.

**Comment by getdave** [comment]
Ok possible change of plan. VVV seems to install Composer globally and updating on provision. This is also how PHPUnit recommends handling installation via Composer

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision.sh#L213

**Comment by austinpray** [comment]
What does VVV have to do with anything?

**Comment by nathanielks** [comment]
@austinpray just comparing another popular project ;)

I'm with Austin though. Just because they do it doesn't mean we should. He brought up a great point earlier that composer should be managed as a project dependency just as any other composer package your project requires.

**Comment by swalkinshaw** [comment]
It is basically objectively *wrong* to use a library such as PHPUnit globally. The reason why is as everyone mentioned: it's a dependency like anything else and should be treated as such.

I'm fine with adding `vendor/bin` to `$PATH` to the `vagrant` user's `/etc/bash.bashrc`.

**Comment by getdave** [comment]
> What does VVV have to do with anything?

Just an observation. Apologies if this was inappropriate.

@swalkinshaw consider me convinced. I think perhaps it's better for you guys to handle this though.

Thanks

**Comment by nathanielks** [comment]
@getdave we welcome PR's! Why not try your hand? Good learning experience.

**Comment by mAAdhaTTah** [comment]
> I'm with Austin though. Just because they do it doesn't mean we should. He brought up a great point earlier that composer should be managed as a project dependency just as any other composer package your project requires.

Wait, composer itself should be a project dependency? Or did you mean PHPUnit?

**Comment by nathanielks** [comment]
Herp derp. I meant PHPUnit. Good catch!



—

**Comment by getdave** [comment]
@nathanielks Ok i'm working on a PR

**Comment by getdave** [comment]
Ok opened a PR at

https://github.com/roots/bedrock-ansible/pull/256

Probably not up to your standards so please feel to tell me it's rubbish or make changes. Probably won't be able to look at this again for a few days.

Cheers
