### ISSUE TITLE
Dynamic ANSIBLE_PATH breaks Windows compatibility

### ISSUE THREAD

**Issue by jchapron** [roots/trellis#262]
It seems that #257 breaks windows compatibility. I tracked down the issue to this code in windows.sh : 

```ruby
if [ ! -d /vagrant/${ANSIBLE_PATH}/vendor ]; then
  echo "Running Ansible Galaxy install"
  ansible-galaxy install -r /vagrant/${ANSIBLE_PATH}/requirements.yml -p /vagrant/${ANSIBLE_PATH}/vendor/roles
fi
```

This code used to work with ANSIBLE_PATH being "." but breaks now that it's the absolute path to the file. You get something like "/vagrant/D:/development/ansible/vendor".

I'm not sure how to fix it without just rollbacking to the old value.
Thanks

**Comment by louim** [comment]
Woops, that's my fix.

@kalenjohnson you have pioneered most of the windows compatibility, is there a reason the Ansible need to use `ANSIBLE_PATH` inside the VM?

**Comment by kalenjohnson** [comment]
Hmm... yeah, I see how that's an issue now. I unfortunately don't work in Windows so I forgot about that.

The only reason we're passing the Ansible path to the windows script is to account for the example project modified directory structure.

So, it seems to me that perhaps we should simply have a bash variable set up in `windows.sh`, which points to `/vagrant`, if the Vagrantfile is in the topmost folder with the Ansible playbooks, then fine, it works out of the box. If you are following the project example, having the playbooks in an `ansible` folder and the `Vagrantfile` in the root directory, you would have to modify the variable on `windows.sh` to point to `/vagrant/ansible`.
