### ISSUE TITLE
Ansible Requirement Script Location to Run From

### ISSUE THREAD

**Issue by jasperf** [roots/trellis#271]
I think `ansible-galaxy install -r requirements.yml` should be run inside trellis folder. So perhaps that should be specified in the documentation?

**Comment by nathanielks** [comment]
Hey @jasperf! For clarities sake, curious where you thought it would be run?

**Comment by jasperf** [comment]
Hey @nathanielks !  For people who are just getting started they would just run it in `site.com` and not `site.com/trellis` following the manual. Been using the script for a while now - and Linux  for years - so I move to the Trellis or Ansible directory. An extra clarification is nice I would say.

**Comment by fullyint** [comment]
Thanks @jasperf. Added this note to the README in [#272](https://github.com/roots/trellis/pull/272/files#diff-04c6e90faac2675aa89e2176d2eec7d8R42)
