### ISSUE TITLE
SSL: Option to generate snakeoil cert for non-production environments

### ISSUE THREAD

**Issue by austinpray** [roots/trellis#277]
## Problem

If your production environment has SSL, you should have SSL on your development and staging as well. Why? Because stuff like this will slip into production:

![screenshot 2015-07-17 11 06 58](https://cloud.githubusercontent.com/assets/2192970/8751678/2f76e556-2c74-11e5-8e18-ecddd09ba2ed.png)
![screenshot 2015-07-17 11 07 15](https://cloud.githubusercontent.com/assets/2192970/8751677/2f74a174-2c74-11e5-9c26-839715add2cb.png)

You should be catching errors like this in development not via a user submitting a ticket. You should not be deploying to staging and production crossing your fingers and hoping it works.

So why aren't you using SSL on dev? Probably because it's too much trouble.

## Solution

```diff
* `ssl` - enable SSL and set paths
  * `enabled` - `true` or `false` (required, set to `false`)
+  * `snakeoil` - `true` or `false` (default: `false`)
  * `key` - local relative path to private key
  * `cert` - local relative path to certificate
```

When `snakeoil` is set to `true` the playbooks will generate a snakeoil certificate and hand it over to nginx. 

### Alternative solutions

I understand that you could have the user generate a snakeoil cert on the host machine and just populate `key` and `cert` properties. But that doesn't make the repo very cloneable. Having to instruct everyone on the team to generate a cert in this particular way and put it in a exactly this folder with a particular name is too much trouble. Plus this probably is DOA for windoze users.

## Implementation

Could be as simple as:

```
apt-get install ssl-cert
```

And then we have this available to us:

```
SSLEngine on
SSLCertificateFile    /etc/ssl/certs/ssl-cert-snakeoil.pem
SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
```

This is what I have been doing manually, mind as well build it into a playbook.

## Snake Oil?

A "snake oil" cert might be not be the correct term, but that's the term I've always heard being used. Maybe you guys can advise me. 

## Conclusion

We need to make SSL dev by default as easy as possible because https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/ is looming. A+ SSL is a huge feature for trellis, we want to be making it as accessible as possible.

**Comment by mAAdhaTTah** [comment]
I think the term is "self-signed certificate." Otherwise, :+1:

**Comment by louim** [comment]
Plus plus one for this! As @mAAdhaTTah said, `self-signed` might be a better name.

I'm currently using this snippet, and committing the fake certs to the repo under `files/example.com/`

```
# This command will generate a new self-signed certificate and a new private key.
# Simply create a folder with the required domain name and run this command inside it.
# For example, running this command inside an "example.com" folder would create an "example.com" self-signed certificate.

openssl req -subj "/C=CA/ST=Quebec/L=Quebec/O=O2 Web/OU=DevOps/CN=${PWD##*/}" -new -newkey rsa:2048 -days 365 -nodes -x509 -sha256 -keyout ${PWD##*/}.key -out ${PWD##*/}.crt
```

Automating this with ssl-cert would be awesome. :+1:

**Comment by austinpray** [comment]
Ok let's do it with @louim's command and call it "self-signed"

**Comment by louim** [comment]
@austinpray I think going with your solution (ssl-cert) would be better. Mine is a one liner if you want to generate them yourself, but having them installed and already ready to use without committing them would be the best I think. It will allow to easily toggle on and off without additional config which is a big plus IMHO.

I would make it so that when you turn ssl on in the config bit don't pass a cert / key option, the snake-oil is used.

**Comment by louim** [comment]
I just tested it locally. It's kinda working with `ssl-cert`. Problem is that it trie to guess the domain based on the `hostname -f` command. So it's bound to errors. also it would need to be regenerated if the hostname is changed. I'll do it manually with `openssl`. PR incoming.

**Comment by austinpray** [comment]
>I would make it so that when you turn ssl on in the config bit don't pass a cert / key option, the snake-oil is used.

:+1: That would be completely badass.  

>  I'll do it manually with openssl.

Is it possible to leave out all this stuff: `/C=CA/ST=Quebec/L=Quebec/O=O2`?

**Comment by louim** [comment]
@austinpray sure ahah, I just pasted the snippet litterally like I use it, I'll make it more agnostic :smile:

**Comment by austinpray** [comment]
Great job @louim!
