### ISSUE TITLE
EACCES bug during bower install

### ISSUE THREAD

**Issue by elimc** [roots/trellis#284]
Attempting to install Trellis for the first time. I have done all the instructions perfectly, until I get the following bug while attempting a `bower install`:

```javascript
/Applications/AMPPS/www/example.com/site/web/app/themes/sage
❯ bower install
bower cached        git://github.com/twbs/bootstrap-sass.git#3.3.5
bower validate      3.3.5 against git://github.com/twbs/bootstrap-sass.git#3.3.5
bower cached        git://github.com/Modernizr/Modernizr.git#2.8.2
bower validate      2.8.2 against git://github.com/Modernizr/Modernizr.git#2.8.2
bower cached        git://github.com/jquery/jquery.git#2.1.4
bower validate      2.1.4 against git://github.com/jquery/jquery.git#>= 1.9.0
bower EACCES        EACCES, mkdir '/Applications/AMPPS/www/example.com/site/web/app/themes/sage/bower_components'

Stack trace:
Error: EACCES, mkdir '/Applications/AMPPS/www/example.com/site/web/app/themes/sage/bower_components'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.12.7
OS: Darwin 14.4.0 x64
```

I'm not entirely sure what this error means, but people might get frustrated while running into it.

**Comment by ptibbetts** [comment]
Hey @elimc ,

The team use GitHub issues for bug reporting and pull requests and the forums for support requests like this, so you're more likely to get help (in the future) by going to [the forums](https://discourse.roots.io/c/sage) first.

Having said that, this error looks like bower wasn't able to create the bower_components folder for you:

```
Error: EACCES, mkdir '/Applications/AMPPS/www/example.com/site/web/app/themes/sage/bower_components'
```
If you create it manually and rerun `bower install` it should work. 

If not, check out [this thread](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) on the forums or you could [create your own thread](https://discourse.roots.io/c/sage).

**Comment by swalkinshaw** [comment]
Trellis doesn't user Bower anywhere. Maybe this error came from following https://github.com/roots/roots-example-project.com?

If so, the `bower install` command that is run is a **local** command run on your machine. You have a permissions problem but there's nothing we can do about that unfortunately.

@ptibbetts :+1:
