### ISSUE TITLE
Non Root User on AWS Errors on Provisioning server.yml

### ISSUE THREAD

**Issue by BrandonShutter** [roots/trellis#285]
I have an Ubuntu box on AWS.  Setting `admin_user: ubuntu` in `group_vars/all` results in an error when the `Determine remote user task` runs.

Rather than Trellis trying to use `ubuntu` over `root` it errors out with ssh garbage.

Here's the output of `-vvvv`:

```
Brandons-MacBook-Pro:ansible shutter$ ansible-playbook -i hosts/production server.yml -vvvv
```

    PLAY [Determine Remote User] ************************************************** 
    
    TASK: [remote-user | Determine whether to connect as root or admin_user] ****** 
    <127.0.0.1> REMOTE_MODULE command ssh -o PasswordAuthentication=no  "echo root" || echo ubuntu #USE_SHELL
    <127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1438381915.22-77758919300933 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1438381915.22-77758919300933 && echo $HOME/.ansible/tmp/ansible-tmp-1438381915.22-77758919300933']
    <127.0.0.1> PUT /var/folders/lf/878x4xqx5q71w08fpj496mnh0000gn/T/tmpnwxIKk TO /Users/shutter/.ansible/tmp/ansible-tmp-1438381915.22-77758919300933/command
    <127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/shutter/.ansible/tmp/ansible-tmp-1438381915.22-77758919300933/command; rm -rf /Users/shutter/.ansible/tmp/ansible-tmp-1438381915.22-77758919300933/ >/dev/null 2>&1']
    ok: [52.3.121.253 -> 127.0.0.1] => {"changed": false, "cmd": "ssh -o PasswordAuthentication=no root@52.3.121.253 \"echo root\" || echo ubuntu", "delta": "0:00:11.073787", "end": "2015-07-31 18:32:06.360790", "rc": 0, "start": "2015-07-31 18:31:55.287003", "stderr": "", "stdout": "Please login as the user \"ubuntu\" rather than the user \"root\".", "stdout_lines": ["Please login as the user \"ubuntu\" rather than the user \"root\"."], "warnings": []}
    
    TASK: [remote-user | Set remote user for each host] *************************** 
    <52.3.121.253> ESTABLISH CONNECTION FOR USER: shutter
    ok: [52.3.121.253] => {"ansible_facts": {"ansible_ssh_user": "Please login as the user \"ubuntu\" rather than the user \"root\"."}}
    
    PLAY [WordPress Server - Install LEMP Stack with PHP 5.6 and MariaDB MySQL] *** 
    
    GATHERING FACTS *************************************************************** 
    <52.3.121.253> ESTABLISH CONNECTION FOR USER: Please login as the user "ubuntu" rather than the user "root".
    <52.3.121.253> REMOTE_MODULE setup
    <52.3.121.253> EXEC ssh -C -tt -vvv -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/shutter/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=Please login as the user "ubuntu" rather than the user "root". -o ConnectTimeout=10 52.3.121.253 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1438381926.4-222011237551738 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1438381926.4-222011237551738 && echo $HOME/.ansible/tmp/ansible-tmp-1438381926.4-222011237551738'
    fatal: [52.3.121.253] => SSH Error: command-line line 0: garbage at end of line; "login".
    It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.
    
    TASK: [common | Validate Ansible version] ************************************* 
    FATAL: no hosts matched or all hosts have already failed -- aborting
    
    
    PLAY RECAP ******************************************************************** 
               to retry, use: --limit @/Users/shutter/server.retry
    
    52.3.121.253               : ok=2    changed=0    unreachable=1    failed=0   
    
    Brandons-MacBook-Pro:ansible shutter$ ssh ubuntu@52.3.121.253
    Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-48-generic x86_64)

You can see the error AWS is giving is trying to use `root` instead of `ubuntu`.

`ESTABLISH CONNECTION FOR USER: Please login as the user "ubuntu" rather than the user "root".`

**Comment by BrandonShutter** [comment]
See https://discourse.roots.io/t/aws-ubuntu/4371/19 for conversation leading up to this issue.

**Comment by fullyint** [comment]
Thanks for reporting this, @BrandonShutter 

Back in roots/trellis#274 I didn't anticipate the scenario that a failed connection for `root` could still give a return code of `0`, but it does on an Ubuntu box on AWS.

The following changes to `roles/remote-user/tasks/main.yml` work for me when I test on an AWS EC2 instance. Would you mind testing whether they work for you?
```diff
 ---
 - name: Determine whether to connect as root or admin_user
-  local_action: shell ssh -o PasswordAuthentication=no root@{{ inventory_hostname }} "echo root" || echo {{ admin_user }}
+  local_action: shell ssh -o PasswordAuthentication=no root@{{ inventory_hostname }} "echo can_connect"
+  failed_when: false
   changed_when: false
-  register: remote_user
+  register: root_status

 - name: Set remote user for each host
   set_fact:
-    ansible_ssh_user: "{{ remote_user.stdout }}"
+    ansible_ssh_user: "{{ (root_status.stdout == 'can_connect') | ternary('root', admin_user) }}"
```
The changes above assume that if `root` can connect, the `echo can_connect` command will run as expected. I'd love someone to suggest a more reliable indicator of success/failure in `root` SSH connection, given that we can't rely on return codes.

**Comment by louim** [comment]
If like me you where intrigued how they did get this to work, they actually allow connection as the `root` user. They just execute the command and the close the connection. This is the content of the `/root/.ssh/authorized_keys`:

```
no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="echo 'Please login as the user \"ec2-user\" rather than the user \"root\".';echo;sleep 10" ssh-rsa AAAA<more public key content>EAhdTX AWS
```

**Comment by BrandonShutter** [comment]
@fullyint That fix did indeed work.

**Comment by swalkinshaw** [comment]
@fullyint looks good. Want to do a PR?

**Comment by fullyint** [comment]
PR in #290. I appreciate your time reviewing this @BrandonShutter @louim @swalkinshaw
