### ISSUE TITLE
Backup role

### ISSUE THREAD

**Issue by louim** [roots/trellis#289]
Hello!

Would you guys be interested in a backup role coming by default with Trellis? I have used https://github.com/Stouts/Stouts.backup in the past with great success. It allows differential backup, multiple upload strategies, encryption, and much more feature like specific file restore. 

I could prepare a PR with defaults setting, covering the database and the `uploads` folder.

**Comment by swalkinshaw** [comment]
Stouts looks good. It would be nice to see what kind of configuration would be needed to support Trellis by default.

**Comment by austinpray** [comment]
It looks like this is pretty easy to include as a drop-in solution. I don't really see much benefit in rolling this into stock trellis. 

I would much rather have a trellis supported wiki entry about this than being on the hook for maintaining the actual code.

**Comment by swalkinshaw** [comment]
Closing this as per @austinpray above

**Comment by MWDelaney** [comment]
Just a quick note, I put this together last night. It's preliminary and probably ugly, but it works. Contributions are welcome!

https://github.com/MWDelaney/trellis-backup
