### ISSUE TITLE
Users role should fail if server has no keys

### ISSUE THREAD

**Issue by austinpray** [roots/trellis#294]
Born out of the discussion from https://github.com/roots/trellis/pull/293

>
we could finish the users role with a fail task causing server.yml to fail when all these conditions are met:
>
- not vagrant vm
- sshd_permit_root_login = "no"
- server has no key for admin_user

If for instance the user forgets to configure their SSH keys or their SSH keys do not resolve they should not be locked out of the server.

This is a low-priority enhancement.

**Comment by fullyint** [comment]
Here's an [instance](https://discourse.roots.io/t/help-with-users-on-secured-droplet/4713) of the problem.
