### ISSUE TITLE
Dynamic development IP

### ISSUE THREAD

**Issue by evanfuture** [roots/trellis#295]
So, I have a bash script that gets the latest IP matching the roots default pattern (from the Vagrantfile), adds one to it and sed's it back into the Vagrantfile.  This being so I can have launch multiple boxes without having to launch my /etc/hosts file every time:  https://gist.github.com/evanfuture/baa53fced4b18783e498

Is there a way to integrate this into Ansible maybe, as I find it saves a lot of time?

Referencing: https://github.com/roots/trellis/blob/master/Vagrantfile

**Comment by louim** [comment]
Seems like if would be feasible using `vagrant-hostmanager` instead of `vagrant-hostupdater`.

changing the line referencing the ip in the `Vagrantfile` to : 
```
config.vm.network "private_network", type: "dhcp"
```
and implementing this in the `Vagrantfile`:

```
cached_addresses = {}
config.hostmanager.ip_resolver = proc do |vm, resolving_vm|
  if cached_addresses[vm.name].nil?
    if hostname = (vm.ssh_info && vm.ssh_info[:host])
      vm.communicate.execute("/sbin/ifconfig eth0 | grep 'inet addr' | tail -n 1 | egrep -o '[0-9\.]+' | head -n 1 2>&1") do |type, contents|
        cached_addresses[vm.name] = contents.split("\n").first[/(\d+\.\d+\.\d+\.\d+)/, 1]
      end
    end
  end
  cached_addresses[vm.name]
end
```

This is stolen from: https://github.com/smdahlen/vagrant-hostmanager/issues/86. I haven't tester, so you may need to fiddle a bit with this to get it working. 

Pull request is appreciated if you get it working! :smile:

**Comment by evanfuture** [comment]
I found that before, but I wasn't sure what would be lost by removing vagrant-hostupdater from trellis.

**Comment by louim** [comment]
@evanfuture `vagrant-hostupdater` doesn't seems to be maintained anymore (last commit is from 31 Oct 2013). I think it's all for the best to switch to hostmanager.

**Comment by nathanielks** [comment]
I use https://github.com/oscar-stack/vagrant-auto_network in my projects. I'm a fan.

**Comment by evanfuture** [comment]
Ok, having looked at both plugins, I'm not sure its actually necessary to have a new dependency.  After all, the vagrantfile is in Ruby.  So, I did this:

    # next lines are commands to retrieve the latest ip address used of our prefered pattern from your etc/hosts file.
    latest_ip = File.read("/etc/hosts").scan(/192\.168\.50\.\d{1,3}/).sort.last.delete("192.168.50.").to_i
    latest_ip = latest_ip + 1
    latest_ip = "192.168.50.#{latest_ip}"
    config.vm.network :private_network, ip: latest_ip

That's using the root's convention for ip's.

Major caveat:  It breaks if there is no ip of that pattern.  I'm not sure how to fix that.  If someone lets me know, I can submit a pull request.

**Comment by QWp6t** [comment]
There is no `/etc/hosts` on Windows (it's `%SystemRoot%\System32\drivers\etc\hosts`) so I'm guessing that would cause Vagrant to shit its pants. But I think you're on the right track.

**Comment by evanfuture** [comment]
Yes, and as well, my ruby script doesn't work for ip's of more than one character!  I'll get it eventually.

**Comment by evanfuture** [comment]
Ok, here's the next iteration:
    # next lines are commands to retrieve the latest ip address used of our prefered pattern from your etc/hosts file.
    require 'ipaddr'
    if Vagrant::Util::Platform.windows?
      hostsfile = "#{ENV['WINDIR']}\\System32\\drivers\\etc\\hosts"
    else
      hostsfile = "/etc/hosts"
    end
    ip = File.read(hostsfile).scan(/192\.168\.50\.\d{1,3}/).sort_by! {|ip| ip.split('.').map{ |octet| octet.to_i} }.last
    ips = [ip]
    ips << IPAddr.new(ips.last).succ.to_s
    latest_ip = ips.last
    config.vm.network :private_network, ip: latest_ip

I have no idea if the Windows bit works, but that's the basic idea of it.  Again, if anyone wants to fix it up, I think this is shaping up well!

**Comment by evanfuture** [comment]
It does still break if no ip's match the string, but that's only a single line to fix it.

**Comment by swalkinshaw** [comment]
I'm going to close this for now because I'm not comfortable adding this kind of complexity. I think this feature would be great but just not liking the solutions it requires.

@evanfuture thanks for sharing these.
