### ISSUE TITLE
php_admin_flag[log_errors] = on prevents define('WP_DEBUG_DISPLAY', false);

### ISSUE THREAD

**Issue by JacobDorman** [roots/trellis#297]
`php_admin_flag[log_errors] = on` 
(https://github.com/roots/trellis/commit/11e793bde02347dcab4795d0b1bf433d76a80878#diff-97894dad9044d33182d3b1ad613c6e20R16)

> Any directive type set with php_admin_flag can not be overridden by .htaccess or ini_set().

So if you say, want to configure staging to log errors to file, but not display:
```
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
```

wordpress tries to `ini_set( 'display_errors', 0 )` but is prevented by php_admin_flag

**Comment by JacobDorman** [comment]
would changing those lines to `php_flag` break anything?

**Comment by swalkinshaw** [comment]
@JacobDorman not sure would have to test this again. If you're able to that would be great as well.
