### ISSUE TITLE
Add option to block outgoing mail on development

### ISSUE THREAD

**Issue by retlehs** [roots/trellis#298]
there should be an option to block outgoing mail for development environments

right now it's possible to accidentally send out emails to users/customers/clients, which you probably don't want to do on dev

maybe have a whitelist of allowed domains?

**Comment by louim** [comment]
Better option should be to use [Mailhog](https://github.com/mailhog/MailHog) in the development environment by default to catch all mails.

**Comment by retlehs** [comment]
nice. @kalenjohnson also mentioned http://mailcatcher.me/

**Comment by kalenjohnson** [comment]
Mailhog's catchline: "Inspired by MailCatcher, easier to install."

Sounds good

Built in Go. Sorry Mailhog

**Comment by louim** [comment]
In fact Mailhog is directly inspired from mailcatcher and do the same work, but being in go, it is self contained, and doesn't need Ruby to be run. It provides binary for all platforms https://github.com/mailhog/MailHog/releases

**Comment by kalenjohnson** [comment]
I'd be up to give it a try. Ruby isn't installed on a Trellis box by default, so if something works just as well, no need to have it installed.

**Comment by retlehs** [comment]
https://github.com/geerlingguy/ansible-role-mailhog

**Comment by retlehs** [comment]
closed by #304
