### ISSUE TITLE
Redis Alternative

### ISSUE THREAD

**Issue by rohmann** [roots/trellis#300]
Similar to how you can set `hhvm: true` how would you feel about allowing `redis: true` to install Redis instead of Memcached? This was touched on a bit in #34 but more off-topic there. I've been using Batcache with Redis on half a dozen sites and have come to prefer it over Memcached.

If you're open to it, I'd be happy to submit a PR.

**Comment by kalenjohnson** [comment]
I like the sounds of this, although I would assume there are some Redis playbooks in Ansible Galaxy.

Is there a lot of extra configuration when using Batcache with Redis? I haven't thought of trying that, really. I've played with using Redis for the object and transient cache, but that's as far as I've taken it. But we probably wouldn't want to restrict it to just Batcache, since there are other uses for Redis as well. Even with Trellis, Memcached is installed but it's not really in use by default.

**Comment by nathanielks** [comment]
Batcache only works with Memcache.

**Comment by nathanielks** [comment]
wait wait wait... insert foot in mouth. Batcache just uses whatever you have set for your object cache. Derp.

**Comment by rohmann** [comment]
@nathanielks 
Batcache is simply a page cache that uses the WordPress object cache for persistence. It was originally written when Memcache was the only in-memory object cache readily available, but it will work with any object cache, including Redis.

**Comment by kalenjohnson** [comment]
Well this is embarrassing for someone, *cough cough*

**Comment by nathanielks** [comment]
![p55nlem4g6wmy](https://cloud.githubusercontent.com/assets/314009/9281951/98dc0ae6-428e-11e5-8bb6-78f85cbc4a2d.gif)

**Comment by swalkinshaw** [comment]
If we did an option it would probably look like:

```yaml
cache:
  enabled: true
  backend: redis
```

Or something like (since that conflicts with current microcaching variable).

Sometime in the future I'd like to find a better default caching recommendation and include that by default.

**Comment by rohmann** [comment]
@kalenjohnson 
Batcache itself doesn't require any additional configuration. It just wants a working `object-cache.php`. Last time I used this one (https://github.com/ericmann/Redis-Object-Cache) it worked fine out of the box. I've also used this one (https://github.com/tillkruss/Redis-Object-Cache) but needed to modify it slightly.

**Comment by austinpray** [comment]
```yaml
cache:
  enabled: true
  provider: redis
```

@swalkinshaw-- for bad naming

**Comment by rohmann** [comment]
@swalkinshaw 
Maybe this is too complicated, but what I prefer is having the micro cache at around 5s just as a frontline DOS protection. Then having batcache at around 30 minutes,  because the pages can be properly invalidated by actions like saving posts etc.

**Comment by swalkinshaw** [comment]
@rohmann not too complicated at all. That's easily achievable right now with Trellis.

Problem I have with most caching plugins (including Batcache), is there's a lot of common scenarios where cache invalidation does not happen.

**Comment by rohmann** [comment]
Indeed, and the severity of failure to invalidate varies from project to project. I've found it more useful than not just to keep those homepages nice and snappy.

**Comment by nathanielks** [comment]
authenticated sessions _cough_

**Comment by rohmann** [comment]
What's nice about Batcache is that WP gets a chance to load first, so it aborts any caching if an authentication cookie is present. Then many plugins like WooCommerce make use of the constant `DONOTCACHEPAGE` popularized by W3TC and WP Super Cache. I've added that to Batcache manually to round things out a bit. Too bad WP doesn't really have a one size fits all solution (yet).

**Comment by swalkinshaw** [comment]
Closing this since memcached might not even stay by default. We either have "official" caching (non-microcache) solution or just let people do whatever they want via custom roles.

**Comment by partounian** [comment]
I apologize for asking a question on this closed issue, but does object caching even make sense when full page caching is in use already? Without distribution I don't believe it makes sense, but maybe I don't understand it fully.

**Comment by swalkinshaw** [comment]
It's probably not needed but it's still a different type of cache which might provide additional benefits.

Trellis' micro-caching is "full page" caching, but it's very short lived. So requests still get through to WP even if the page hasn't changed/cache not busted. Those requests would still benefit from object caching persisted to something like Memcached or Redis.

**Comment by partounian** [comment]
I see. Wouldn't it make sense to be using APCu since this is a single server setup?

**Comment by swalkinshaw** [comment]
PHP 5.5+ has built-in opcaching which kind of eliminates the need for APC. I can't really speak to APCu. There might be some additional optimizations?

But you're correct that with singe server setups there's not much point in using Memcached/Redis for an object cache.

**Comment by partounian** [comment]
APCu is object caching, and it's just as fast as Redis. This is an interesting WP specific project with APCu as its base. https://github.com/lcache/wp-lcache/blob/master/readme.md

**Comment by nathanielks** [comment]
A 👎  for APCu is that it's not distributed, so if Trellis ever goes multi-server, caches would be limited to per-instance. That said, APCu is very fast and good at what it does!

**Comment by nathanielks** [comment]
@partounian `wp-lcache` looks legit!

**Comment by nathanielks** [comment]
I don't like that it uses the database for the persistent cache, though... I'd be interested to see if they wrote the persistent layer in a pluggable way. I'd much rather use a persistent cache like Redis than a database for that

**Comment by partounian** [comment]
Lcache uses APCu, also if multi-server setup is allowed for Trellis, there would still need an option for single server. I think it would make sense to have APCu/Lcache for single server, and Redis for multi-server.

**Comment by strarsis** [comment]
APCu somehow appears to have compatibility issues. Most if not all WordPress plugins for APCu seem to be abandoned or their development stalled (the aforementioned [WP LCache](https://de.wordpress.org/plugins/wp-lcache/) mentions this and its last release is 2 years ago now).

Redis seems to emerge as currently best practice for object caching, I like the [WP Redis](https://wordpress.org/plugins/wp-redis/) plugin.
