### ISSUE TITLE
ansible-galaxy requirements

### ISSUE THREAD

**Issue by evanfuture** [roots/trellis#306]
I keep forgetting to run the requirements.yml playbook before I vagrant up.  There is a way to run it before launch, so long as you have this plugin installed:  https://github.com/emyl/vagrant-triggers

Here's the block I've been using in my Vagrantfile:

    if !Vagrant.has_plugin? 'vagrant-triggers'
      puts 'vagrant-triggers missing, please install the plugin:'
      puts 'vagrant plugin install vagrant-triggers'
    end

    config.trigger.before :up do
      requirements = File.join(ANSIBLE_PATH, 'vendor/')
      if !File.exists?(requirements)
        system "ansible-galaxy install -r #{ANSIBLE_PATH}/requirements.yml -p #{ANSIBLE_PATH}/vendor/roles"
      end
    end

Thoughts?

**Comment by swalkinshaw** [comment]
Hmm I'm hesitant to add a plugin just to handle this. It also doesn't account for when updates are made to `requirement.yml`. You'd still need to manually run the command at that point.

**Comment by nathanielks** [comment]
It also expects Vagrant to have run before your other environments. Likely, yes, but it doesn't really solve the issue imo.

**Comment by nathanielks** [comment]
We just need a generator that'll run these commands automatically ( ͡° ͜ʖ ͡°)
```
trellis new boogers_project
```
(half joking, half serious)

**Comment by evanfuture** [comment]
Yes, before I did it this way, I had it run as part of a bash script that set up eveything for the project, moved files around, and filled in variables for me.  Alright, keep it in the back of your minds anyway, I'll close this for now so we don't clutter the repo.
