### ISSUE TITLE
What are Trellis requirements for the shared hosting ?

### ISSUE THREAD

**Issue by cibulka** [roots/trellis#310]
Apologies in advance for a noobness of my question.

I am trying to wrap my head around using Trellis with Capistrano for deploying my Bedrock project at shared hosting. Right now, I am stuck on following error:

```
TASK: [common | Update Apt] *************************************************** 
failed: [web713@cibulka.me] => {"cmd": "apt-get update '&&' apt-get install python-apt -y -q", "failed": true, "rc": 127}
stderr: /bin/sh: apt-get: command not found

msg: /bin/sh: apt-get: command not found
```

After SSHing to remote `/usr/bin` directory, there is indeed no `apt-get` to use. Is there any way around this without completely rewriting Ansible roles you've created for us?

And more generally - is there any list of requirements that the hosting needs to meet in order to use Trellis deploying successfuly?

Thank you!

**Comment by mAAdhaTTah** [comment]
Trellis is for provisioning servers, you wouldn't use it to provision a shared host. It does also do deployments, but you wouldn't use "Trellis with Capistrano." You're also better off posting your questions over on Discourse:

https://discourse.roots.io/

**Comment by swalkinshaw** [comment]
If you want to deploy with Trellis then you'd use our `deploy.yml` playbook. But if you want to use Capistrano then don't use Trellis at all.

**Comment by austinpray** [comment]
@cibulka @swalkinshaw correction: Don't use trellis for remote deployments. I don't see a problem with using Trellis for your local environment with vagrant.

**Comment by cibulka** [comment]
The error above is the result of `ansible-playbook -i hosts/production server.yml` command. So yes, I want to deploy with Trellis, sorry for wrong choice of words.

So, to rephrase my question - would usage of `deploy.yml` work on any server I have SSH access to? Or is there any list of requirements the shared hosting has to meet?

And should we move this discussion to Discourse, as @mAAdhaTTah suggested?

**Comment by cibulka** [comment]
Anyway, I phrased my question hopefully a little better on Roots's Discourse: https://discourse.roots.io/t/requirements-of-shared-hosting-for-staging-production-with-trellis/4540/1

Thank you!
