### ISSUE TITLE
Inconsistencies with logfiles

### ISSUE THREAD

**Issue by retlehs** [roots/trellis#315]
one server:

```
-rw-r----- 1 web  www-data         0 Aug 23 06:45 access.log
-rw-r--r-- 1 root root     121922353 Aug 26 04:31 access.log.1
-rw-r----- 1 web  www-data         0 Aug 23 06:45 error.log
-rw-r--r-- 1 root root         83120 Aug 26 01:41 error.log.1
```

another server:

```
-rw-r--r-- 1 root root     2276589 Aug 26 04:31 access.log
-rw-r--r-- 1 root root       73289 Aug 26 03:23 error.log
```

i don't think either of these are working as intended. 

ref https://github.com/roots/trellis/blob/0a7bdef92097bf875ca8eb1f68f4111549b29fa6/group_vars/all#L60

**Comment by louim** [comment]
> `-rw-r----- 1 web  www-data         0 Aug 23 06:45 error.log`

This one is matching. When the rotation occur, the new log are set correctly. Seem's like the initial log doesn't have the right owner / permissions

**Comment by kalenjohnson** [comment]
I'm also seeing this:
```
-rw-r----- 1 deploy www-data       0 Aug 26 06:35 access.log
-rw-r----- 1 deploy www-data 2651252 Aug 27 23:03 access.log.1
-rw-r----- 1 deploy www-data  213008 Aug 25 10:42 access.log.2.gz
-rw-r----- 1 deploy www-data  240942 Aug 19 09:40 access.log.3.gz
-rw-r----- 1 deploy www-data  288319 Aug 11 13:31 access.log.4.gz
-rw-r----- 1 deploy www-data  262321 Aug  5 12:27 access.log.5.gz
-rw-r----- 1 deploy www-data  803570 Jul 30 20:15 access.log.6.gz
-rw-r--r-- 1 root   root      283252 Jul 15 19:10 access.log.7.gz
```

**Comment by austinpray** [comment]
![image](https://cloud.githubusercontent.com/assets/2192970/9538286/4604883c-4d08-11e5-886e-6b5b840944db.png)

pls fix asap tyvm

**Comment by kalenjohnson** [comment]
actually looks like @austinpray is user error

**Comment by fullyint** [comment]
It's a bit over my head, but I suspect nginx starts its master process as root and uses that user to write the first log, despite our [`nginx_user: www-data`](https://github.com/roots/trellis/blob/7dacb9faa9e8591da65cf2ac5577cac496d0eef4/roles/nginx/defaults/main.yml#L3). The `access.log` seems like it should be the active log, but strangely has file size `0`, probably because current traffic is actually being written to `acccess.log.1`, as I watched happen with my logs. Perhaps this is the same issue:

> **nginx logging to access.log.1 instead of access.log**
The problem was that nginx was not releasing the file handle to the log file upon receiving the -USR1 signal from kill. Long story short, the reason it was not reloading the log files was because the /var/log/nginx folder was not owned by the same user as the nginx worker processes.  I have no idea how that changed (perhaps because this server was remade recently), but changing the folder to be owned by the same user as the nginx worker processes (and fixing the logrotate file to make new logs as web) fixed the issue.
-- [Ben Torell](http://serverfault.com/a/639180)

We could change ownership and permissions of the new logs created by logrotate:
```diff
-       - create 0640 {{ web_user }} {{ web_group }}
+       - create 0644 root root
```
But that's actually the default, so we could just omit the `create`.

That doesn't solve the potential problem that the `logs` directory has different ownership than the nginx worker processes. Maybe the logs folder will have to be owned by root?
> Logs should be controlled by root and handled by the master process.
-- [nginx Ubuntu](https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/499494)

I tried forcing the logrotate by running `/usr/sbin/logrotate -f /etc/logrotate.conf` with the `logs` dir set to `root:root`, then again as `root:www-data`. Each time I had matching values for the `create` parameter. However, real time logging still happened in `access.log.1` instead of `access.log`. The first time I ran the manual `logrotate` per server build, I got this error: `error: error running shared postrotate script for '"/srv/www/**/logs/*.log" '`. Each time I ran the command again and it appeared to rotate logs without error (?).

Do I understand correctly that all the logging is actually happening, just with different file ownership/permissions and different file naming than we expect?

**Comment by retlehs** [comment]
> Do I understand correctly that all the logging is actually happening, just with different file ownership/permissions and different file naming than we expect?

yup

**Comment by alan-c** [comment]
There are two main issues involved here. One is the ownership/permissions of the first access.log and error.log files. The second is the failure of log rotation.


**Initial Log Ownership/Permissions**

With examples from a clean install of Bedrock/Trellis/Sage/Soil, changing only the domain from example.com to logs.dev...

These are as expected. Immediately following `vagrant up` and `vagrant ssh`, 

```
vagrant@logs:~$ cd /srv/www/logs.dev/logs/ && ls -al
total 8
drwxr-xr-x 2 vagrant www-data 4096 Oct  7 19:35 .
drwxr-xr-x 5 vagrant www-data 4096 Oct  7 19:35 ..
-rw-r--r-- 1 root    root        0 Oct  7 19:35 access.log
-rw-r--r-- 1 root    root        0 Oct  7 19:35 error.log
```

Then poking the server via web browser a couple times...
```
vagrant@logs:/srv/www/logs.dev/logs$ ls -al
total 12
drwxr-xr-x 2 vagrant www-data 4096 Oct  7 19:35 .
drwxr-xr-x 5 vagrant www-data 4096 Oct  7 19:35 ..
-rw-r--r-- 1 root    root     2799 Oct  7 19:36 access.log
-rw-r--r-- 1 root    root        0 Oct  7 19:35 error.log
```

Followed by looking at the relevant running processes...
```
vagrant@logs:/srv/www/logs.dev/logs$ ps -eo "%U %G %a" | grep nginx
root     root     nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
www-data www-data nginx: worker process
www-data www-data nginx: worker process
www-data www-data nginx: worker process
www-data www-data nginx: worker process
www-data www-data nginx: worker process
www-data www-data nginx: worker process
www-data www-data nginx: worker process
www-data www-data nginx: worker process
www-data www-data nginx: cache manager process
vagrant  vagrant  grep --color=auto nginx
```

The master process starts as `root`, so the logs are as well. There are ways to change this, both before and after the fact, obviously, but there is nothing unexpected here - although it may be unwanted in your eyes.

**logrotate Not Functioning as desired**

Continuing with the same dev setup...

Forcing a logrotate with the original files results in 
```
...
running postrotate script
error: error running shared postrotate script for '"/srv/www/**/logs/*.log" '
```

So I changed the postrotate script to
```
[ -f /var/run/nginx.pid ] && kill -USR1 `cat /var/run/nginx.pid`
```
as per this commit https://github.com/roots/trellis/pull/377 and then destroyed and rebuilt the vagrant box.

Results from forced logrotate...
```
vagrant@logs:/srv/www/logs.dev/logs$ sudo logrotate -vf /etc/logrotate.d/wordpress-sites
reading config file /etc/logrotate.d/wordpress-sites

Handling 1 logs

rotating pattern: "/srv/www/**/logs/*.log"  forced from command line (8 rotations)
empty log files are not rotated, log files >= 52428800 are rotated earlier, old logs are removed
considering log /srv/www/logs.dev/logs/access.log
  log needs rotating
considering log /srv/www/logs.dev/logs/error.log
  log does not need rotating
rotating log /srv/www/logs.dev/logs/access.log, log->rotateCount is 8
dateext suffix '-20151007'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
previous log /srv/www/logs.dev/logs/access.log.1 does not exist
renaming /srv/www/logs.dev/logs/access.log.8.gz to /srv/www/logs.dev/logs/access.log.9.gz (rotatecount 8, logstart 1, i 8),
old log /srv/www/logs.dev/logs/access.log.8.gz does not exist
renaming /srv/www/logs.dev/logs/access.log.7.gz to /srv/www/logs.dev/logs/access.log.8.gz (rotatecount 8, logstart 1, i 7),
old log /srv/www/logs.dev/logs/access.log.7.gz does not exist
renaming /srv/www/logs.dev/logs/access.log.6.gz to /srv/www/logs.dev/logs/access.log.7.gz (rotatecount 8, logstart 1, i 6),
old log /srv/www/logs.dev/logs/access.log.6.gz does not exist
renaming /srv/www/logs.dev/logs/access.log.5.gz to /srv/www/logs.dev/logs/access.log.6.gz (rotatecount 8, logstart 1, i 5),
old log /srv/www/logs.dev/logs/access.log.5.gz does not exist
renaming /srv/www/logs.dev/logs/access.log.4.gz to /srv/www/logs.dev/logs/access.log.5.gz (rotatecount 8, logstart 1, i 4),
old log /srv/www/logs.dev/logs/access.log.4.gz does not exist
renaming /srv/www/logs.dev/logs/access.log.3.gz to /srv/www/logs.dev/logs/access.log.4.gz (rotatecount 8, logstart 1, i 3),
old log /srv/www/logs.dev/logs/access.log.3.gz does not exist
renaming /srv/www/logs.dev/logs/access.log.2.gz to /srv/www/logs.dev/logs/access.log.3.gz (rotatecount 8, logstart 1, i 2),
old log /srv/www/logs.dev/logs/access.log.2.gz does not exist
renaming /srv/www/logs.dev/logs/access.log.1.gz to /srv/www/logs.dev/logs/access.log.2.gz (rotatecount 8, logstart 1, i 1),
old log /srv/www/logs.dev/logs/access.log.1.gz does not exist
renaming /srv/www/logs.dev/logs/access.log.0.gz to /srv/www/logs.dev/logs/access.log.1.gz (rotatecount 8, logstart 1, i 0),
old log /srv/www/logs.dev/logs/access.log.0.gz does not exist
log /srv/www/logs.dev/logs/access.log.9.gz doesn't exist -- won't try to dispose of it
running prerotate script
renaming /srv/www/logs.dev/logs/access.log to /srv/www/logs.dev/logs/access.log.1
creating new /srv/www/logs.dev/logs/access.log mode = 0640 uid = 1000 gid = 33
running postrotate script
```

Taking a look at the files immediately after...
```
vagrant@logs:/srv/www/logs.dev/logs$ ls -al
total 12
drwxr-xr-x 2 vagrant  www-data 4096 Oct  7 19:38 .
drwxr-xr-x 5 vagrant  www-data 4096 Oct  7 19:35 ..
-rw-r----- 1 www-data www-data    0 Oct  7 19:38 access.log
-rw-r--r-- 1 root     root     2799 Oct  7 19:36 access.log.1
-rw-r--r-- 1 www-data root        0 Oct  7 19:35 error.log
```

Then poke the server some more...
```
vagrant@logs:/srv/www/logs.dev/logs$ ls -al
total 16
drwxr-xr-x 2 vagrant  www-data 4096 Oct  7 19:38 .
drwxr-xr-x 5 vagrant  www-data 4096 Oct  7 19:35 ..
-rw-r----- 1 www-data www-data 4025 Oct  7 19:39 access.log
-rw-r--r-- 1 root     root     2799 Oct  7 19:36 access.log.1
-rw-r--r-- 1 www-data root        0 Oct  7 19:35 error.log
```

**Comment by alan-c** [comment]
Sorry for so much text, but I wasn't sure really sure on which things you'd find obvious and which you'd want to see more. Not intending to be pedantic at all.

**Comment by swalkinshaw** [comment]
@alan-c did you have a solution in mind for the initial log file permissions? I'm thinking they should be `www-data` for consistency.

**Comment by alan-c** [comment]
Yes, the one I was going to suggest is to have Vagrant handle it. I'll test it and put in a pull request if you'd like. To my knowledge, there is no configuration that can be set in nginx to change the initial log file ownership and permissions. So, short of running nginx as a different user - and all the changes that would involve - Vagrant seems a straightforward approach to a fix.

**Comment by swalkinshaw** [comment]
@alan-c sorry just getting back to this. A Vagrant solution would only fix this in development though and it appears the bug is happening on remote servers as well. So I'm not exactly sure what we can do here.

**Comment by swalkinshaw** [comment]
If this bug still exists it's only on development which is fine /shrug

Otherwise it's working as is:

```plain
drwxr-xr-x 2 web      www-data     4096 Apr  2 06:25 ./
drwxr-xr-x 5 web      www-data     4096 Mar 26 01:08 ../
-rw-r----- 1 www-data www-data 23455918 Apr  8 21:04 access.log
-rw-r----- 1 www-data www-data 21456006 Apr  2 06:25 access.log.1
-rw-r----- 1 www-data www-data  2566684 Mar 27 06:25 access.log.2.gz
-rw-r----- 1 www-data www-data  1982755 Mar 19 06:24 access.log.3.gz
-rw-r----- 1 www-data www-data  2517788 Mar 13 06:24 access.log.4.gz
-rw-r----- 1 www-data www-data  1938635 Mar  5 06:25 access.log.5.gz
-rw-r----- 1 www-data www-data  2378826 Feb 27 06:25 access.log.6.gz
-rw-r----- 1 www-data www-data  1985043 Feb 19 06:25 access.log.7.gz
-rw-r----- 1 www-data www-data  2535391 Feb 13 06:25 access.log.8.gz
-rw-r----- 1 www-data www-data   210423 Apr  8 20:38 error.log
-rw-r----- 1 www-data www-data   175521 Apr  2 06:07 error.log.1
-rw-r----- 1 www-data www-data    82301 Mar 27 05:29 error.log.2.gz
-rw-r----- 1 www-data www-data    12458 Mar 19 04:56 error.log.3.gz
-rw-r----- 1 www-data www-data    18068 Mar 13 06:22 error.log.4.gz
-rw-r----- 1 www-data www-data    16574 Mar  5 04:15 error.log.5.gz
-rw-r----- 1 www-data www-data    27157 Feb 27 06:06 error.log.6.gz
-rw-r----- 1 www-data www-data    27647 Feb 19 05:15 error.log.7.gz
-rw-r----- 1 www-data www-data    36021 Feb 13 05:46 error.log.8.gz
```
