### ISSUE TITLE
404 Behaviour needs looking at. Requests returning 301.

### ISSUE THREAD

**Issue by austinpray** [roots/trellis#316]
Bare trells + bedrock master is giving me weird 404 behavior. It's returning 301 Moved Permanently for stuff that should return a 404.

For posterity:

trellis commit 8a84639257bdeaceb3b440823e2ac78c5c17906a
bedrock commit https://github.com/roots/bedrock/tree/5dc485e1058e3a32c218e8d90c9abb5929f16cd4

### run the test

Reduced testcase: https://gist.github.com/austinpray/d067346e447910f9d70a

You can run the tests by cloning the gist:

```
git clone https://gist.github.com/d067346e447910f9d70a.git testTrellis
cd testTrellis
./test.sh
```

You can cleanup by running:

```
./cleanup.sh
```

### results

```
VM is running
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 27 Aug 2015 21:21:05 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Pingback: http://example.dev/wp/xmlrpc.php
Location: http://example.dev/sdfsdfrsgv/
X-UA-Compatible: IE=Edge

HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 27 Aug 2015 21:21:05 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Pingback: http://example.dev/wp/xmlrpc.php
Location: http://example.dev/completelybogus/
X-UA-Compatible: IE=Edge

done
```

### full output

```
HEAD is now at 8a84639... Merge pull request #311 from roots/readme-usage
HEAD is now at 5dc485e... Merge pull request #197 from austinpray/bump
VM is running
* Hostname was NOT found in DNS cache
*   Trying 192.168.50.5...
* Connected to example.dev (192.168.50.5) port 80 (#0)
> HEAD /sdfsdfrsgv HTTP/1.1
> User-Agent: curl/7.37.1
> Host: example.dev
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
HTTP/1.1 301 Moved Permanently
* Server nginx is not blacklisted
< Server: nginx
Server: nginx
< Date: Thu, 27 Aug 2015 21:20:11 GMT
Date: Thu, 27 Aug 2015 21:20:11 GMT
< Content-Type: text/html; charset=UTF-8
Content-Type: text/html; charset=UTF-8
< Connection: keep-alive
Connection: keep-alive
< X-Pingback: http://example.dev/wp/xmlrpc.php
X-Pingback: http://example.dev/wp/xmlrpc.php
< Location: http://example.dev/sdfsdfrsgv/
Location: http://example.dev/sdfsdfrsgv/
< X-UA-Compatible: IE=Edge
X-UA-Compatible: IE=Edge

<
* Connection #0 to host example.dev left intact
* Hostname was NOT found in DNS cache
*   Trying 192.168.50.5...
* Connected to example.dev (192.168.50.5) port 80 (#0)
> HEAD /completelybogus HTTP/1.1
> User-Agent: curl/7.37.1
> Host: example.dev
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
HTTP/1.1 301 Moved Permanently
* Server nginx is not blacklisted
< Server: nginx
Server: nginx
< Date: Thu, 27 Aug 2015 21:20:11 GMT
Date: Thu, 27 Aug 2015 21:20:11 GMT
< Content-Type: text/html; charset=UTF-8
Content-Type: text/html; charset=UTF-8
< Connection: keep-alive
Connection: keep-alive
< X-Pingback: http://example.dev/wp/xmlrpc.php
X-Pingback: http://example.dev/wp/xmlrpc.php
< Location: http://example.dev/completelybogus/
Location: http://example.dev/completelybogus/
< X-UA-Compatible: IE=Edge
X-UA-Compatible: IE=Edge

<
* Connection #0 to host example.dev left intact
done
```

**edit:** added a success case `curl http://example.dev/` to show that the setup is working in the first place.

**Comment by kalenjohnson** [comment]
ty for success case :100:

**Comment by louim** [comment]
Seen this before. I believe it is due to how Nginx rewrite are made. Changing the Wordpress permalink setting to "post" make it work correctly.

**Comment by austinpray** [comment]
@louim yep. That fixes it.

https://codex.wordpress.org/Nginx#URL_Rewrites_.2F_Permalinks

So the question is: do we care?

**Comment by kalenjohnson** [comment]
Perhaps we could add a WP-CLI command to set the site to pretty permalinks by default. I mean, who doesn't turn those on anyways?

**Comment by retlehs** [comment]
@kalenjohnson++

**Comment by retlehs** [comment]
seems like permalinks _should_ be enabled by default as of 4.2: https://core.trac.wordpress.org/ticket/6481

**Comment by kalenjohnson** [comment]
I'm betting it's because WP is installed with wp-cli. I would assume that installing WP via the 5-minute installer would have pretty permalinks enabled.

Man, it's been a while since I did it that way :joy:

**Comment by louim** [comment]
@kalenjohnson I don't believe it makes a difference, or maybe the wp-cli has some hack to install without using the install method of WordPress? This is the function used to check if permalinks can be enabled: https://developer.wordpress.org/reference/functions/wp_install_maybe_enable_pretty_permalinks/

**Comment by kalenjohnson** [comment]
@louim yep I've been looking at it. I'm not sure if the permalink testing works from the command line though... could be completely off base, that was just my assumption.

I'm also going off memory, but I'm pretty sure in the last few months, definitely post-4.2 release, I've had to enable pretty permalinks on a Trellis site. Should probably just give it a try again though to confirm.
