### ISSUE TITLE
Extend trellis without loosing the ability to pull new commits

### ISSUE THREAD

**Issue by fabianhenzler** [roots/trellis#325]
Hi,

I'd like to extend trellis with some roles, like a Migrate DB Job running in the end with wp-cli. But I don't want to loose the ability to pull new stuff from the repo.
Is there a way?

**Comment by louim** [comment]
The cleanest way is to create your own Ansible-Galaxy role with the tasks you want to run, and add it to the `requirements.yml` and to the `server.yml` and /or the `dev.yml` playbooks. 

See for example [this role](https://github.com/louim/bedrock-site-protect) that I made to add htpasswd protection to sites.
