### ISSUE TITLE
Multisite with 9a4b36e

### ISSUE THREAD

**Issue by fabianhenzler** [roots/trellis#326]
Notice: Constant MULTISITE already defined in /srv/www/local.matrix42.com/current/web/wp-config.php on line 11
Warning: Cannot modify header information - headers already sent by (output started at /srv/www/local.matrix42.com/current/web/wp-config.php:11) in /srv/www/local.matrix42.com/current/web/wp/wp-includes/pluggable.php on line 1207
![scr_2015-08-31_09-57-42_am](https://cloud.githubusercontent.com/assets/1168345/9574424/1658a354-4fc7-11e5-8fb7-fda18f268f20.png)

**Comment by fabianhenzler** [comment]
injecting the Multisite config into development.php seems to work pretty well

**Comment by fabianhenzler** [comment]
in combination with bedrock -- forgot to mention

**Comment by alan-c** [comment]
Are you using the latest Trellis and following the instructions in the multisite wiki?

You need to add the multisite constants into `config/application.php`. If they are not added and Bedrock is in use, WP-CLI will stick the constants at the end of the wp-config.php file, which can lead to the error you are seeing.

**Comment by austinpray** [comment]
Added a note about this to https://github.com/roots/trellis/wiki/Multisite so it's 100% clear.
