### ISSUE TITLE
Step "wp core install" fails when selecting hhvm 

### ISSUE THREAD

**Issue by jsilence** [roots/trellis#330]
When I activate the Hip Hop VM and start setting up the Vagrant VM, the above step fails, leaving the Wordpress site unconfigured. 

Symptom: Browsing to the site displays the normal Wordpress installation page.

When sshing into the VM and trying to configure the site with:
`wp core install --allow-root --admin_user=...` 
I get:
`Your PHP installation appears to be missing the MySQL extension which is required by WordPress`

Workaround: Changing php5-mysqlnd to php5-mysql in roles/php/tasks/main.yml

**Comment by swalkinshaw** [comment]
@jsilence thanks for this bug report. I can reproduce the problem as well.

I found that installing `php5-mysqlnd` manually fixed the issue. The entire `php` role is skipped when HHVM is enabled so we can't just add a package to `roles/php/tasks/main.yml`.

**Comment by bensagardoy** [comment]
Reproduced too. I just added this task
```
- name: Install php5-mysqlnd extension to fix Wordpress Installation 
  apt: name=php5-mysqlnd state=present force=yes
```
after the `Install HHVM` task in the hhvm role, and this also fixed the issue for me.

**Comment by swalkinshaw** [comment]
See https://github.com/roots/trellis/issues/431
