### ISSUE TITLE
memcache session

### ISSUE THREAD

**Issue by ale77dan** [roots/trellis#341]
Activate "memcached_sessions" make nginx and php-fpm stop working on a fresh install.
On roles/php/templates/php-fpm.conf.j2 changing
    
    {% if memcached_sessions %}
    session.save_handler = memcached
    session.save_path = "tcp://{{ memcached_listen_ip }}:{{ memcached_port }}"
    {% endif %}

with

    {% if memcached_sessions %}
    php_value[session.save_handler] = memcached
    php_value[session.save_path] = "tcp://{{ memcached_listen_ip }}:{{ memcached_port }}"
    {% endif %}

solved the problem.

**Comment by swalkinshaw** [comment]
Thanks!
