### ISSUE TITLE
Issue with `vagrant ssh` after creating new vm

### ISSUE THREAD

**Issue by redconfetti** [roots/trellis#348]
I'm running into an issue when running `vagrant ssh` immediately after running `vagrant up`. I'm using Trellis with a Bedrock site.

```
$ vagrant ssh
ssh_exchange_identification: Connection closed by remote host
```

When modifying dev.yml to only include the 'sshd' role, this issue still persists. When I comment out the 'sshd' role, the issue is resolved.

```
$ vagrant ssh -- -vvv
$ vagrant ssh -- -vvv
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /Users/myuser/.ssh/config
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: /etc/ssh_config line 102: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 2222.
debug1: Connection established.
debug3: Incorrect RSA1 identifier
debug3: Could not load "/Users/myuser/Projects/myproject/.vagrant/machines/default/virtualbox/private_key" as a RSA1 public key
debug1: identity file /Users/myuser/Projects/myproject/.vagrant/machines/default/virtualbox/private_key type -1
debug1: identity file /Users/myuser/Projects/myproject/.vagrant/machines/default/virtualbox/private_key-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.2
ssh_exchange_identification: Connection closed by remote host
```

Only when I do allow the 'users' role to establish my public key in the VM does the following command work. Using the public key that Vagrant establishes with 127.0.0.1 doesn't work though.

```bash
$ ssh vagrant@192.168.50.5 -p 2222
```

I'm still trying to narrow down the cause of this issue. The /etc/sshd_config that is generated isn't different than the default configuration that is put in place when the 'sshd' role is applied. But certainly when I apply the changes, I'm locked out. When I remove them and rebuild the VM, `vagrant ssh` works fine.

**Comment by redconfetti** [comment]
I think I just discovered the discrepancy.

```
$ vagrant ssh -- -v
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /Users/redconfetti/.ssh/config
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: /etc/ssh_config line 102: Applying options for *
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 2200.
```

It's using port 2200 when the 'sshd' role isn't applied. With the role applied, `vagrant ssh` attempts to use port 2222. I noticed that during the build that isn't failing it includes:

```
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
```

Perhaps there is some sort of port issue, collision with Mac OS X.

**Comment by redconfetti** [comment]
Okay. I've found the solution to this issue.

Vagrant and/or Virtualbox sets up your workstations networking so that port 2222 is forwarded to port 22 of the virtual machine. If you explicitly add the configuration option `sshd_port: 2222` to `group_vars/development/main.yml`, then SSHD is configured to answer on 192.168.50.5:2222 only, and the forwarder from 127.0.0.1:2222 to port 22 of the VM fails because SSH isn't listening on port 22 as expected.

Make sure you do not configure your local development to use port 2222, the VM should answer on port 22 and let the virtualbox network configuration do the port forwarding.

**Comment by swalkinshaw** [comment]
@redconfetti thanks for the detail notes :+1:

**Comment by JJ** [comment]
OK, but what if that sshd_port option is not set? Any idea?
