### ISSUE TITLE
wordpress uploads folder capable of executing php scripts

### ISSUE THREAD

**Issue by erikbelusic** [roots/trellis#352]
if a php script (or some other script) makes it into the uploads folder, the script can be run.

example.com/app/uploads/2015/09/test.php can be run

i am capable of fixing this and submitting a pull request, i am just not sure which file to do this in. my gut says in the wordpress.conf file, but i was trying to find where the 403 is returned when trying to access the uploads folder directly e.g. example.com/app/uploads/2015/09/ OR example.com/app/uploads returns a 403, but im not sure where that is set. i can do it either place!

**Comment by swalkinshaw** [comment]
There's a few options for Nginx but this looks like a simple one (untested):

```nginx
location ~* /app/uploads/.*\.php$ {
    deny all;
}
```

@erikbelusic as you said this should probably live in https://github.com/roots/trellis/blob/master/roles/nginx/templates/wordpress.conf.j2

**Comment by erikbelusic** [comment]
ive used the following block before on a laravel app without issue:

```
location ~* /uploads/.*\.php$ {
	deny all;
}
```

some other resources suggest the following:

```
location ~* /(?:uploads|files)/.*\.php$ {
    deny all;
}
```

i am not a regex person, so im not exactly sure what ```(?:uploads|files)``` does....

thoughts on which of the three is the best?

**Comment by swalkinshaw** [comment]
`(?:uploads|files) just checks for *either* `uploads` or `files`. `?:` means a "non-capturing group" as `()` usually captures the matching part.

```nginx
location ~* /app/uploads/.*\.php$ {
    deny all;
}
```

This is simplest/most direct check since that's the Bedrock path for uploads. We should figure out what the path would be for uploads on a network site though as well.

**Comment by swalkinshaw** [comment]
Looks like we only need that regexp. @erikbelusic want to test that and do a PR if it works? Should probably go here https://github.com/roots/trellis/blob/d8c655082de710f84a780e4b937a0688c57cbfab/roles/nginx/templates/wordpress.conf.j2#L2 above the main `location`.

**Comment by erikbelusic** [comment]
yup! im not familiar with multisite setups too much, so im not sure if something else is needed. does (does bedrock/trellis support multsite fully?).

lastly, do we want to just do ```/app/uploads/``` or do we want to also consider the case where a user is not using bedrock (if this is even possible with trellis)

**Comment by swalkinshaw** [comment]
MS would just look like `app/uploads/sites/<id>/year/month/filename` which is covered by `~* /app/uploads/.*\.php$`.

The rest of Trellis assumes a Bedrock structure so we only support that by default.
