### ISSUE TITLE
php7(-nightly)

### ISSUE THREAD

**Issue by soderlind** [roots/trellis#354]
I guess [PHP 7](http://php7.zend.com/) is on your roadmap. If I want to test it now [with WordPress](https://make.wordpress.org/core/2015/09/10/wordpress-and-php7/), is it enough that I modify `roles/php/tasks/main.yml` ?

**Comment by swalkinshaw** [comment]
Correct. You'll just need to change the `apt_repository` and maybe the extension package names as well.

**Comment by soderlind** [comment]
Excellent, thank you!

**Comment by merchantguru** [comment]
@soderlind how did PHP7 work for you? Can you share your tasks/main.yml?

**Comment by fabianhenzler** [comment]
yes please share you main.yml :) Please @soderlind
