### ISSUE TITLE
Trellis broken for Windows

### ISSUE THREAD

**Issue by EinArzt** [roots/trellis#370]
The check for galaxy roles introduced with this commit 6118bdd75fff1458576fd91a85b0ecc514d3f36b makes it unable for windows users to `vagrant up`.

Error-Message: 
>You are missing the required Ansible Galaxy roles. Run `ansible-galaxy install -r requirements.yml` to get them.

**Comment by louim** [comment]
What `galaxy_roles` value do you get? Maybe include `config_file` just to compare.

You can print it directly by doing `puts galaxy_roles`

**Comment by louim** [comment]
Oh I get it now. Since those roles are installed in the VM on windows, They are not present when the VM is started, hence the fail.

@austinpray we could make the check conditional to the platform, and add a similar check in the `window.sh` file.

**Comment by austinpray** [comment]
Do'oh! Sorry Windows folks!

@louim yeah that's the simplest fix. Windows folks have their stuff installed for them automatically anyway, so yeah no sense in checking.

@EinArzt delete these lines for now: https://github.com/roots/trellis/blob/6905e128d07a20690e777f33b0ba4a621ccc0acf/Vagrantfile#L24-L26 so you can be up and running.

**Comment by EinArzt** [comment]
@austinpray I already did, thanks! :)

**Comment by swalkinshaw** [comment]
Fixed by https://github.com/roots/trellis/pull/367
