### ISSUE TITLE
Configure system cron for multisite

### ISSUE THREAD

**Issue by starise** [roots/trellis#379]
It [looks](https://github.com/roots/trellis/blob/master/roles/wordpress-setup/tasks/main.yml#L22:L29) like the "Setup system cron" task isn't taking into consideration multisite installations. When using subfolders we need to create a cronjob for any active blog in the stack:
```
*/15 * * * * web curl -s http://example.com/{subfolder}/wp-cron.php
```
otherwise the functions that depend on cron (as scheduled posts) will not work for 'subsites'.

**Comment by austinpray** [comment]
I would just disable the system cron:

**Comment by starise** [comment]
I'm sorry, i can't see any reference in the documentation about that issue. I know it can be 'optionally' disabled, but I don't like how wp-cron works. The cron can be also manually added, anyway because actually Trellis expected to work on a multisite setup, it should automatically configure the system cron, isn't it? ;)

**Comment by swalkinshaw** [comment]
And toggle this: https://github.com/roots/bedrock/blob/6f0d96047d53c5552b4d68a1d9d1d20a235adffe/config/application.php#L66

But we could change this conditional as well to check for multisite: https://github.com/roots/trellis/blob/124dbc7252951cb21b3415380ff87cf0b891ba5d/roles/wordpress-setup/tasks/main.yml#L29

**Comment by swalkinshaw** [comment]
@starise I don't think we'll ever make this work seamlessly for multisite. If you have tons of sites then using system cron can actually be bad. Since you have to loop over ALL the sites some can take a long time.

**Comment by louim** [comment]
@starise, it wouldn't be possible to really do it on the system level for multisite. The reason being that the sites creation is dynamic, and not tied to the deploy process. Once multisite is setup, you can create as much site as you want in the admin panel without ever deploying again if you wish. 

The list of cron to run would need to be dynamic and updated on each site creation. Your best bet in that case is to create a mu-plugin that will query the database for all multisite domain and will `curl` them from the script. You would then refer to this single script in your cronjob.

**Comment by starise** [comment]
@louim yes, i was thinking about the same thing: something like [that](http://wptelldus.fisensmosse.se/cron-job-multisite/) as mu-plugin.

@swalkinshaw i got your point. I think a manual solution is needed in this case. Adding a conditional should be an idea. Anyway, considering that system_cron is "true" by default, but in fact broken on multsite, it should be at least mentioned in the readme.

**Comment by swalkinshaw** [comment]
@starise if you'd like to help our docs are on GitHub now: https://github.com/roots/docs/blob/master/trellis/multisite.md
