### ISSUE TITLE
Add some default fail2ban rules

### ISSUE THREAD

**Issue by retlehs** [roots/trellis#380]
add some default fail2ban rules to block against common wordpress attacks 

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)

**Comment by retlehs** [comment]
maybe in the future

**Comment by QWp6t** [comment]
We did it! We made it to the future!

**Comment by retlehs** [comment]
assigned to @swalkinshaw to setup `security.yml` with `fail2ban_services` rules

**Comment by swalkinshaw** [comment]
Mostly done in https://github.com/roots/trellis/pull/1375
