### ISSUE TITLE
Stuck at group vars config file: local_path

### ISSUE THREAD

**Issue by landwire** [roots/trellis#387]
Hi there,

I am not sure what I need to put in here. It's not clear at all from the examples and I have no idea what the ansible root directory would be. How do I find out?

in wordpress_sites.yml:

 local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)

what do I put in local_path???

**Comment by louim** [comment]
Check the readme:
```
example.com/    - Primary folder for the project
├── trellis/    - Your clone of repository
└── site/       - A Bedrock-based site (suggested to name this the generic `site` since your project name is already at the top level)
```

`local_path` needs to point to the Bedrock folder. If you cloned this repo as is, your local Ansible root is this repo folder. To navigate from this folder to your Bedrock folder, that would be `../site` assuming you have named your Bedrock clone folder: `site` and you have them in the same containing folder as per the example in the readme.

**Comment by landwire** [comment]
Thanks for the reply! Trying it as we speak. I still do not find it clear, but then I do not know ansible at all. But maybe a little note in brackets like "trellis/    - Your clone of repository (this is the ansible root directory, if you followed the steps above)" would help :-)
