### ISSUE TITLE
SPDY to HTTP/2

### ISSUE THREAD

**Issue by merchantguru** [roots/trellis#389]
[nginx now supports HTTP/2](https://www.nginx.com/blog/nginx-1-9-5/) and seems to be a drop-in replacement for SPDY. SPDY support is dropped in current versions of nginx (1.9.5+).

**Comment by louim** [comment]
This would require switching from the Stable PPA to the Mainline PPA. (I'm not against it at all, just need  to remember this when we do the switch).

Also note that HTTP/2 require TLS to be taken advantage of. Else the connection will be downgraded. (the spec "support" HTTP/2 unencrypted, but no browser or web server implementation have made it work without TLS).

https://www.nginx.com/blog/nginx-1-9-5/

**Comment by BrandonShutter** [comment]
Cloudflare just released this today: https://www.cloudflare.com/http2/

**Comment by swalkinshaw** [comment]
Yep and unfortunately it confirms that switching from SPDY to H2 should be held off as long as possible until those usage numbers even out. Or until Cloudflare open sources their custom Nginx version/path/extension which enables both.

**Comment by merchantguru** [comment]
Nice catch Scott. Shows [actual H2 support is only ~25%](https://blog.cloudflare.com/introducing-http2/). Without SPDY fallback, doesn't make sense to switch yet. Bummer.

**Comment by swalkinshaw** [comment]
See https://github.com/roots/trellis/pull/433
