### ISSUE TITLE
Consider using WP-CLI nightly for local dev

### ISSUE THREAD

**Issue by danielbachhuber** [roots/trellis#391]
Hi, would you consider using WP-CLI nightly for dev? It's stable enough for local development, and is compatible with WordPress trunk. You just need to replace https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar with https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar

**Comment by swalkinshaw** [comment]
Only if you promise there's no bugs :)

But yeah this is a good idea for development only. See https://github.com/roots/trellis/pull/392

**Comment by austinpray** [comment]
Probably just use nightly everywhere, right? I test my scripts on development and then promote them to production. I don't want my script failing due to it relying on nightly behavior when production has an earlier release.

**Comment by retlehs** [comment]
should we use nightly at all? if we want parity then we should be defining specific versions of wp-cli to use across all environments.

if we switch to nightly, someone could very easily wind up with one nightly version of wp-cli on dev that doesn't match up with remote (or vice-versa).

**Comment by austinpray** [comment]
Oh shoot. Ben is totally right.

**Comment by danielbachhuber** [comment]
> if we switch to nightly, someone could very easily wind up with one nightly version of wp-cli on dev that doesn't match up with remote (or vice-versa).

Why not use nightly for dev, and the latest stable everywhere else?

**Comment by retlehs** [comment]
https://roots.io/twelve-factor-10-dev-prod-parity/

you could end up in a situation where dev works but prod doesn't

for instance - isn't wp-cli going to require a new min version once wp 4.4 is out? what if your remote server has the older version? we need dev and remote to be the same

**Comment by mAAdhaTTah** [comment]
It doesn't look like the task is currently locked to a version as it is. If someone provisions their remote machine and their local env between version releases, they'll have different versions.

**Comment by retlehs** [comment]
correct, #392 should be updated to specify a version

**Comment by swalkinshaw** [comment]
Unfortunately there's no way to link a specific version from the WP-CLI builds at https://github.com/wp-cli/builds/tree/gh-pages/phar.

@danielbachhuber any suggestions? Maybe tags on that repo for versions?

**Comment by QWp6t** [comment]
@swalkinshaw why not just use https://github.com/wp-cli/wp-cli/releases ?

https://github.com/wp-cli/wp-cli/releases/download/v0.20.4/wp-cli-0.20.4.phar
https://github.com/wp-cli/wp-cli/releases/download/v0.21.1/wp-cli-0.21.1.phar
https://github.com/wp-cli/wp-cli/releases/download/v0.21.0/wp-cli-0.21.0.phar

etc.

**Comment by swalkinshaw** [comment]
@QWp6t somehow missed those. That can work :+1:

**Comment by danielbachhuber** [comment]
You can also pull releases programmatically from the Github API: https://api.github.com/repos/wp-cli/wp-cli/releases

Though, note: the releases are sorted by publication date, and not version number.
