### ISSUE TITLE
multisite setting 

### ISSUE THREAD

**Issue by akwatra** [roots/trellis#395]
Hi, 

it seems great, i am testing on this if all well, On multisite set -up
referring your https://roots.io/trellis/docs/multisite/

did not found : 
" If you are using bedrock: you need to make sure you remove the WP-CLI output from wp-config.php and move it to your config/application.php.

You’ll also need to edit the wordpress_sites.yml vars file and update the multisite settings under your environment directory (group_vars/<environment>/wordpress_sites.yml): "

-- i put theme in app/themes 
in network dashboard nothing any theme display 

while click on network admin , url was not configured well as its missed the wp folder in dymanic url link 

-- its already subdomain setup, do we still need to set-up : plugin install landrush ?

--i take care of all setting still not display site ? 

how to resolve this ..

Regards

**Comment by QWp6t** [comment]
Please use https://discourse.roots.io/c/trellis for support questions. This issue tracker is for Trellis development.
