### ISSUE TITLE
Add `wp core upgrade-db` to deploy task

### ISSUE THREAD

**Issue by mAAdhaTTah** [roots/trellis#398]
Got the idea here: https://github.com/wp-cli/wp-cli/issues/2171 Thought it might be a useful addition. Would trellis be interested in adding this by default or would this be better as a per-user thing?

**Comment by danielbachhuber** [comment]
You might want to consider `wp core upgrade-db --network` for upgrading the database across a network of sites.

**Comment by retlehs** [comment]
^^ `update-db` instead of `upgrade-db`
