### ISSUE TITLE
Ansible Vault encrypted files + deploy.sh

### ISSUE THREAD

**Issue by psymeon** [roots/trellis#401]
In the [Trellis Passwords](https://roots.io/trellis/docs/passwords/) docs, one of the recommended methods of protecting config files that contain sensitive data is by encrypting them with Ansible Vault.

However, when running the deploy.sh script there is no way to pass the necessary `--ask-vault-pass` argument to the script.

Shouldn't there be a way to properly handle any extra arguments passed to the script? So far it only seems to be using the [--extra-vars](https://github.com/roots/trellis/blob/master/deploy.sh#L4) argument.

**Comment by louim** [comment]
This is being worked on: https://github.com/roots/trellis/pull/317

**Comment by psymeon** [comment]
Great! Thanks.
