### ISSUE TITLE
Mailgun email issue

### ISSUE THREAD

**Issue by dischord01** [roots/trellis#406]
I am able to send test emails from my server but not through wordpress. I get this error;

```
The e-mail could not be sent.
Possible reason: your host may have disabled the mail() function.
```

here is a sample of my mail.yml;

```
mail_smtp_server: smtp.mailgun.org
mail_admin: postmaster@acquire.cloudworks.io
mail_hostname: acquire.cloudworks.io
mail_user: postmaster@acquire.cloudworks.io
mail_password: key-redactedredactidredactid
```

and this has been my Ansible deploy command;

```
ansible-playbook -i hosts/production server.yml --tags "ssmtp mail"
```

Any ideas what the issue could be?

**Comment by retlehs** [comment]
you sure those settings & credentials work for sending email? wordpress falls back to using php's `mail()` which is configured based off those settings in `mail.yml`

**Comment by chrisk2020** [comment]
Are you using the api key as password - or smtp credentials?
https://help.mailgun.com/hc/en-us/articles/203380100-Where-can-I-find-my-API-key-and-SMTP-credentials-

**Comment by chrisk2020** [comment]
After I slept on it - I reprovisioned and for me it worked. I think my issue was that I was deploying to t he server, but not reprovisioning.

If it helps here is the functioning mail.yml:
<pre>
mail_smtp_server: smtp.mailgun.org
mail_admin: postmaster@mg.mydomain.com
mail_hostname: mydomain.com
mail_user: postmaster@mg.mydomain.com
mail_password: mysmtpcredentialpassword
</pre>

**Comment by dischord01** [comment]
I was using the Mailgun API key not SMTP password. I changed it to SMTP password and it worked. Thanks!
