### ISSUE TITLE
Vagrant default name

### ISSUE THREAD

**Issue by wassimdotis** [roots/trellis#408]
Since the last release, the default name of the virtual machine is 'trellis' and no more the parent directory's name. Now I can't no more quickly differentiate the machines from each other.

Any ideas how to fix this? Should I manually define a machine name in Vagrantfile or move this one to parent dir as we used to do before?

**Comment by swalkinshaw** [comment]
Do you mean the name in VirtualBox? I thought the name always included "default" since we don't define it?

**Comment by retlehs** [comment]
for virtualbox, it shows the directory name (trellis) followed by the name of the virtual machine (default). i'm not sure about other providers

![image](https://cloud.githubusercontent.com/assets/115911/11159569/74400a7c-8a26-11e5-8722-9e9e62d7fbc6.png)

```
➜  ~  vagrant global-status
id       name    provider   state        directory
--------------------------------------------------------------------------------------------
0107ce1  default virtualbox poweroff     /Users/ben/Sites/roots-example-project.com/trellis
```

**Comment by QWp6t** [comment]
@wassimdotis have you been following roots-example-project.com?

If so, then that would explain the issue you're having. We moved the Vagrantfile from the project root into the newly created trellis folder. So the parent directory of the Vagrantfile is now trellis, whereas before it was roots-example-project.com.
