### ISSUE TITLE
Better VM preformance when using 1 CPU core

### ISSUE THREAD

**Issue by primozcigler** [roots/trellis#410]
Hi there,

I had an issue with the local VM (VirtualBox), when the server was responding slowly. I moved the WP network from my previous VM.

The TTFB on the previous VM was around 500ms for the HTML to get back. The stack was pretty much the same (nignx + php-fpm, mariadb).

When I copies the files to the Trellis and dumped the DB, the TTFB increased to around 1500ms - 2000ms. This was unexpected and I couldn't tolerate such deplay during dev, as page is refreshed frequently. I decided to compare the config to find the problem that introduced the delay. Started with php-fpm, went to nginx, mariadb and at the end even tried to disable some extensions like xdebug. Nothing made any significant difference.

I almost gave up at the end, when I remembered to check the Vagrantfile as well. I experimented a bit with various settings and at the end I figured out very interesting thing: if I comment out the `vb.customize ['modifyvm', :id, '--cpus', cpus]` which sets the number of cores for VM, the TTFB drops down to 500-600ms for each request => ~4x perf. boost.

I would like other to get some feedback regarding this and would like to see if anyone else can test this out and confirm the same strange behavior?
The problem is more apparent in more complex WP stacks, with multiple heavy plugins like WooCommerce, Page Builder by SiteOrigin and all the plugins that heavily rely on filters, like simple lightbox.

I am on Linux now, but I experienced the same problem on Mac as well.

Related #62.

**Comment by swalkinshaw** [comment]
Obviously this seems counter to what we'd expect. I don't really have anything to say about this unless other people are also experiencing this.

**Comment by primozcigler** [comment]
I hope other people try this out us know. If not, you are free to close the ticket, but at least you've been warned in case that someone else reports this in the future.

**Comment by QWp6t** [comment]
Intel or AMD?

**Comment by primozcigler** [comment]
Intel. I hope to find some time to do consistent testing with Apache's ab tool this week on multiple machines to either confirm or decline this issue.

**Comment by primozcigler** [comment]
I benchmarked [roots example project](https://github.com/roots/roots-example-project.com) with Apache Benchmark and I can confirm this (OSX 10.10.5, VirtualBox 4.3.30).

Results (run with command `$ ab -n 20 -w http://roots-example-project.dev/`):

#### With `vb.customize ['modifyvm', :id, '--cpus', cpus]`

<table >
<tr ><th colspan=2 bgcolor=white>Server Software:</th><td colspan=2 bgcolor=white>nginx</td></tr>
<tr ><th colspan=2 bgcolor=white>Server Hostname:</th><td colspan=2 bgcolor=white>roots-example-project.dev</td></tr>
<tr ><th colspan=2 bgcolor=white>Server Port:</th><td colspan=2 bgcolor=white>80</td></tr>
<tr ><th colspan=2 bgcolor=white>Document Path:</th><td colspan=2 bgcolor=white>/</td></tr>
<tr ><th colspan=2 bgcolor=white>Document Length:</th><td colspan=2 bgcolor=white>6416 bytes</td></tr>
<tr ><th colspan=2 bgcolor=white>Concurrency Level:</th><td colspan=2 bgcolor=white>1</td></tr>
<tr ><th colspan=2 bgcolor=white>Time taken for tests:</th><td colspan=2 bgcolor=white>5.822 seconds</td></tr>
<tr ><th colspan=2 bgcolor=white>Complete requests:</th><td colspan=2 bgcolor=white>20</td></tr>
<tr ><th colspan=2 bgcolor=white>Failed requests:</th><td colspan=2 bgcolor=white>0</td></tr>
<tr ><th colspan=2 bgcolor=white>Total transferred:</th><td colspan=2 bgcolor=white>135000 bytes</td></tr>
<tr ><th colspan=2 bgcolor=white>HTML transferred:</th><td colspan=2 bgcolor=white>128320 bytes</td></tr>
<tr ><th colspan=2 bgcolor=white>Requests per second:</th><td colspan=2 bgcolor=white>3.44</td></tr>
<tr ><th colspan=2 bgcolor=white>Transfer rate:</th><td colspan=2 bgcolor=white>22.64 kb/s received</td></tr>
<tr ><th bgcolor=white colspan=4>Connnection Times (ms)</th></tr>
<tr ><th bgcolor=white>&nbsp;</th> <th bgcolor=white>min</th>   <th bgcolor=white>avg</th>   <th bgcolor=white>max</th></tr>
<tr ><th bgcolor=white>Connect:</th><td bgcolor=white>    0</td><td bgcolor=white>    0</td><td bgcolor=white>    3</td></tr>
<tr ><th bgcolor=white>Processing:</th><td bgcolor=white>  263</td><td bgcolor=white>  291</td><td bgcolor=white>  566</td></tr>
<tr ><th bgcolor=white>Total:</th><td bgcolor=white>  263</td><td bgcolor=white>  291</td><td bgcolor=white>  569</td></tr>
</table>

#### With `vb.customize ['modifyvm', :id, '--cpus', 1]`

<table >
<tr ><th colspan=2 bgcolor=white>Server Software:</th><td colspan=2 bgcolor=white>nginx</td></tr>
<tr ><th colspan=2 bgcolor=white>Server Hostname:</th><td colspan=2 bgcolor=white>roots-example-project.dev</td></tr>
<tr ><th colspan=2 bgcolor=white>Server Port:</th><td colspan=2 bgcolor=white>80</td></tr>
<tr ><th colspan=2 bgcolor=white>Document Path:</th><td colspan=2 bgcolor=white>/</td></tr>
<tr ><th colspan=2 bgcolor=white>Document Length:</th><td colspan=2 bgcolor=white>6416 bytes</td></tr>
<tr ><th colspan=2 bgcolor=white>Concurrency Level:</th><td colspan=2 bgcolor=white>1</td></tr>
<tr ><th colspan=2 bgcolor=white>Time taken for tests:</th><td colspan=2 bgcolor=white>3.330 seconds</td></tr>
<tr ><th colspan=2 bgcolor=white>Complete requests:</th><td colspan=2 bgcolor=white>20</td></tr>
<tr ><th colspan=2 bgcolor=white>Failed requests:</th><td colspan=2 bgcolor=white>0</td></tr>
<tr ><th colspan=2 bgcolor=white>Total transferred:</th><td colspan=2 bgcolor=white>135000 bytes</td></tr>
<tr ><th colspan=2 bgcolor=white>HTML transferred:</th><td colspan=2 bgcolor=white>128320 bytes</td></tr>
<tr ><th colspan=2 bgcolor=white>Requests per second:</th><td colspan=2 bgcolor=white>6.01</td></tr>
<tr ><th colspan=2 bgcolor=white>Transfer rate:</th><td colspan=2 bgcolor=white>39.59 kb/s received</td></tr>
<tr ><th bgcolor=white colspan=4>Connnection Times (ms)</th></tr>
<tr ><th bgcolor=white>&nbsp;</th> <th bgcolor=white>min</th>   <th bgcolor=white>avg</th>   <th bgcolor=white>max</th></tr>
<tr ><th bgcolor=white>Connect:</th><td bgcolor=white>    0</td><td bgcolor=white>    0</td><td bgcolor=white>    2</td></tr>
<tr ><th bgcolor=white>Processing:</th><td bgcolor=white>  151</td><td bgcolor=white>  166</td><td bgcolor=white>  358</td></tr>
<tr ><th bgcolor=white>Total:</th><td bgcolor=white>  151</td><td bgcolor=white>  166</td><td bgcolor=white>  360</td></tr>
</table>

---

More real-world example (more complex theme, couple of plugins installed) was even more problematic:

#### With `vb.customize ['modifyvm', :id, '--cpus', cpus]`

<table >
<tr ><th bgcolor=white colspan=4>Connnection Times (ms)</th></tr>
<tr ><th bgcolor=white>&nbsp;</th> <th bgcolor=white>min</th>   <th bgcolor=white>avg</th>   <th bgcolor=white>max</th></tr>
<tr ><th bgcolor=white>Connect:</th><td bgcolor=white>    0</td><td bgcolor=white>    0</td><td bgcolor=white>    2</td></tr>
<tr ><th bgcolor=white>Processing:</th><td bgcolor=white>  873</td><td bgcolor=white>  930</td><td bgcolor=white> 1194</td></tr>
<tr ><th bgcolor=white>Total:</th><td bgcolor=white>  873</td><td bgcolor=white>  930</td><td bgcolor=white>  1196</td></tr>
</table>

#### With `vb.customize ['modifyvm', :id, '--cpus', 1]`

<table >
<tr ><th bgcolor=white colspan=4>Connnection Times (ms)</th></tr>
<tr ><th bgcolor=white>&nbsp;</th> <th bgcolor=white>min</th>   <th bgcolor=white>avg</th>   <th bgcolor=white>max</th></tr>
<tr ><th bgcolor=white>Connect:</th><td bgcolor=white>    0</td><td bgcolor=white>    0</td><td bgcolor=white>    2</td></tr>
<tr ><th bgcolor=white>Processing:</th><td bgcolor=white>  230</td><td bgcolor=white>  333</td><td bgcolor=white>  687</td></tr>
<tr ><th bgcolor=white>Total:</th><td bgcolor=white>  230</td><td bgcolor=white>  333</td><td bgcolor=white>  689</td></tr>
</table>

**Comment by primozcigler** [comment]
I pinged @swrobel [over twitter](https://twitter.com/primozcigler/status/676130080830173184). It would be great to have him elaborate on this, as AFAIK you guys added these Vagrantfile 'improvements' after [this blogpost](https://stefanwrobel.com/how-to-make-vagrant-performance-not-suck#toc_1).

**Comment by primozcigler** [comment]
Moreover, I experience the same issues on linux machine as well.

**Comment by swrobel** [comment]
@primozcigler really interesting findings. I suppose in my post, I take for granted that more cpus = better performance, or at least that it won't cause *worse* performance. One thing to note is that you didn't test concurrency - not that is a typical concern in development contexts. I used [wrk](https://github.com/wg/wrk) for my NFS vs VirtualBox sharing benchmarks because it's supposed to better emulate real-world traffic than `ab` but I still have no explanation for why you're seeing reduced performance.

**Comment by primozcigler** [comment]
@swrobel thanks for stopping by :smiley: 

I could use wrk as well, but I can tell the performance slowdown is noticeable even when developing - without benchmarks.
So there's no need for me to test this again. It would be great if anyone else takes couple of minutes of time and does independent test. Hopefully guys here at Roots, maybe this is particular to WP - I haven't bother to benchmark other stacks.

**Comment by swalkinshaw** [comment]
Figured I'd test this out myself. I'm a bit dubious of how much these benchmarks matter and they definitely aren't rigorous or anything.

I timed `vagrant up` and then the `ab` bench you posted:

### CPUS: 4 (`sysctl -n hw.ncpu`)
* `vagrant up`: 7:45.16
* `ab -n 20 -w http://example.dev/`: ~3.3 req/s

### CPU: 1
* `vagrant up`: 9:17.21
* `ab -n 20 -w http://example.dev/`: ~4.2 req/s

I ran the `ab` bench a few times.

Funny enough I also found this: https://github.com/rdsubhas/vagrant-faster/issues/5

Anecdotal but I'm leaning towards removing this cpu configuration.

**Comment by swalkinshaw** [comment]
@primozcigler thanks for bringing this up. Finally went with 1 as the default.

**Comment by primozcigler** [comment]
My pleasure.
