### ISSUE TITLE
Stop Cron Jobs from Sending Emails

### ISSUE THREAD

**Issue by nbyloff** [roots/trellis#412]
By default, cron is trying to send emails after the http://sitename.com/wp/wp-cron.php job is run. I do this manually every time I checkout Trellis, but thought it might be useful for all installs, or at least a configurable option that allows the user to turn off email responses after a cron job is run.

Done simply by adding ``` > /dev/null 2>&1```

```javascript
- name: Setup WP system cron
  cron:
    name: "{{ item.key }} WordPress cron"
    minute: "*/15"
    user: "{{ web_user }}"
    job: "curl -s {{ item.value.env.wp_siteurl }}/wp-cron.php > /dev/null 2>&1"
    cron_file: "wordpress-{{ item.key | replace('.', '_') }}"
  with_dict: wordpress_sites
  when: item.value.env.disable_wp_cron | default(false) and not item.value.multisite.enabled | default(false)
```

**Comment by swalkinshaw** [comment]
@nbyloff thanks, do you want to create a PR for this? It should be the default in my opinion.

**Comment by nbyloff** [comment]
@swalkinshaw sure thing. added.
