### ISSUE TITLE
Config File and auto install Sage & Bedrock on Vagrant Up

### ISSUE THREAD

**Issue by nbyloff** [roots/trellis#415]
I have been playing around with a forked instance of Trellis, and I borrowed some code from another project on Github for testing. I have tested this on Windows, and while it says it works on Mac & Linux, I have not tested it. So far with that projects help I have:

* Changed the Vagrantfile to use a config file for specifying options
* Enabled SSH forwarding on Windows so I can deploy & provision to remote machines using my personal Public/Private keys

Because the SSH forwarding should work in all environments, next I hope to:

* Configure the Vagrantfile to optionally auto clone Bedrock & Sage and setup the project for me on first `vagrant up`
* Add config variables to allow me to auto install `nvm` and `bower` as well (optionally) on the VM.
* Allow user to optionally configure private repos they may have of their own existing projects

While this is pretty limited so far, this is my `Trellis.yaml` config file

```javascript
vm:
  ip: 192.168.50.5
  memory: 1024
  cpus: 1
  box: ubuntu/trusty64

trellis:
  version: master
  debug: false
  https: false
  ansible_path: ansible

# Github account info
git:
  username: myuser
  email: myemail@example.com

# Leave blank if using only local vagrant insecure key
# or you do not need to SSH forward to other boxes
# with the same key
security:
  box_public_key: ~/.ssh/id_rsa.pub
  box_private_key: ~/.ssh/id_rsa
  forward_agent: true
```

This is the project & Vagrantfile I based my changes on: https://github.com/alt3/cakebox
Here's the commit that accomplishes the top two bullets:
f56716779700d66fbdacefc2da4546d13c500286

Is this something worth doing or anyone is interested in? This whole project makes things really easy in a couple steps. Thought might be nice to have it all done in one step.

**Comment by swalkinshaw** [comment]
Thanks for sharing this. It's pretty cool and definitely simpler which is something we're trying to get better at.

We've just started on a roots-cli project at https://github.com/roots/roots-cli which will go a long way towards that goal. It will automated a lot of the boilerplate setup.

I'm going to close this issue because of that, but feel free to continue some discussion in here if you want. There might be something in there that would work separate like Trellis. Maybe SSH keys/forwarding for WIndows? I don't know much about that process.

**Comment by nbyloff** [comment]
Fair enough. I saw that project but posted here for now for visibility. Majority of my team is Mac, but I stress environment agnostic code before making it in the `master`. So I test everything in Windows.

I got all the bullet points above working in my local Trellis install, but i'll look at options on `roots-cli` and contribute where I can. 

The SSH forwarding on Windows was a necessary monster for instances where the IT manager for specific vendors preferred that.

**Comment by nbyloff** [comment]
Mac/Linux SSH forwarding should work just fine the way the default project is. I have just included the necessary files to make it work on Windows, and only loads them on Windows machines. I think it's worth while including the main Trellis project. All the other configuration makes more sense in roots-cli. 

I needed a reason to get back into go. :)

**Comment by QWp6t** [comment]
SSH forwarding on Windows was a pain in the ass for me as well.

With upcoming Vagrant 1.8, I'll be working on getting Trellis to not be as hostile toward Windows developers. SSH forwarding might not even be a problem at that point, but I haven't tested yet to be sure.

If you want to submit a PR with just the stuff you did to resolve SSH forwarding, or maybe open an issue with an overview of what you're doing to resolve it, that would probably be something worth considering for Trellis. If you don't feel like doing that, I'll do it this weekend when I test vagrant 1.8.

**Comment by nbyloff** [comment]
I can create a pull request for sure. Is it supposed to work for Windows in 1.8? I didn't see anything in the changelog. 

Regardless, I will submit the PR. The only requirement for Windows users outside of including these scripts in Trellis is to have Pageant running with their key added before `vagrant up`

http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html
