### ISSUE TITLE
A+ SSL support is now a B

### ISSUE THREAD

**Issue by jgraup** [roots/trellis#416]
On the [Trellis Page](https://roots.io/trellis/) you mention an A+ rating. Currently the SSL implementation scores a [B](https://www.ssllabs.com/ssltest/analyze.html?d=roots.io) on the Qualys SSL Labs Test.

> Assessed on:  Thu, 19 Nov 2015 16:33:15 UTC
>
> This server supports weak Diffie-Hellman (DH) key exchange parameters. Grade capped to B.   [MORE INFO »](https://weakdh.org)

**Comment by nbyloff** [comment]
FWIW, I just tested a ecommerce site I did with Trellis about a month ago, and it still reports an A+.

**Comment by retlehs** [comment]
the roots.io box is on a pretty old bedrock-ansible version that was prior to the strong DH key implementation in trellis i believe. need to migrate it to the latest trellis :)

**Comment by swalkinshaw** [comment]
Closing this as it's not an issue with Trellis but with roots.io, but thanks for notifying us.
