### ISSUE TITLE
Vagrant "stdin: is not a tty" error message

### ISSUE THREAD

**Issue by mullnerz** [roots/trellis#419]
On Windows we can clean the "vagrant up" output with this line included in the Vagrantfile.
`config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"`
It is safe to add this, this is working on other platforms too. 
This is the "offical" fix for the problem: https://github.com/mitchellh/vagrant/issues/1673

**Comment by nbyloff** [comment]
@mullnerz I was annoyed by that issue too. I created PR #418 for SSH forwarding, but also includes this fix.
