### ISSUE TITLE
Symlink mysql.sock for HHVM fails when mysql_remote_database is true

### ISSUE THREAD

**Issue by hjrnunes** [roots/trellis#430]
I presume we should just skip this task if we're not setting up a local database?

Adding
```
when: not mysql_remote_database
```
to the task fixes it.

**Comment by swalkinshaw** [comment]
Yeah, you can do that for now. We have some work in progress updates which remove the need for that altogether: https://github.com/roots/trellis/pull/343.

**Comment by swalkinshaw** [comment]
See https://github.com/roots/trellis/issues/431
