### ISSUE TITLE
PHP 7 and HHVM removal

### ISSUE THREAD

**Issue by swalkinshaw** [roots/trellis#431]
Now that [PHP 7](http://php.net/archive/2015.php#id2015-12-03-1) has been released, it will become the default in Trellis soon enough.

PHP 7 offers enough performance improvements to make it roughly equivalent with HHVM. Because of this, we'll be removing HHVM entirely.

Supporting both of them adds a lot of complexity and bugs. Not to mention the actual differences between the two and bugs within HHVM itself.

**Comment by merchantguru** [comment]
Totally agree!

**Comment by swalkinshaw** [comment]
Closed via https://github.com/roots/trellis/pull/432
