### ISSUE TITLE
Requests for missing .php files result in incorrect 404

### ISSUE THREAD

**Issue by retlehs** [roots/trellis#436]
`http://example.com/doesnt-exist.php` returns "File not found" instead of the WordPress 404 

`http://example.com/doesnt-exist.html` is good
`http://example.com/doesnt-exist` is good

**Comment by pacotole** [comment]
I have the same problem again with the last versions of Trellis.

**Comment by retlehs** [comment]
@pacotole unable to reproduce. please use https://discourse.roots.io/ if you still need support.

![image](https://cloud.githubusercontent.com/assets/115911/20719792/3cb04f10-b61a-11e6-9059-e7e1f250eb2c.png)

**Comment by pacotole** [comment]
@retlehs yes, in vagrant works as expected but in server (staging or production) somefile.php returns "File not found" instead of the WordPress 404.

I'll try on a server with all the WP plugins disabled to discard that possibility...

**Comment by fullyint** [comment]
@pacotole would love to have you test the proposed fix in #692 if you're interested

**Comment by pacotole** [comment]
@fullyint Problem solved!! Thanks =)
