### ISSUE TITLE
no host entries after suspend

### ISSUE THREAD

**Issue by mockey** [roots/trellis#445]
I just updated to current head and it seems that the host entries are removed on `suspend` now. But they are apparently not written back on `up`. It works fine after `halt`.
I had an older versiion running for some time that kept the host entries on `suspend`, so must have changed recently. Great work BTW.

**Comment by swalkinshaw** [comment]
See https://github.com/roots/trellis/pull/443.

Can you install the new plugin and see if it works as expected?

**Comment by mockey** [comment]
OK, I installed vagrant-hostmanager (and unistalled vagrant-hostsupdater). hosts entries are written on `up` (if they are not there) and not touched on `suspend` or `halt`. As hostmanager appaently only hooks into `up` and `destroy` that seems to work as expected.
I saw that `var/exports` gets updated on every `up` (after a `halt`). Is this intentional?

**Comment by swalkinshaw** [comment]
I believe the `exports` stuff is from Vagrant itself. We don't do anything special for it or for hosts either. We're just relying on the plugin.
