### ISSUE TITLE
failed SSH connection to box after `vagrant up`

### ISSUE THREAD

**Issue by timiyay** [roots/trellis#46]
I recently updated the `roots/bedrock` Vagrant box to 0.3.0, and can't get the box to load up. After running `vagrant up` and booting, the client fails to connect via SSH. Instead, the connection times out and retries repeatedly:

```
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
```

I'm running Vagrant 1.6.5

**Comment by alx** [comment]
Hi all,

I've got the same kind of issue, and tried every mentionned in this thread without success.
Everything is a fresh install on a debian wheezy.

Could you help me debug this problem ?

In virtualbox GUI, the bedrock virtual machine is running.

Here is a part of the VAGRAND_LOG=debug log : 
```
DEBUG ssh: == Net-SSH connection debug-level log START ==
DEBUG ssh: D, [2015-01-24T00:56:57.428328 #24515] DEBUG -- net.ssh.transport.session[51c44cc]: establishing connection to 127.0.0.1:2222
D, [2015-01-24T00:56:57.429399 #24515] DEBUG -- net.ssh.transport.session[51c44cc]: connection established
I, [2015-01-24T00:56:57.429904 #24515]  INFO -- net.ssh.transport.server_version[51c7f8c]: negotiating protocol version
DEBUG ssh: == Net-SSH connection debug-level log END ==
```

Here trying with command line : 

```
$ ssh -vvv -p 2222 -i /home/alx/.vagrant.d/insecure_private_key vagrant@localhost 
OpenSSH_6.0p1 Debian-4+deb7u2, OpenSSL 1.0.1e 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to localhost [::1] port 2222.
debug1: connect to address ::1 port 2222: Connection refused
debug1: Connecting to localhost [127.0.0.1] port 2222.
debug1: Connection established.
debug3: Incorrect RSA1 identifier
debug3: Could not load "/home/alx/.vagrant.d/insecure_private_key" as a RSA1 public key
debug1: identity file /home/alx/.vagrant.d/insecure_private_key type -1
debug1: identity file /home/alx/.vagrant.d/insecure_private_key-cert type -1
```

Then if hangs...

**Comment by nathanielks** [comment]
Is this immediately after a provision? Have you ssh'd in a few times before you weren't able to connect?



—

**Comment by alx** [comment]
Yes, it appears on the first time I'm setting up the vm with `vagrant up` command.

I've tried a few destroy/up with info from comments on this thread, but still get this same error.

**Comment by Phpanos** [comment]
For me the files existed in /etc/ssh but were empty (Check /var/log/auth.log for the errors). So I removed all ssh_host* files and ran:
vagrant halt
vagrant destroy
vagrant up --provision

And that solved it for me.

**Comment by mmikeww** [comment]
I was having this same problem.

My issue was, I am on a Windows laptop. I installed Ubuntu guest into a VirtualBox VM on the Windows host. Then, inside that Ubuntu, I attempted to install trellis/vagrant/anothervirtualbox. And I ran into this SSH error. 

This link recommended I turn on the vb.gui setting to debug, which showed me some virtualization error:
https://discourse.roots.io/t/timed-out-while-waiting-for-the-machine-to-boot/5943/

Some more googling brought me to this link:
http://stackoverflow.com/questions/24620599/error-vt-x-not-available-for-vagrant-machine-inside-virtualbox

That link explained that the problem was the nested VM attempt. Apparently VirtualBox doesn't support nested 64-bit VMs. Installing VMWare Player on my Windows host, allowed me to nest the VMs successfully.

**Comment by JJ** [comment]
I just had the same problem. It stopped after a while with the message:
```
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.
```

However, checked VB and the machine seemed to be running, although it was not responding to ssh. I tried `vagrant up` again and it up and started without an (apparent) problem, although it required to enter the sudo password.

**Comment by at-thuytran** [comment]
I checked folder `.vagrant\machines\default\virtualbox`, I saw don't have file `private_key`. I added that and ran `vagrant reload` it ok.

**Comment by lehien** [comment]
I solved this problem with:
`vagrant halt`
`vagrant up --provision`
But it is really annoyed because in some day, this problem comes back and I have to use the above way.

**Comment by kmurudi** [comment]
Fixed for me too after deleting/destroying previously created vms.

**Comment by ayeremir** [comment]
You need a vagrant destroy than you should reload with a vagrant up --provision while you shutdown the machine and be careful you will maybe need to restart your pc and that's what worked fine for me ;)
