### ISSUE TITLE
502 Bad gateway when cache: true

### ISSUE THREAD

**Issue by toppetoppe** [roots/trellis#472]
Hey!

Im trying out the new php 7 stuff and im getting 502 Bad Gateway when using cache: true

The error.log in /srv/www/site/logs says the following
```
2016/01/27 16:15:51 [crit] 25593#25593: *11 connect() to unix:/var/run/php-fpm-wordpress.sock failed (2: No such file or directory) while connecting to upstream, client: xxx.xx.xx.xx, server: site.site, request: "GET /wp/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-wordpress.sock:", host: "site.site"
```

(I removed some sensitive stuff from the log output)

If I disable cache, the site works fine.

**Comment by swalkinshaw** [comment]
Thanks for the report.

Were you toggling the cache setting and just running the playbook again? I just set `cache: true` on a fresh Vagrant box and everything worked fine.

**Comment by swalkinshaw** [comment]
Tested this by toggling the setting and trying with SSL on/off as well. Couldn't reproduce it at all.

**Comment by toppetoppe** [comment]
I got this error on a fresh digital ocean droplet when running production. I'll send more info soon.

**Comment by toppetoppe** [comment]
Ok, tested with a fresh trellis / bedrock setup and could not reproduce. Guess something was wierd with our original setup, tried to enable cache and now it works.
