### ISSUE TITLE
Laravel / Lumen?

### ISSUE THREAD

**Issue by ionut-tanasa** [roots/trellis#476]
Hi,

First of all I would like to thank you for this awesome project. We use it daily at the company where I work. I has become the first thing we use when starting a new WordPress project. Using Bedrock, of course!

So now comes the big question:
Could you redesign it a bit to integrate it with [Laravel](https://laravel.com/) or [Lumen](https://lumen.laravel.com/)? Same workflow, same configuration etc. Instead of WordPress we install Laravel.

I am pretty new to Ansible and I tried to twist the roles a bit locally, but with no luck.
Maybe someone else out there thinks the same as I do.

I can provide any kind of information on how to setup a Laravel/Lumen application if needed.

**Comment by QWp6t** [comment]
I'd love to see this as well since I'm a big fan of Laravel. But like you, I don't know enough about ansible. Have you looked into Laravel Homestead? That might hold you over until one of us can figure out Laravel well enough to write an ansible role for trellis. lol

**Comment by ionut-tanasa** [comment]
I am currently using Honestead, but it got kinda clogged now. I think I have 50ish projects on it. But this is not the point I wanted to make earlier. 

Using Trellis we'd have the same server configuration on the local VM, in production and staging. Plus the deploy is a piece of cake.

Personally I don't care about hard drive space. I can, actually I'd like, to have single VMs per project.

**Comment by QWp6t** [comment]
You can use a single VM per project with Homestead too, just in case you didn't know that. (just search for "per project installation" on [this page](https://laravel.com/docs/5.2/homestead))

Not that I'm trying to steer you away from Trellis. Just letting you know in case you need a solution to hold you over for now. If I wasn't so dumb with Ansible, I'd tell you how to get Laravel going with Trellis. ;o

**Comment by ionut-tanasa** [comment]
Gotcha! 
Some day a new pull request will appear. Some day :d 

Thanks for your time.

I think we could close this. I just wanted to throw an idea out there :)

**Comment by alexandcote** [comment]
@ionut-tanasa If you're still interested into a Laravel support for Trellis, I build a role for Laravel.

**Comment by oppiansteve** [comment]
@alexandcote I'd be interested in seeing what you've done

**Comment by ionut-tanasa** [comment]
@alexandcote ofc i'm interested :D

**Comment by richardjkeys** [comment]
@alexandcote @ionut-tanasa I'd also be interested in seeing anything you've done on this. Love the idea.
