### ISSUE TITLE
Custom Nginx includes and logs folder permissions

### ISSUE THREAD

**Issue by kenanfallon** [roots/trellis#485]
After following the [Nginx includes](https://roots.io/trellis/docs/nginx-includes/) documentation to include the [h5bp expire rules ](https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/location/expires.conf), Trellis doesn't provision the .conf changes correctly.

When I ssh into the server after the provision, I can see the .conf file in the correct folder but the server is not loading the .conf changes (expire headers are not set on the files).

When I check the Nginx config by `sudo nginx -t` it returns

`nginx: the configuration file /etc/nginx/nginx.conf syntax is ok`
`nginx: [emerg] open() "/usr/share/nginx/logs/static.log" failed (2: No such file or directory)`
`nginx: configuration file /etc/nginx/nginx.conf test failed`

When I try to force a reload of Nginx by `sudo /etc/init.d/nginx reload` it fails to reload the Nginx configuration and returns

`* Reloading nginx configuration nginx                                                                                             [fail]`

If I create the folder at `/usr/share/nginx/logs/` and run `sudo /etc/init.d/nginx reload` again, it reloads the conf changes with no errors and the .conf changes come through OK (expire headers are set).

I'm unsure if this is due to the Nginx Reload role in the playbook being incorrect, or that the `/usr/share/nginx/logs/` folder has not being created.

**Comment by Foxaii** [comment]
There's nothing wrong with the playbooks. The issue is the h5bp rules are attempting to write a log to a non-existent directory, so you just need to customise the rules to your requirements. 

There is already a log folder available for each site installed by Trellis. You should just use that:

```
# cache.appcache, your document html and data
location ~* \.(?:manifest|appcache|html?|xml|json)$ {
  expires -1;
  # access_log logs/static.log;
  access_log {{ www_root }}/{{ item.key }}/logs/static.log
}

```

**Comment by kenanfallon** [comment]
Thanks @Foxaii. It appears I was overlooking the error that Nginx was returning.
