### ISSUE TITLE
Required module mysqlnd not loaded

### ISSUE THREAD

**Issue by chrisnx** [roots/trellis#499]
Hello.

I'm working with a fresh install of trellis (cloned from tag v0.9.6) and bedrock (cloned from tag v1.5.3). The only changes made after cloning was to change wordpress_sites and vault for the development environment.

On `vagrant provision` I'm getting this error

> TASK [composer : Run Composer installer.] **************************************
> fatal: [default]: FAILED! => {"changed": true, "cmd": ["php", "composer-installer.php"], "delta": "0:00:00.426234", "end": "2016-02-23 13:54:54.627804", "failed": true, "rc": 255, "start": "2016-02-23 13:54:54.201570", "stderr": "PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo_mysql.so' - /usr/lib/php/20151012/pdo_mysql.so: undefined symbol: mysqlnd_allocator in Unknown on line 0\nPHP Warning:  Cannot load module 'mysqli' because required module 'mysqlnd' is not loaded in Unknown on line 0\nPHP Fatal error:  Uncaught Error: Class 'Phar' not found in /tmp/composer-installer.php:505\nStack trace:\n#0 /tmp/composer-installer.php(111): installComposer(false, '/tmp', 'composer.phar', false, false, false)\n#1 /tmp/composer-installer.php(13): process(Array)\n#2 {main}\n  thrown in /tmp/composer-installer.php on line 505", "stdout": "All settings correct for using Composer\nDownloading...", "stdout_lines": ["All settings correct for using Composer", "Downloading..."], "warnings": []}

Running with `-vvvv` doesn't give any extra information.
If I ssh into the box and run `php -v`

> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo_mysql.so' - /usr/lib/php/20151012/pdo_mysql.so: undefined symbol: mysqlnd_allocator in Unknown on line 0
> PHP Warning:  Cannot load module 'mysqli' because required module 'mysqlnd' is not loaded in Unknown on line 0
> PHP 7.0.3-7+deb.sury.org~trusty+1 (cli) ( NTS )

I also tried the master branch of trellis, same issue. I'm not sure what other information I can provide at this point, please let me know if you need any more than this.

My best guess is that where trellis has switched over to php7.0 there is no longer a mysqlnd package available. I'm afraid I don't know enough about installing mysql or php to fix this myself.

Thanks!

**Comment by chrisnx** [comment]
I'm going attempt a git bisect and see if I can find at what point the issue appeared, as I didn't have any problems with v0.4.0

**Comment by chrisnx** [comment]
Oh - this is my environment if that helps at all.
ansible 2.0.0.2
virtualbox 4.3.10
Vagrant 1.7.2

**Comment by retlehs** [comment]
as stated in our contributing guidelines (that are linked at the top when you go to create a new issue), please don't use github issues for personal support requests.

https://discourse.roots.io/

**Comment by chrisnx** [comment]
I read the guidelines, but wasn't sure this was a personal issue. My apologies for the misunderstanding!

**Comment by swalkinshaw** [comment]
Just to quickly chime in: I've never seen this particular error and Trellis 0.9.6 and master are both working out of the box. I don't have any guesses on what would cause it either :(

**Comment by austinpray** [comment]
What version of the Ubuntu vagrant box are you on?
