### ISSUE TITLE
add ansible *.retry files to .gitignore

### ISSUE THREAD

**Issue by ak5** [roots/trellis#505]
Hi!

First off, thanks for bringing WP into the present, I've been struggling to do so myself for a while now and just stumbled upon your projects - setting up a site with the trellis, bedrock and sage at this moment. I'm impressed by the amounts of features!

This issue is a small nitpick, living in China we have pretty crappy internet and I always end up having .retry files in my repo. Would be nice to have them in .gitignore. That is all.

---

add to .gitignore
```
*.retry
```

**Comment by swalkinshaw** [comment]
We'll consider this but in the meantime you can turn them off in your `ansible.cfg` confg: http://stackoverflow.com/questions/31318881/how-do-you-stop-ansible-from-creating-retry-files-in-the-home-directory
