### ISSUE TITLE
Ansible v2.0.1.0 is not working with Trellis

### ISSUE THREAD

**Issue by brazabr** [roots/trellis#506]
The documentation says I can use Ansible >= v2.0.0.2, but when I try to provision my development environment using ansible v2.0.1.0 I receive the following error:

> ERROR! The requested action was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem.
> 
> The error appears to have been in '/home/brazabr/roots-example-project.com/trellis/roles/common/tasks/main.yml': line 2, column 3, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> \-\-\-
> \- name: Validate Ansible version
>   ^ here
> 
> Ansible failed to complete successfully. Any error output should be
> visible above. Please fix these errors and try again.

If I downgrade ansible to v2.0.0.2 it works fine.

I am installing ansible using pip.
Running on Ubuntu 14.04.1 x86_64.

**Comment by swalkinshaw** [comment]
How did you install 2.0.1? I just upgraded my version via `pip` and it's working fine.

**Comment by brazabr** [comment]
I tried to install it via apt-get using the PPA. Without success, I removed i, cleaned unnecessary packages and removed the PPA. Then I tried installing it via `pip`. Same results. I then uninstalled it via `pip`.

I decided to try version 1.9.4 via `pip`, but then I got a lost dependency error on `ansible.compat.six.string_types`. I removed it again and tried the 2.0.0.2 via `pip` and it worked.

**Comment by swalkinshaw** [comment]
I'm not exactly sure what the solution is for you, but this isn't a Trellis issue. We've had a few people all try this and 2.0.1 works just fine if it's installed correctly.

If Ansible doesn't even detect its own core modules then something is wrong with the install.
