### ISSUE TITLE
Nginx reload silently fails if key is invalid

### ISSUE THREAD

**Issue by spencerbeggs** [roots/trellis#507]
I was troubleshooting a Trellis deployment that never seemed to take despite successfully going through all the deployment steps. All the Nginx confs were being created but I was still seeing the default site (the default site conf was not linked in sites-enabled). Finally, I ssh'd into the box and tested the confs with:

`
sudo nginx -t
`

And received this response:

`
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/nginx/ssl/privkey.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: ANY PRIVATE KEY error:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib)
nginx: configuration file /etc/nginx/nginx.conf test failed
`

The problem was that there were incorrect line encodings in the key file. If I stopped and tried to restart Ngnix, the server wouldn't come back up. It seems to me that Trellis should fail if it is unable to restart Ngninx. Perhaps it's worth running the conf test command to ensure that SSL certs are installed properly.

**Comment by swalkinshaw** [comment]
:+1: I think that's a good idea to run the conf test and fail with a nicer message if it errors.

**Comment by swalkinshaw** [comment]
This was added during Let's Encrypt integration. We run Nginx config tests at a few points such as here: https://github.com/roots/trellis/blob/fefb73f20f2923050fc0fc956897038d0567f4d7/roles/wordpress-setup/tasks/nginx.yml#L66-L68
