### ISSUE TITLE
DNS resolution issues if multisite is configured

### ISSUE THREAD

**Issue by o1y** [roots/trellis#511]
VirtualBox cannot resolve hostnames if a multisite setup is configured as described in the [docs](https://roots.io/trellis/docs/multisite/). Provisioning fails with

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

apt-get install -y bindfs

Stdout from the command:

Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  bindfs
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 25.1 kB of archives.
After this operation, 89.1 kB of additional disk space will be used.
Err http://archive.ubuntu.com/ubuntu/ trusty/universe bindfs amd64 1.12.3-1
  Could not resolve 'archive.ubuntu.com'
```

Adding `config.landrush.guest_redirect_dns = false` to the Vagrantfile temporary fix the issue, as described in the landrush [docs](https://github.com/phinze/landrush#visibility-on-the-guest). But I think this is just a workaround which solves not the cause of the problem. Any ideas?

**Comment by retlehs** [comment]
the error msg you provided seems unrelated to anything multisite related...

> Could not resolve 'archive.ubuntu.com'

did you try again? seems like a connectivity problem

**Comment by o1y** [comment]
DNS resolution won't work only if a multisite is configured with landrush. archive.ubuntu.com is up and I can ping the server ip from the virtual machine without any problems:

```
vagrant@roots-example-project:~$ dig google.de

; <<>> DiG 9.9.5-3ubuntu0.7-Ubuntu <<>> google.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 56609
;; flags: qr aa rd; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; Query time: 31 msec
;; SERVER: 10.0.2.3#53(10.0.2.3)
;; WHEN: Mon Mar 07 13:53:41 UTC 2016
;; MSG SIZE  rcvd: 12

vagrant@roots-example-project:~$ dig archive.ubuntu.com

; <<>> DiG 9.9.5-3ubuntu0.7-Ubuntu <<>> archive.ubuntu.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 7967
;; flags: qr aa rd; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; Query time: 4 msec
;; SERVER: 10.0.2.3#53(10.0.2.3)
;; WHEN: Mon Mar 07 13:59:44 UTC 2016
;; MSG SIZE  rcvd: 12
```

```
vagrant@roots-example-project:~$ ping 91.189.91.13
PING 91.189.91.13 (91.189.91.13) 56(84) bytes of data.
64 bytes from 91.189.91.13: icmp_seq=1 ttl=63 time=115 ms
64 bytes from 91.189.91.13: icmp_seq=2 ttl=63 time=146 ms
64 bytes from 91.189.91.13: icmp_seq=3 ttl=63 time=127 ms
64 bytes from 91.189.91.13: icmp_seq=4 ttl=63 time=149 ms
```


I used a clean roots-example-project, and followed the multisite [instructions](https://roots.io/trellis/docs/multisite/). This is the only part I changed in the Vagrantfile

```
  if Vagrant.has_plugin? 'landrush'
    config.landrush.enabled = true
    config.landrush.tld = config.vm.hostname

    aliases.each do |host|
      config.landrush.host host, ip
    end
  else
    fail_with_message "landrush missing, please install the plugin with this command:\nvagrant plugin install landrush"
  end
```

**Comment by working-name** [comment]
@o1y I'm dealing with the same issue on Sierra 10.12.2 as host. **My workaround** is to quickly `vagrant ssh` while it is waiting to get bindfs, and `sudo nano /etc/resolv.conf` to replace whatever is there with 8.8.8.8 or your favorite DNS server.

I have tried every combination of the following to no avail (these are in your `Vagrantfile`):
```
config.vm.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
config.vm.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
config.vm.customize ["modifyvm", :id, "--natdnspassdomain1", "off"]
```

**Comment by maiorano84** [comment]
Chiming in here, since I ran into the same issue with Multisite and Landrush installed. I came across this discussion that helped workaround the problem:

https://discourse.roots.io/t/trellis-multisite-fresh-development-setup-not-working-at-all/7911/2

Adding `config.landrush.guest_redirect_dns = false` to the Trellis Vagrant file fixed the issue for me as well.

    elsif Vagrant.has_plugin?('landrush') && multisite_subdomains?(wordpress_sites)
        config.landrush.enabled = true
        config.landrush.tld = config.vm.hostname
        config.landrush.guest_redirect_dns = false # This line fixes the DNS error
        hostnames.each { |host| config.landrush.host host, ip }

This leads me to believe that some networks don't play as nicely with Landrush. [This is a known issue](https://github.com/vagrant-landrush/landrush/blob/master/doc/Troubleshooting.adoc#guest-is-unable-to-access-the-internet) that has more to do with network settings itself than Landrush or Trellis. This above fix is probably the most appropriate.

I would suggest highlighting it in the docs, or even making it a part of the Trellis Vagrantfile.

**Comment by swalkinshaw** [comment]
I'd be fine adding `config.landrush.guest_redirect_dns = false` to the `Vagrantfile` by default but I don't really know enough about it. It seems according to Landrush docs that this should only be done if something isn't working?

**Comment by maiorano84** [comment]
I would highlight it in the docs, first. I haven't seen too many people talking about it, so my guess is that this is affecting only a small number of people whose network firewall configurations are preventing Landrush from making outbound requests.

I'll keep an eye on my own local installation to see if there are any unintended consequences, but so far I haven't see anything.

**Comment by swalkinshaw** [comment]
Would you mind doing a PR over here https://github.com/roots/docs with a mention of it? You probably know more about it than me :)

**Comment by swalkinshaw** [comment]
Added a note to docs: https://github.com/roots/docs/commit/495f0d8ab3ea666dead59eb0c799230a1881679e
