### ISSUE TITLE
Nginx included templates broken on Ansible 2.x

### ISSUE THREAD

**Issue by swalkinshaw** [roots/trellis#517]
Task: https://github.com/roots/trellis/blob/c3f6822e6d05457be6a9fe308688ad3c90f7f38d/roles/wordpress-setup/tasks/nginx.yml#L26-L32

Looks like Ansible changed how it runs tasks in 2.x. I believe `cd {{ role_path }}/templates/includes.d` is not run on the *remote* host instead of locally which results in this:

```plain
TASK [wordpress-setup : Template files out to includes.d] **********************
/bin/sh: line 0: cd: /Users/scott/dev/trellis/roles/wordpress-setup/templates/includes.d: No such file or directory
```

**Comment by swalkinshaw** [comment]
Can't reproduce

**Comment by wassimdotis** [comment]
Could we reopen this? I'm getting the same error locally with Ansible 2.1.2.0

**Comment by fullyint** [comment]
@wassimdotis I'm testing a fix and plan to post a PR in the next 48 hours.
