### ISSUE TITLE
Problems with the defaults since #533

### ISSUE THREAD

**Issue by fredriksundstrom** [roots/trellis#535]
Hey!

I'm having all sorts of issues with the defaults since PR #533.

Mainly it gets stuck on trying a multisite-install, even though I've got it set to false. It complains about the subdomains option not set. When I set it, it complains about the admin_pass.

That's how far I got until I had to move on. But clearly, something's off. When going back to #534 everything is fine.

`TASK [wordpress-setup : Create WordPress configuration for Nginx] **************
failed: [default] => (item={'value': {u'multisite': {u'enabled': False}, u'cache': {u'enabled': False}, u'ssl': {u'enabled': False, u'provider': u'self-signed'}, u'local_path': u'../site', u'site_hosts': [u'dalatrafik-traffic.dev'], u'admin_email': u'admin@dalatrafik-traffic.dev'}, 'key': u'information.dalatrafik.se'}) => {"failed": true, "item": {"key": "information.dalatrafik.se", "value": {"admin_email": "admin@dalatrafik-traffic.dev", "cache": {"enabled": false}, "local_path": "../site", "multisite": {"enabled": false}, "site_hosts": ["dalatrafik-traffic.dev"], "ssl": {"enabled": false, "provider": "self-signed"}}}, "msg": "AnsibleUndefinedVariable: ERROR! 'dict object' has no attribute 'subdomains'"}`

**Comment by swalkinshaw** [comment]
Sorry about that, missed a default. For now you can just re-add `subdomains: false` under `multisite` for your site and it will work again. I'll add a proper fix soon.

**Comment by fredriksundstrom** [comment]
No worries and thank you!

I hopped back a few commits. Did you see the part on other missing defaults showing up, though?

My hunch at the time was, also, that even though I had multisite: false, it tried to install as multisite. Maybe I should have been clearer on that, but I had nothing but the default wordpress_site.yml.

So, multisite: false, still gave that error. But perhaps that is normal and will be fixed, also, by adding that default. :)

**Comment by swalkinshaw** [comment]
Hoping it was `admin_user` that gave you the error since I could replicate that.

Fixed in fc44e94d6f174792b00833d79a89dd92d4b1daf8
