### ISSUE TITLE
Fresh installation w/ Bedrock. Scripts and stylesheets sent as text/html

### ISSUE THREAD

**Issue by aaroneaton** [roots/trellis#54]
Let me know if this is a Bedrock-only issue and I'll move this over to that repo.

Just installed this along with Bedrock and the installation seemed to go just fine. When I visited the site I got an unstyled site along with the following errors:
![developer_tools_-_http___docs_channeleaton_dev__p_1_and_new_issue_ _roots_bedrock-ansible](https://cloud.githubusercontent.com/assets/128851/4291213/8b7c7ede-3dc2-11e4-982f-1eb76a0cee34.png)

In addition, I get redirected back to the home page when going to wp-admin and wp-login.php throws a 404.

None of the configurations have been changed.

**Comment by cam5** [comment]
I did the same thing. Being overenthusiastic, I removed /wp from the site_url
