### ISSUE TITLE
Setup Permalink Structure Task Failing for WordPress Installations using Multisite

### ISSUE THREAD

**Issue by richvida** [roots/trellis#550]
**Here's an active Discourse describing the same issue**: [Multisite - database error on vagrant up](https://discourse.roots.io/t/multisite-database-error-on-vagrant-up/6350)

My Vagrant development environment, which consists of 3 websites (1 Multisite, 2 non-Multisite), is failing at `TASK [wordpress-install : Setup Permalink Structure]` with error:

    WordPress database error Table 'site1_development.wp_blogs' doesn't exist for query SELECT * FROM wp_blogs WHERE domain = 'site1.dev' AND path = '/' made by include('phar:///usr/bin/wp/php/boot-phar.php'), include('phar:///usr/bin/wp/php/wp-cli.php'), WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('phar:///usr/bin/wp/php/wp-settings- cli.php'), require('wp-includes/ms-settings.php'), get_site_by_path Error: Site site1.dev/ not found. failed: [default] => (item=site1) => {"changed": true, "cmd": ["wp", "rewrite", "structure", "/%postname%/", "--allow-root"], "delta": "0:00:00.096019", "end": "2016-04-05 20:16:15.394469", "failed": true, "item": "site1", "rc": 1, "start": "2016-04-05 20:16:15.298450", "stderr": "WordPress database error Table 'site1_development.wp_blogs' doesn't exist for query SELECT * FROM wp_blogs WHERE domain = 'site1.dev' AND path = '/' made by include('phar:///usr/bin/wp/php/boot-phar.php'), include('phar:///usr/bin/wp/php/wp-cli.php'), WP_CLI\\Runner->start, WP_CLI\\Runner->load_wordpress, require('phar:///usr/bin/wp/php/wp-settings-cli.php'), require('wp-includes/ms-settings.php'), get_site_by_path\nError: Site site1.dev/ not found.", "stdout": "", "stdout_lines": [], "warnings": []}
    ---------------------------------------------------
    changed: [default] => (item=site2)
    changed: [default] => (item=site3)

when running `vagrant up` for the first time.

Loading *site1.dev* a web browser results in this:

    Error establishing a database connection 

**group_vars/development/wordpress_sites.yml**:

    wordpress_sites:

      site1:
        site_hosts:
          - site1.dev
        local_path: ../site1
        admin_email: admin@site1.dev
        multisite:
          enabled: true
          subdomain: false
        ssl:
          enabled: false
          provider: self-signed
        cache:
          enabled: false
        env:
          domain_current_site: site1.dev

      site2:
        site_hosts:
          - site2.dev
        local_path: ../site2
        admin_email: admin@site2.dev
        multisite:
          enabled: false
        ssl:
          enabled: false
          provider: self-signed
        cache:
          enabled: false

      site3:
        site_hosts:
          - site3.dev
        local_path: ../site3
        admin_email: admin@site3.dev
        multisite:
          enabled: false
        ssl:
          enabled: false
          provider: self-signed
        cache:
          enabled: false

**Comment by swalkinshaw** [comment]
Thanks, got a proper fix here: https://github.com/roots/trellis/pull/551

**Comment by richvida** [comment]
Starting from a fresh VM I'm still getting this error when viewing _site1.dev_

    Error establishing a database connection

But Trellis/Ansible provisioned the server without error!

**Comment by swalkinshaw** [comment]
@richvida that's an unrelated problem. I figured out what was wrong and added some more to our docs: https://roots.io/trellis/docs/multisite/

You need to set `wp_home` and `wp_siteurl`.

**Comment by inorbita** [comment]
I've applied the latest Trellis fixes and added wp_home and wp_siteurl, but now I receive this error:

```
TASK [wordpress-setup : Create database of sites] ******************************
'dict object' has no attribute 'ssl'
fatal: [default]: FAILED! => {"failed": true}
```

Not sure if something went wrong on my end while updating Trellis, or if it's still a bug.
