### ISSUE TITLE
the ssh command responded with a non-zero exit status

### ISSUE THREAD

**Issue by TheAggressive** [roots/trellis#553]
I keep getting this every time I `vagrant up ` even `vagrant provision`

Thank you for any help

**Comment by austinpray** [comment]
Not really enough information here to reproduce. Try and get it sorted over on http://discourse.roots.io. If we can reproduce the issue there then we will log it here as a bug.

**Comment by TheAggressive** [comment]
This is the error that it looks like it outputs durring installing

`==> default: TASK [wordpress-setup : Create database of sites] ******************************
==> default: 'dict object' has no attribute u'theaggressive.com'
==> default: fatal: [192.168.50.5]: FAILED! => {"failed": true}
`

**Comment by retlehs** [comment]
https://discourse.roots.io/search?q=%27dict%20object%27%20has%20no%20attribute%20

**Comment by swalkinshaw** [comment]
Also see the docs: https://roots.io/trellis/docs/wordpress-sites/#passwords-secrets
