### ISSUE TITLE
Trying to get up vagrant

### ISSUE THREAD

**Issue by ecolasurdo** [roots/trellis#557]
Error after running:

`vagran up`

> Vagrant failed to initialize at a very early stage:
> 
> There was an error loading a Vagrantfile. The file being loaded
> and the error message are shown below. This is usually caused by
> a syntax error.
> 
> Path: /home/theUser/mydomain.com/trellis/Vagrantfile
> Message: undefined local variable or method `__dir__' for main:Object

Im using ruby 2.2.1.

**Comment by retlehs** [comment]
please use https://discourse.roots.io/ for personal support requests
