### ISSUE TITLE
Multisite subdomain server_name nginx

### ISSUE THREAD

**Issue by twinleafdev** [roots/trellis#572]
## Submit a feature request or bug report

- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

When multisite: true and subdomain: true server_name in, etc/nginx/sites-enabled/example.com.conf, is being set to:
`
server_name example.com
`

**What is the expected or desired behavior?**

server_name in etc/nginx/sites-enabled/example.com.conf should be set to:
`server_name example.com *.example.com`

This solved the issue for me:
https://github.com/twinleafdev/trellis/commit/12ad7120420376d101f8bc056c07b7854e7d71b2

**Comment by twinleafdev** [comment]
Or perhaps update the [docs](https://roots.io/trellis/docs/multisite/) to  subdomain**s**: false

**Comment by swalkinshaw** [comment]
Docs have been updated: https://github.com/roots/docs/commit/ce8e5508ef49a947ec167e4052a5cd7b2fa99e19

Thanks
