### ISSUE TITLE
Switch to a different TLD than .dev

### ISSUE THREAD

**Issue by bostondv** [roots/trellis#580]
- [X] This is a feature request
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

---

**What is the current behavior?**

When using a subdomain multisite with landrush and a `.dev` url Chrome 50 complains about ICANN name collisions and does not load the page.

**What is the expected or desired behavior?**

The page should load using the Trellis default TLD in development.
## Feature Request

As `.dev` is one of the new gTLDs introduced by ICANN and causing name collisions, changing the example configs in Trellis to an extension that ICANN will not delegate might be a good idea. I propose `.test` since its short and reserved as "never to be used as official TLD" via [RFC2606](https://tools.ietf.org/html/rfc2606#section-2).

There is a thread related to this issue in the Landrush repo: https://github.com/vagrant-landrush/landrush/issues/118

**Comment by mAAdhaTTah** [comment]
Wait, seriously? They made `.dev` a real TLD?

**Comment by retlehs** [comment]
what's in your hosts file? on chrome 50 i'm able to use `.dev` without any issues

not to say we're not open to switching to something such as `.test`, just curious as to what's going on with your chrome

**Comment by swalkinshaw** [comment]
Yeah, just to be clear: your local `/etc/hosts` file overrides everything else. You can override a `.com` as well. It doesn't matter if it's a real domain, real TLD, whatever.

**Comment by QWp6t** [comment]
Oh cool. Just purchase `.dev` domain and point it at `192.168.x.x`, avoid hosts file iirc :trollface:

**Comment by bostondv** [comment]
Putting the domain in the hosts file works fine for me as well. The problem I have really is when running a subdomain multisite network with landrush. Landrush doesn't seem to overcome the name collision and I'd rather not have to put a host entry for every subdomain in the multisite network :)

**Comment by RiFi2k** [comment]
On chrome version 53 I get the collision message, same for 55 (unstable/dev)

Is this something you all are still interested in getting done?

Personally I use .local

**Comment by iamjoshellis** [comment]
I think Apple uses .local for bonjour services on OSX, which could cause potential conflicts.
https://support.apple.com/en-gb/HT203136

**Comment by RiFi2k** [comment]
Good call, I don't use OSX so I didn't have any clue about that.

**Comment by scherii** [comment]
I think [`.test`](https://tools.ietf.org/html/rfc2606#section-2) is the best available option.

Others (like `.localhost` or `.local`) all have some sort of conflict.

**Comment by iamjoshellis** [comment]
Yea, I'd agree with `.test`

**Comment by pixeline** [comment]
We use `*.loc`

**Comment by QWp6t** [comment]
You're free to use whatever TLD you want. We'll stick with `.dev` in our examples for now.

**Comment by retlehs** [comment]
reopened because of https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/
