### ISSUE TITLE
Cant create a site with å,ä or ö (Swedish chars) in url 

### ISSUE THREAD

**Issue by therealkristoffer** [roots/trellis#589]
## Submit a feature request or bug report

- [ ] This is a feature request
- [X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [ ] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**
When i try to deploy lidingonaprapaterna (./deploy.sh command) with this setup (wordpress_sites.yml):
``` lidingonaprapaterna:
    site_hosts:
      - "lidingönaprapaterna.se"
      - lidingonaprapaterna.se
      - lidingonaprapaterna.com
    local_path: ../lidingonaprapaterna # path targeting local Bedrock site directory (relative to Ansible root)
    theme: lidingonapprapaterna
    repo: git@bitbucket.org:webnerds/lidingonaprapaterna.git
    branch: master
    # repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo (above) if it is not the root (like the roots-example-project structure)
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: "http://lidingönaprapaterna.se"
      wp_siteurl: "http://lidingönaprapaterna.se/wp"
      wp_env: production
      db_name: lidingonap_prod
      db_user: lidingonap_dbuser
      # Define the following variables in group_vars/production/vault.yml
      # db_password:
      # auth_key:
      # secure_auth_key:
      # logged_in_key:
      # nonce_key:
      # auth_salt:
      # secure_auth_salt:
      # logged_in_salt:
      # nonce_salt:
```
I get this error:
`UnicodeEncodeError: 'ascii' codec can't encode character u'\\xf6' in position 6: ordinal not in range(128)`

**What is the expected or desired behavior?**

I would like to be able to publish sites with special characters in the url. 

---

## Bug report

**Please describe your local environment:**

Ansible version: ansible 2.0.2.0

OS: Local: OSX 10.11.3, remote: Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-45-generic x86_64)

Vagrant version: Vagrant 1.8.1

**Where did the bug happen? Development or remote servers?**
Remote server

**Please provide a repository or your `wordpress_sites` config (if possible):**
See above.

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

https://discourse.roots.io/t/cant-create-a-site-with-a-a-or-o-swedish-chars-in-url/6838

**Comment by swalkinshaw** [comment]
Thanks for reporting this. Got a PR up here: https://github.com/roots/trellis/pull/590. You can update that manually to try it out before I merge if you want.

**Comment by therealkristoffer** [comment]
@swalkinshaw awesome! Thanks. And how would i go about do the update manually in the best manner? Sry, quiet new to git. :/

**Comment by CFXd** [comment]
Make the red part look like the green part in this file: https://github.com/roots/trellis/pull/590/files 👍🏻
