### ISSUE TITLE
vagrant-hostmanager is missing

### ISSUE THREAD

**Issue by hintings** [roots/trellis#603]
## Submit a feature request or bug report

- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X ] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

When I type into my Terminal `vagrant up`, it will echo a red error message, `vagrant-hostmanager is missing`.

**What is the expected or desired behavior?**

It should not give an error.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

I've simply followed the instructions in the docs: https://roots.io/trellis/docs/installing-trellis/

**Please describe your local environment:**

Ansible version: 2.1.0.0

OS: Ubuntu Desktop 16.04 64bit

Vagrant version: 1.8.1

**Where did the bug happen? Development or remote servers?**

I wrote `vagrant up` in the trellis root directory where the VagrantFile is located.

**Comment by swalkinshaw** [comment]
So you get this helpful error message:

> vagrant-hostmanager missing, please install the plugin with this command:
vagrant plugin install vagrant-hostmanager

It tells you exactly what to do. Install the plugin by running this command: `vagrant plugin install vagrant-hostmanager`

**Comment by hintings** [comment]
@swalkinshaw I have done that already, it's part of trellis install instructions in the docs. 
I also tried that again when I received the error message.

Please, open the issue again.

**Comment by retlehs** [comment]
please don't use github for personal support.

**Comment by hintings** [comment]
@retlehs Why do say that it's personal support? It's an issue with Trellis

**Comment by swalkinshaw** [comment]
Trellis docs list all the requirements needed as the very first thing: https://roots.io/trellis/docs/installing-trellis/. vagrant-hostmanager is in that list.

You're also using an incompatible version of Ansible. Our docs contain the required version.

**Comment by hintings** [comment]
The Ansible version wasn't the problem. 
I don't remember how I installed Vagrant anymore but it turned out that I needed v1.8.4
I also had to `sudo apt-get install nfs-common nfs-kernel-server`

**Comment by swalkinshaw** [comment]
@hintings we've had problems with 1.8.4 and even recommend 1.8.1 and less now. Maybe you just needed to re-install Vagrant.

**Comment by hintings** [comment]
@swalkinshaw well, that's really weird! Because I wasn't able to install any vagrant plugins until I updated to vagrant 1.8.4 instead of 1.8.1.

**Comment by QWp6t** [comment]
This isn't a Trellis issue. You should take this to the forums or report it upstream to the Vagrant guys if you think it's a bug with Vagrant. Regardless, it's not a bug on our end.
