### ISSUE TITLE
 Mounting NFS shared folders timeout error on vagrant up

### ISSUE THREAD

**Issue by hintings** [roots/trellis#610]
## Submit a feature request or bug report

- [X ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X ] This is a bug report
- [ X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [ X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

When I vagrant up then I get a timeout error when mounting NFS shared folders.

`==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' XXX.XXX.XX.X:'/home/hintings/Projects/hintings.com/site' /vagrant-nfs-example.com

Stdout from the command:

Stderr from the command:

mount.nfs: Connection timed out`

I x'ed out the IP for privacy

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

I have followed the installation setup steps from the Trello docs that includes these three pages:
https://roots.io/trellis/docs/installing-trellis/ and https://roots.io/trellis/docs/wordpress-sites/ and https://roots.io/trellis/docs/local-development-setup/

**Please describe your local environment:**

Ansible version: 2.0.2.0

OS: Ubuntu Desktop 16.04 64bit

Vagrant version: 1.8.1

**Where did the bug happen? Development or remote servers?**

Development

**Please provide a repository or your `wordpress_sites` config (if possible):**

X

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

`wordpress_sites:

  hintings.com:

    site_hosts:

      - hintings.dev

    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)

    admin_user: Hintings

    admin_email: hintings@hintings.com

    multisite:

      enabled: false

    ssl:

      enabled: false

      provider: self-signed

    cache:

      enabled: false`

In the real file there are no empty lines between each text line.. Just had some problems with formatting when pasting it into here.

**Comment by retlehs** [comment]
1. this is not a trellis specific error.

2. [you've already been asked once to not use issues for personal support requests](https://github.com/roots/trellis/issues/603).

3. you already posted this on our discourse. i'm assuming you created this issue because you haven't received help there yet? please don't do that.

if you search google for the error message you've provided there's a lot of results.
