### ISSUE TITLE
Updating development from production

### ISSUE THREAD

**Issue by silverbux** [roots/trellis#618]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

everything is fine and working properly, for this i thank you.

**What is the expected or desired behavior?**

right now contributors/writers are uploading and writing contents on **production**. and i want to update our **development** environment, what is the proper way to do this? and as much as possible i would want to use GIT just so we could track changes and history.

**Comment by QWp6t** [comment]
https://discourse.roots.io/c/trellis
