### ISSUE TITLE
windows.sh. Failing to fetch archives without apt-get update when installing Ansible on VM

### ISSUE THREAD

**Issue by cadros** [roots/trellis#621]
- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x]  This is a feature request
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

---

**What is the current behavior?**

vagrant up aborts with
`pip: command not found`
due to 
`Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/p/python-pip/`

**Please provide steps to reproduce, including full log output:**

On Windows host
`vagrant up`

**Please describe your local environment:**

Ansible version: '2.0.2.0' (on VM)
OS: Windows
Vagrant version: 1.8.4

**Where did the bug happen? Development or remote servers?**
dev

---

**Please provide use cases for changing the current behavior:**

(I switched to Windows only lately), so not exactly sure why the `apt-get update` line was removed. After adding it back to windows.sh Ansible gets installed smoothly
```
if [ ! -f /usr/bin/ansible ]; then
  + sudo apt-get -y update
  echo "Installing pip..."
.....
```

**Comment by swalkinshaw** [comment]
Looks like this was a regression in https://github.com/roots/trellis/pull/613.

Do you want to do the PR to re-add it?

**Comment by cadros** [comment]
Sure, anything to make windows users' life easier. How do I better describe it, the message?

**Comment by swalkinshaw** [comment]
Doesn't matter too much but something like "Re-add apt update to windows.sh`

**Comment by TheAggressive** [comment]
I'm also having this issue. What is needed to correct?

**Comment by cadros** [comment]
TheAggressive, sorry, didn't make it today (it's night where i am), will PR for re-adding the `sudo apt-get -y update` line tomorrow

meanwhile i guess you could just temporarily add it manually back to windows.sh file right before the point where it installs the pip

**Comment by TheAggressive** [comment]
OK I'll try that and report back!

**Comment by TheAggressive** [comment]
Thanks @cadros that fixed the issue.

I went a head and submitted the pull request for you to avoid any issues from cloning in the future. PR is here - #623
