### ISSUE TITLE
Deploys using identical IP and different SSH ports not working as expected

### ISSUE THREAD

**Issue by nathanielks** [roots/trellis#625]
**What is the current behavior?**

When using multiple environments, and those environments are on the same IP but use a different port to ssh to a different environment, an incorrect host may be chosen (I'm still trying to determine how ansible chooses the host).

For example:

```
# hosts/staging
[web]
12.23.34.56 ansible_ssh_port=23456

[production]
12.23.34.56 ansible_ssh_port=23456
```

```
# hosts/production
[web]
12.23.34.56 ansible_ssh_port=12345

[production]
12.23.34.56 ansible_ssh_port=12345
```

```
./deploy.sh production example.com
```

Instead of using `production`'s values, `staging`'s are used instead. These are the same as mine in that the IP is the same and the ports are different, with `staging`'s ports being higher than `production`'s. I thought perhaps because the port numbers were higher, `staging` was being prioritized over `production`, so I tried switching the two and still the `staging` hosts file is being used instead of `production`'s.

**What is the expected or desired behavior?**

Ansible would select the correct environment and hosts to deploy to.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

- Have 2 host files, one named `production` and the other `staging`, with the hosts sharing the same IP address, but use different ports to ssh into.
- Run a deploy to production.
- The staging port will be selected.

**Please describe your local environment:**

Ansible version: 2.0.2.0

OS: 10.10.5

Vagrant version: 1.8.1

**Where did the bug happen? Development or remote servers?**

Locally

**Please provide a repository or your `wordpress_sites` config (if possible):**

N/A

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

Nope!

**Comment by nathanielks** [comment]
I believe this is occurring because Ansible loads all the hosts and then parses them out by combining the two groups, `web` and whatever the environment is, but because the `web` is using the same ip address, I actually wonder if this is a bug in ansible itself. Do you have any insight @fullyint?

**Comment by fullyint** [comment]
I believe the options listed at this forum discussion may be relevant:
https://discourse.roots.io/t/production-server-provision-configures-staging-envs-if-hosts-are-the-same-bug-or-intention/6090/2

**Comment by nathanielks** [comment]
(I think ansible doesn't ip addresses with different ssh ports as unique hosts, I think it's treating them as the same and grabbing whichever one is on top)

**Comment by nathanielks** [comment]
herp derp, thanks @fullyint!
