### ISSUE TITLE
Nginx fails to restart

### ISSUE THREAD

**Issue by gchaincl** [roots/trellis#633]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

---

**What is the current behavior?**

Nginx fails to restart

**What is the expected or desired behavior?**

Nginx should be restarted

---

## Bug report

**Please provide steps to reproduce, including full log output:**

```
TASK [wordpress-setup : Setup WP system cron] **********************************
ok: [www.webmdhealthservices.com] => (item=www.webmdhealthservices.com)

RUNNING HANDLER [common : reload nginx] ****************************************
System info:
  Ansible 2.1.1.0; Linux
  Trellis at "Upgrade Ubuntu from 14.04 Trusty to 16.04 Xenial"
---------------------------------------------------
The conditional check 'nginx_test | success' failed. The error was: |failed
expects a dictionary

The error appears to have been in '/home/gchain/dev/webmd/webmd.com/ansible/r
oles/common/tasks/reload_nginx.yml': line 7, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: reload nginx
  ^ here

fatal: [www.webmdhealthservices.com]: FAILED! => {"failed": true}

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'server.retry'.         [Errno 2] No such file or directory: ''

```

**Please describe your local environment:**

Ansible version: 2.1.1.0

OS: Ubuntu 14 LTS.

**Where did the bug happen? Development or remote servers?**

Remote production server

**Comment by fullyint** [comment]
Please see if applying the update in #631 will fix this for you.

**Comment by gchaincl** [comment]
that was fast, and it worked, thanks!
