### ISSUE TITLE
Composer extremely slow on provision

### ISSUE THREAD

**Issue by cibulka** [roots/trellis#635]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

---

**What is the current behavior?**

I experience quite a few problems with Composer on `vagrant reload --provision` which I haven't before. Those are some of notices I received:

```
You are running composer with xdebug enabled. This has a major impact on
runtime performance. See https://getcomposer.org/xdebug
```

```
Do not run Composer as root/super user! See https://getcomposer.org/root for
details
```

```
 Failed to download squizlabs/php_codesniffer from source: The process
"git clone --no-checkout 'https://github.com/squizlabs/PHP_CodeSniffer.git'
'/srv/www/divnamista.dev/current/vendor/squizlabs/php_codesniffer' && cd
'/srv/www/divnamista.dev/current/vendor/squizlabs/php_codesniffer' && git
remote add composer 'https://github.com/squizlabs/PHP_CodeSniffer.git' && git
fetch composer" exceeded the timeout of 300 seconds.
```

```
Could not delete /srv/www/divnamista.dev/current/vendor/squizlabs/php_codes
niffer/.git/objects/pack:
```

Besides the notices, the whole process is extremely slow (current try just exceeded 20 minutes). Could you help me debug where the cause might be?

Also, it's been a while since I added new project to my dev, so I updated a lot of stuff (Trellis, Vagrant, Ansible, ...), so that might be related.

This - https://github.com/composer/composer/issues/1787 - seem to be relevant no more.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

`vagrant reload --provision`

**Please describe your local environment:**

Ansible version: 2.0.2.0

OS: OSX 10.11.6

Vagrant version: 1.8.5

**Where did the bug happen? Development or remote servers?**

Development

--

Thanks in advance!

**Comment by cibulka** [comment]
Weirdly enough, when I'm trying to run Composer locally, it hangs also on cloning squizlabs/php_codesniffer:

```
  - Installing squizlabs/php_codesniffer (dev-master 71945d9)
    Cloning 71945d90d2735aa7cc466aa099674d011ee6ad17
```

Could that be related in any way? 

Here is my Composer.json, if that helps in any way: https://gist.github.com/cibulka/167194786221953c3d2dab66484420d3

**Comment by swalkinshaw** [comment]
20 minutes is crazy.

I've personally never seen this happen before. We've known about the xdebug warning for a while but never actually noticed it impacting performance.

That php_codesniffer timeout is probably the main problem. 300 seconds is 5 minutes alone and it might be doing other requests too.

I just ran `composer install` on your version on a brand new Composer install with nothing cached and got this:

`composer install  14.27s user 5.89s system 38% cpu 52.718 total`

So just under a minute.

I'd be interested if you could run it on your local machine and compare the times vs the VM.

**Comment by cibulka** [comment]
It would seem, that on my new machine the issue is gone. Thanks & sorry for late confirmation!
