### ISSUE TITLE
Install instruction do not work without github account

### ISSUE THREAD

**Issue by COLABORATI** [roots/trellis#636]
Please do not assume that everybody has an active github account in his default console config, there are many reasons not to do it like this (e.g. for security reasons and to prevent mistakes). 

Please change the [installation instructions](https://roots.io/trellis/docs/installing-trellis/) to contain https links to the github repo (`https://github.com/roots/trellis.git`) so that the instructions are copy-pasteble and working oob for everybody - thanks!

**Comment by retlehs** [comment]
i'm scared to think about how many more support threads we would deal with by not requiring this up front due to lots of confusion already with ssh keys when it comes to provisioning remote servers 🙈
