### ISSUE TITLE
Installing Ansible with pip fails on Windows ( master & 0.9.8 ) 

### ISSUE THREAD

**Issue by ftrudeau** [roots/trellis#655]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

Replace any `X` with your information.

---

## Bug report

==> default: Installing Ansible with pip...
==> default: Collecting ansible==2.0.2.0
==> default:   Downloading ansible-2.0.2.0.tar.gz (1.5MB)
==> default: Collecting paramiko (from ansible==2.0.2.0)
==> default:   Downloading paramiko-2.0.2-py2.py3-none-any.whl (171kB)
==> default: Collecting jinja2 (from ansible==2.0.2.0)
==> default:   Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
==> default: Collecting PyYAML (from ansible==2.0.2.0)
==> default:   Downloading PyYAML-3.12.tar.gz (253kB)
==> default: Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from ansible==2.0.2.0)
==> default: Collecting pycrypto>=2.6 (from ansible==2.0.2.0)
==> default:   Downloading pycrypto-2.6.1.tar.gz (446kB)
==> default: Collecting pyasn1>=0.1.7 (from paramiko->ansible==2.0.2.0)
==> default:   Downloading pyasn1-0.1.9-py2.py3-none-any.whl
==> default: Collecting cryptography>=1.1 (from paramiko->ansible==2.0.2.0)
==> default:   Downloading cryptography-1.5.tar.gz (400kB)
==> default: Collecting MarkupSafe (from jinja2->ansible==2.0.2.0)
==> default:   Downloading MarkupSafe-0.23.tar.gz
==> default: Collecting idna>=2.0 (from cryptography>=1.1->paramiko->ansible==2.0.2.0)
==> default:   Downloading idna-2.1-py2.py3-none-any.whl (54kB)
==> default: Collecting six>=1.4.1 (from cryptography>=1.1->paramiko->ansible==2.0.2.0)
==> default:   Downloading six-1.10.0-py2.py3-none-any.whl
==> default: Collecting enum34 (from cryptography>=1.1->paramiko->ansible==2.0.2.0)
==> default:   Downloading enum34-1.1.6-py2-none-any.whl
==> default: Collecting ipaddress (from cryptography>=1.1->paramiko->ansible==2.0.2.0)
==> default:   Downloading ipaddress-1.0.16-py27-none-any.whl
==> default: Collecting cffi>=1.4.1 (from cryptography>=1.1->paramiko->ansible==2.0.2.0)
==> default:   Downloading cffi-1.8.2.tar.gz (403kB)
==> default: Collecting pycparser (from cffi>=1.4.1->cryptography>=1.1->paramiko->ansible==2.0.2.0)
==> default:   Downloading pycparser-2.14.tar.gz (223kB)
==> default: Building wheels for collected packages: ansible, PyYAML, pycrypto, cryptography, MarkupSafe, cffi, pycparser
==> default:   Running setup.py bdist_wheel for ansible: started
==> default:   Running setup.py bdist_wheel for ansible: finished with status 'done'
==> default:   Stored in directory: /root/.cache/pip/wheels/7a/56/e4/5dbcf0564a8cad5175b8c85bb123fdc81ad48bd31d27ac6011
==> default:   Running setup.py bdist_wheel for PyYAML: started
==> default:   Running setup.py bdist_wheel for PyYAML: finished with status 'done'
==> default:   Stored in directory: /root/.cache/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
==> default:   Running setup.py bdist_wheel for pycrypto: started
==> default:   Running setup.py bdist_wheel for pycrypto: finished with status 'done'
==> default:   Stored in directory: /root/.cache/pip/wheels/80/1f/94/f76e9746864f198eb0e304aeec319159fa41b082f61281ffce
==> default:   Running setup.py bdist_wheel for cryptography: started
==> default:   Running setup.py bdist_wheel for cryptography: finished with status 'error'
==> default:   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o8slFW/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpKHjLALpip-wheel- --python-tag cp27:
==> default:   c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
==> default:   compilation terminated.
==> default:   Traceback (most recent call last):
==> default:     File "<string>", line 1, in <module>
==> default:     File "/tmp/pip-build-o8slFW/cryptography/setup.py", line 334, in <module>
==> default:       **keywords_with_side_effects(sys.argv)
==> default:     File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
==> default:       _setup_distribution = dist = klass(attrs)
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
==> default:       self.fetch_build_eggs(attrs['setup_requires'])
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
==> default:       replace_conflicting=True,
==> default:     File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
==> default:       dist = best[req.key] = env.best_match(req, ws, installer)
==> default:     File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
==> default:       return self.obtain(req, installer)
==> default:     File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
==> default:       return installer(requirement)
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
==> default:       return cmd.easy_install(req)
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
==> default:       return self.install_item(spec, dist.location, tmpdir, deps)
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
==> default:       dists = self.install_eggs(spec, download, tmpdir)
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
==> default:       return self.build_and_install(setup_script, setup_base)
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
==> default:       self.run_setup(setup_script, setup_base, args)
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1089, in run_setup
==> default:       raise DistutilsError("Setup script exited with %s" % (v.args[0],))
==> default:   distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
==> default:
==> default:   ----------------------------------------
==> default:   Failed building wheel for cryptography
==> default:   Running setup.py clean for cryptography
==> default:   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o8slFW/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
==> default:   c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
==> default:   compilation terminated.
==> default:   Traceback (most recent call last):
==> default:     File "<string>", line 1, in <module>
==> default:     File "/tmp/pip-build-o8slFW/cryptography/setup.py", line 334, in <module>
==> default:       **keywords_with_side_effects(sys.argv)
==> default:     File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
==> default:       _setup_distribution = dist = klass(attrs)
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
==> default:       self.fetch_build_eggs(attrs['setup_requires'])
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
==> default:       replace_conflicting=True,
==> default:     File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
==> default:       dist = best[req.key] = env.best_match(req, ws, installer)
==> default:     File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
==> default:       return self.obtain(req, installer)
==> default:     File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
==> default:       return installer(requirement)
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
==> default:       return cmd.easy_install(req)
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
==> default:       return self.install_item(spec, dist.location, tmpdir, deps)
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
==> default:       dists = self.install_eggs(spec, download, tmpdir)
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
==> default:       return self.build_and_install(setup_script, setup_base)
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
==> default:       self.run_setup(setup_script, setup_base, args)
==> default:     File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1089, in run_setup
==> default:       raise DistutilsError("Setup script exited with %s" % (v.args[0],))
==> default:   distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
==> default:
==> default:   ----------------------------------------
==> default:   Failed cleaning build dir for cryptography
==> default:   Running setup.py bdist_wheel for MarkupSafe: started
==> default:   Running setup.py bdist_wheel for MarkupSafe: finished with status 'done'
==> default:   Stored in directory: /root/.cache/pip/wheels/a3/fa/dc/0198eed9ad95489b8a4f45d14dd5d2aee3f8984e46862c5748
==> default:   Running setup.py bdist_wheel for cffi: started
==> default:   Running setup.py bdist_wheel for cffi: finished with status 'error'
==> default:   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o8slFW/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpTciqslpip-wheel- --python-tag cp27:
==> default:   running bdist_wheel
==> default:   running build
==> default:   running build_py
==> default:   creating build
==> default:   creating build/lib.linux-x86_64-2.7
==> default:   creating build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/ffiplatform.py -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/api.py -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/verifier.py -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/recompiler.py -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/commontypes.py -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/lock.py -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/vengine_gen.py -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/cparser.py -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/model.py -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/__init__.py -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/_cffi_include.h -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/parse_c_type.h -> build/lib.linux-x86_64-2.7/cffi
==> default:   copying cffi/_embedding.h -> build/lib.linux-x86_64-2.7/cffi
==> default:   running build_ext
==> default:   building '_cffi_backend' extension
==> default:   creating build/temp.linux-x86_64-2.7
==> default:   creating build/temp.linux-x86_64-2.7/c
==> default:   x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
==> default:   c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
==> default:   compilation terminated.
==> default:   error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
==> default:
==> default:   ----------------------------------------
==> default:   Failed building wheel for cffi
==> default:   Running setup.py clean for cffi
==> default:   Running setup.py bdist_wheel for pycparser: started
==> default:   Running setup.py bdist_wheel for pycparser: finished with status 'done'
==> default:   Stored in directory: /root/.cache/pip/wheels/9b/f4/2e/d03e949a551719a1ffcb659f2c63d8444f4df12e994ce52112
==> default: Successfully built ansible PyYAML pycrypto MarkupSafe pycparser
==> default: Failed to build cryptography cffi
==> default: Installing collected packages: pyasn1, idna, six, enum34, ipaddress, pycparser, cffi, cryptography, paramiko, MarkupSafe, jinja2, PyYAML, pycrypto, ansible
==> default:   Running setup.py install for cffi: started
==> default:     Running setup.py install for cffi: finished with status 'error'
==> default:     Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o8slFW/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-kg7_9n-record/install-record.txt --single-version-externally-managed --compile:
==> default:     running install
==> default:     running build
==> default:     running build_py
==> default:     creating build
==> default:     creating build/lib.linux-x86_64-2.7
==> default:     creating build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/ffiplatform.py -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/api.py -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/verifier.py -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/recompiler.py -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/commontypes.py -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/lock.py -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/vengine_gen.py -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/cparser.py -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/model.py -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/__init__.py -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/_cffi_include.h -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/parse_c_type.h -> build/lib.linux-x86_64-2.7/cffi
==> default:     copying cffi/_embedding.h -> build/lib.linux-x86_64-2.7/cffi
==> default:     running build_ext
==> default:     building '_cffi_backend' extension
==> default:     creating build/temp.linux-x86_64-2.7
==> default:     creating build/temp.linux-x86_64-2.7/c
==> default:     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
==> default:     c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
==> default:     compilation terminated.
==> default:     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
==> default:
==> default:     ----------------------------------------
==> default: Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o8slFW/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-kg7_9n-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-o8slFW/cffi/
==> default: You are using pip version 8.1.1, however version 8.1.2 is available.
==> default: You should consider upgrading via the 'pip install --upgrade pip' command.
==> default: Collecting markupsafe
==> default: Installing collected packages: markupsafe
==> default: Successfully installed markupsafe-0.23
==> default: You are using pip version 8.1.1, however version 8.1.2 is available.
==> default: You should consider upgrading via the 'pip install --upgrade pip' command.
==> default: Running Ansible Galaxy install
==> default: /tmp/vagrant-shell: line 44: ansible-galaxy: command not found
==> default: Running Ansible Playbooks
==> default: /tmp/vagrant-shell: line 49: ansible-playbook: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Please describe your local environment:**

Ansible version: n/a

OS: n/a

Vagrant version: 1.8.5

**Where did the bug happen? Development or remote servers?**

Dev, while running vagrant.exe up

**Please provide a repository or your `wordpress_sites` config (if possible):**

Default used.

**Other relevant information:**

X

**Comment by swalkinshaw** [comment]
Could you try SSHing into the VM and running this:

`sudo apt-get install build-essential libssl-dev libffi-dev python-dev`

Then run `vagrant provision` again

**Comment by swalkinshaw** [comment]
Reference: http://stackoverflow.com/questions/22073516/failed-to-install-python-cryptography-package-with-pip-and-setup-py

http://stackoverflow.com/questions/35144550/how-to-install-cryptography-on-ubuntu

**Comment by ftrudeau** [comment]
That did the trick, thanks.
