### ISSUE TITLE
Deprecation warning from Ansible due to outdated mailhog dependency

### ISSUE THREAD

**Issue by ssteinerx** [roots/trellis#662]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

What is the current behavior?

Ancient version of mailhog (1.0.5 (February), 1.0.6 3 days later, 1.1.0(April), 2.0.0 (July)), produces Ansible Deprecation warning due to outdated role spec syntax.:

```
 mailhog was installed successfully
[DEPRECATION WARNING]: The comma separated role spec format, use the yaml/explicit format instead..
This feature
will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in
 ansible.cfg.
```

What is the expected or desired behavior?

No deprecation warnings, current compatible versions of tools to take advantage of latest features, bug fixes, etc.

Bug report

Following setup instructions:

`ansible-galaxy install -r requirements.yml`

Deprecation warning shown above.

Please describe your local environment:

Ansible version: ansible 2.1.1.0

OS: OS X 10.11.6

Vagrant version: Vagrant 1.8.5

Where did the bug happen? Development or remote servers?

Dev system initial setup.

**Comment by swalkinshaw** [comment]
Thanks. We should at least update to 1.1.0 which fixes this I think. 2.0.0 looks better but might require some changes on our end.

**Comment by swalkinshaw** [comment]
Do you want to do a PR to update to 1.1.0?

**Comment by ssteinerx** [comment]
@swalkinshaw Seems pretty trivial, but I'll do one just to make sure the tests pass.  Speaking of which, since I'm not particularly familiar with the Trellis code yet, can you tell me whether there any tests specifically related to MailHog that will catch any incompatibilities?

**Comment by swalkinshaw** [comment]
@ssteinerx you're in luck, we don't have any tests! 😭 

All our test suite does is run Ansible's syntax check to ensure we at least don't commit completely broken code.

We'd love to get a proper test suite going it's just hard with Ansible/this project unfortunately.
