### ISSUE TITLE
Oct 2nd - bento/ubuntu16.04 v 2.3.0 breaks the vm

### ISSUE THREAD

**Issue by stejmurphy** [roots/trellis#666]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

---

**What is the current behavior?**

Pull latest trellis,
setup machine. 'bento/ubuntu' will pull down v2.3.0 (new as of October 2nd).
Machine will build but hang at SSH.

**What is the expected or desired behavior?**

should not hang

---

## Bug report

**Please describe your local environment:**

Ansible version: 2.0.2

OS: OSX 10.11.6

Vagrant version: 1.8.5

**Where did the bug happen? Development or remote servers?**

local

**Please provide use cases for changing the current behavior:**

`vagrant` file. specify the VM version with

 `config.vm.box_version = '2.2.9'`

**Comment by swalkinshaw** [comment]
Thanks for reporting this. Looks like an upstream issue with the box: https://github.com/chef/bento/issues/677

I'll probably lock to `2.2.9` in the meantime.

**Comment by stejmurphy** [comment]
We've done this locally with the above solution and it's working. 

Is there any benefit for trellis to always pull the latest vm? We're going to lock our stack to 2.2.9 for awhile.

**Comment by swalkinshaw** [comment]
Probably not. It's usually a good practice to specify a version whenever possible (see: package managers).

Want to do a PR for this?

**Comment by stejmurphy** [comment]
Sure, I can do this later today

**Comment by cheeseplus** [comment]
FYI, this is a virtualbox 5.1.6 issue less than a bento issue as per upstream ;)
