### ISSUE TITLE
Set secure sysctl defaults and allow kernel tuning

### ISSUE THREAD

**Issue by RiFi2k** [roots/trellis#671]
## Submit a feature request or bug report
- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

---

**What is the current behavior?**

None

**What is the expected or desired behavior?**

Set sysctl.conf with secure defaults, and allow user specific configuration if needed.
http://docs.ansible.com/ansible/sysctl_module.html

---
## Feature Request

**Please provide use cases for changing the current behavior:**

http://thehackernews.com/2016/08/linux-tcp-packet-hacking.html

I know this is patched already but just an example of something popping up.

https://tweaked.io/guide/kernel/
For tuning

**Other relevant information:**

Probably a good idea to set secure defaults for the kernel that won't effect normal installs and give the option for tuning other configurations that users may need / want for performance. For example I needed to up my fs.file-max and a few others on my server hosting multiple websites.

**Comment by swalkinshaw** [comment]
This makes sense if there's some good defaults we can set automatically. We just have to be careful that they make sense for the average (or most) sites/servers.

**Comment by RiFi2k** [comment]
So while doing the ssh-hardening integration I stumbled on https://github.com/dev-sec/ansible-os-hardening which includes sysctl defaults plus some other good stuff.

What would be the feeling on the possibility of adding that whole role in as well?

**Comment by swalkinshaw** [comment]
Looks mostly good. There's some firewall/ufw things in there that might conflict with our existing stuff though.

**Comment by RiFi2k** [comment]
I saw that as well, I think if we just set
`ufw_manage_defaults: false`
It just bypasses their ufw settings altogether.

**Comment by swalkinshaw** [comment]
This hasn't proven to be a big issue over the years. Closing as stale/wontfix
