### ISSUE TITLE
error getting key id from url: http://keyserver.ubuntu.com

### ISSUE THREAD

**Issue by isvaljek** [roots/trellis#672]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**
Vagrant provision stops at MariaDB task.

==> default: TASK [mariadb : Add MariaDB MySQL apt-key] *************************************
==> default: System info:
==> default:   Ansible 2.0.2.0; Vagrant 1.8.6; Linux
==> default:   Trellis at "Enable per-site setup for permalink structure"
==> default: ---------------------------------------------------
==> default: error getting key id from url: http://keyserver.ubuntu.com/pks/lookup?op=get&
==> default: fingerprint=on&search=0xcbcb082a1bb943db
==> default: fatal: [192.168.50.5]: FAILED! => {"changed": false, "failed": true, "traceback": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1477208298.04-182712911871134/apt_key\", line 166, in download_key\n    return rsp.read()\n  File \"/usr/lib/python2.7/socket.py\", line 355, in read\n    data = self._sock.recv(rbufsize)\n  File \"/usr/lib/python2.7/httplib.py\", line 612, in read\n    s = self.fp.read(amt)\n  File \"/usr/lib/python2.7/socket.py\", line 384, in read\n    data = self._sock.recv(left)\nerror: [Errno 104] Connection reset by peer\n"}
==> default:

**What is the expected or desired behavior?**

Maria DB installed and vagrant provision completes on Windows host + Virtualbox 5.0.28

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

cmd.exe vagrant provision

**Please describe your local environment:**

Ansible version: 2.0.2.0

OS: Windows 10 Pro (Host) Ubuntu 16.04 Virtual

Vagrant version: 1.8.6

**Where did the bug happen? Development or remote servers?**

Development

**Please provide a repository or your `wordpress_sites` config (if possible):**

X

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

---

**Other relevant information:**

Same Trellis repo functions for provisioning and deploying to staging VPS.

**Comment by retlehs** [comment]
> Connection reset by peer

you posted this when there was that large attack going on the internet the other day. probably fine now. if not, post on https://discourse.roots.io/ since this is a connectivity issue and not a bug

**Comment by isvaljek** [comment]
But when I login to virtualbox with vagrant ssh, and do a wget to the same URL it works.
And it's returning the same error today for the vagrant provision command.
