### ISSUE TITLE
Potential Pull Requests - build-before.yml & Wordpress Install

### ISSUE THREAD

**Issue by runofthemill** [roots/trellis#674]
## Submit a feature request or bug report
- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [ ] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

Replace any `X` with your information.
---

I've been refactoring some of the custom changes I've made to my Trellis (v 0.9.7) stack to a bare 0.9.8 repo, and ran into a few things that I thought might benefit from pull requests but wanted to get input first.
1. Installing Wordpress; is there a particular reason why `dev.yml` includes the `wordpress-install` role but it's not in either `server.yml` or `deploy.yml` (with a conditional check of course)? Having it installed at some point prior to the end of `deploy.yml` would allow users to easily add `WP-CLI` tasks into their deploy process.
2. Changing default/example `build-before.yml` hook to operate remotely; since this hook is configured for use with Sage, it's likely that if someone is using it, their Sage theme is part of the same git repo. The rest of Trellis, if used in conjunction with Bedrock, follows the behavior that any local changes in `/trellis` are reflected immediately upon running `ansible-playbook` with `dev.yml` or `deploy.yml`, whereas local changes in `/site` are not reflected unless committed and pushed to the configured remote repo. The example `build-before.yml` hook breaks with this behavior. I saw some conversations somewhat related in #124, #146 and #155, and I get the general desire to not have more dependencies on the remote server, but as this is an optional hook I think it makes more sense to keep consistent with the expected behavior.

**Comment by swalkinshaw** [comment]
1. I honestly kind of forget why we don't automatically install WP in non-dev envs. Maybe it's something we should revisit again. It does cause some confusion as we've had people complain Trellis isn't working properly.

2. We prefer to stick with our own best practice recommendations which is why we compile locally. So we wouldn't want to have that example file compile remotely and then separately recommend doing it locally (such as in roots-example-project). I don't really think it's that inconsistent as asset compilation is a much different context than running `composer install` for example.

**Comment by runofthemill** [comment]
Makes sense. I plan on integrating the WP install into my current project's `server.yml` so perhaps when I'm done I'll submit a PR.

Re: 2; for my own knowledge, what specifically do you guys find problematic (in practice or in theory) with compiling remotely?

**Comment by swalkinshaw** [comment]
Compiling remotely adds more complexity to the server. A lot more packages and dependencies need to be installed to make that happen. And that isn't trivial these days with complicated JS stacks (node, npm/yarn, bower, babel, gulp, etc).

So you end up with a lot more software on the server that isn't needed to actually run your WP site. It's just a part of the build/deploy process.
