### ISSUE TITLE
Vagrant Up fails under Ansible 2.2.0.0

### ISSUE THREAD

**Issue by Leland** [roots/trellis#679]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

---

**What is the current behavior?**

On a fresh install, following the exact instructions provided, `vagrant up` fails with the following error:

``` BASH
TASK [mailhog : Ensure mailhog is enabled and will start on boot.] *************
System info:
  Ansible 2.2.0.0; Vagrant 1.8.6; Darwin
  Trellis at "Update to WP-CLI 0.25.0 for WP 4.7 compat"
---------------------------------------------------
Could not find the requested service "'mailhog'":
fatal: [default]: FAILED! => {"changed": false, "failed": true}
```

**What is the expected or desired behavior?**

`vagrant up` completes successfully.

---

## Bug report

To reproduce, simply install everything from scratch. The default Ansible installation is now 2.2, which results in this failure. You can get everything working again by going back to 2.1.1, as noted by [fullyint on Discourse](https://discourse.roots.io/t/could-not-find-the-requested-service-mailhog/8034/3?u=leland).

**Please describe your local environment:**

Ansible version: 2.2.0.0

OS: 10.12.1

Vagrant version: 1.8.6

**Where did the bug happen? Development or remote servers?**

Development.

**Please provide a repository or your `wordpress_sites` config (if possible):**

[Gist](https://gist.github.com/Leland/c4e01d6cfcd3d324cf60492a4c69422f)

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

[Could not find the requested service “‘mailhog’”](https://discourse.roots.io/t/could-not-find-the-requested-service-mailhog/8034/1)

**Comment by miklb** [comment]
Just encountered same thing setting up a new environment with an existing project.

**Comment by miklb** [comment]
Related to Ansible 2.2 it seems. https://discourse.roots.io/t/could-not-find-the-requested-service-mailhog/8034/3
