### ISSUE TITLE
Vagrant up fail on mac os

### ISSUE THREAD

**Issue by antonmarin** [roots/trellis#698]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [ ] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

Seems like it's not working on mac os. 
Done:
- https://roots.io/trellis/docs/installing-trellis/
- changed key and site_hosts in vault and wordpress_sites
- vagrant up

Have:
- site_hosts are not available
- no hosts in /etc/hosts
- "Mounting NFS shared folders..." last more that expected 

> ==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
set -e
mkdir -p /vagrant-nfs-an-_my-host-here_
mount -o vers=3,udp 192.168.50.1:/Users/antonmarin/PhpstormProjects/_my-host-here_/site /vagrant-nfs-_my-host-here_
if command -v /sbin/init && /sbin/init --version | grep upstart; then
  /sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/vagrant-nfs-_my-host-here_
fi
Stdout from the command:
Stderr from the command:
mount.nfs: Connection timed out

**What is the expected or desired behavior?**

my dev host available with wordpress template

---

## Bug report

**Please provide steps to reproduce, including full log output:**

- https://roots.io/trellis/docs/installing-trellis/
- changed key and site_hosts in vault and wordpress_sites
- vagrant up

**Please describe your local environment:**

Ansible version: ansible 2.2.0.0

OS: MacOS Sierra

Vagrant version: Vagrant 1.8.6

**Where did the bug happen? Development or remote servers?**

Development

**Please provide a repository or your `wordpress_sites` config (if possible):**

no repo now

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

not found

**Comment by retlehs** [comment]
please post on https://discourse.roots.io/c/trellis for support

**Comment by antonmarin** [comment]
posted.
Isn't it an issue?

**Comment by retlehs** [comment]
most likely an issue with your setup rather than an issue with the codebase. it's best to do the back-and-forth on discourse instead of github so that everyone watching this repo isn't notified.
