### ISSUE TITLE
Timeout crash for Mailhog installation

### ISSUE THREAD

**Issue by abumalick** [roots/trellis#700]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

Under `TASK [mailhog : Download MailHog and mhsendmail binaries.]` I get a `failed to create temporary content file: ('The read operation timed out',)` (My internet is quite slow)

**What is the expected or desired behavior?**

We don't want timeout, we want install towait for the download.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

- Use a slow connexion (between 2KB/s to 100KB/s)
- vagrant up 
```
TASK [mailhog : Ensure mailhog install directory exists.] **********************
ok: [default]

TASK [mailhog : Download MailHog and mhsendmail binaries.] *********************
System info:
  Ansible 2.1.1.0; Vagrant 1.8.5; Linux
  Trellis at "Install MariaDB via Ubuntu's official distro packages"
---------------------------------------------------
failed to create temporary content file: ('The read operation timed out',)
failed: [default] (item={u'url': u'https://github.com/mailhog/MailHog/releases/download/v0.2.0/MailHog_linux_amd64', u'dest': u'/opt/mailhog/mailhog'}) => {"failed": true, "item": {"dest": "/opt/mailhog/mailhog", "url": "https://github.com/mailhog/MailHog/releases/download/v0.2.0/MailHog_linux_amd64"}}
---------------------------------------------------
failed to create temporary content file: ('The read operation timed out',)
failed: [default] (item={u'url': u'https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64', u'dest': u'/opt/mailhog/mhsendmail'}) => {"failed": true, "item": {"dest": "/opt/mailhog/mhsendmail", "url": "https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64"}}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/home/abumalick/ws/www/trellis/dev.retry

PLAY RECAP *********************************************************************
default                    : ok=33   changed=1    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
I didn't include full log, I think you don't really need it.

**Please describe your local environment:**

Ansible version: 2.1.1.0

OS: LinuxMint

Vagrant version: 1.8.5

**Where did the bug happen? Development or remote servers?**

Development during installation

**Please provide a repository or your `wordpress_sites` config (if possible):**

The install did stop before deploy

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

Didn't find any.

---

I am installing manually the package now as a work around.

**Comment by swalkinshaw** [comment]
Thanks for the detailed issue.

This is actually from https://github.com/geerlingguy/ansible-role-mailhog which we don't control. You could try opening an issue over there.

I did take a quick look and it uses the `get_url` module which has a default `timeout` of 10 seconds (ref: http://docs.ansible.com/ansible/get_url_module.html). So maybe an option could be added to customie that.

**Comment by fullyint** [comment]
While you wait for action over at the mailhog upstream, you could manually perform the task that failed. Once you've [`curl`](http://manpages.ubuntu.com/manpages/xenial/en/man1/curl.1.html)ed the files in place, the [`get_url` task](https://github.com/geerlingguy/ansible-role-mailhog/blob/e84fa793ca985c78e91b928f8606e0f36bb6c165/tasks/main.yml#L12) in question will probably succeed and not cause your playbook to fail because I don't think it tries to download those files if they already exist on the machine.

So, specifically, you'd `vagrant ssh` into the VM and run something like ...
```
curl -4Ls https://github.com/mailhog/MailHog/releases/download/v0.2.0/MailHog_linux_amd64 /opt/mailhog/mailhog

curl -4Ls https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64 /opt/mailhog/mhsendmail
```

Then exit out of SSH connection to VM and run `vagrant provision`
