### ISSUE TITLE
Plugin stores required files/folder under site/web/app/uploads/pluginname

### ISSUE THREAD

**Issue by mmunem** [roots/trellis#713]
I'm using the genesis-extender plugin here: https://cobaltapps.com/genesis-extender-front-end-css-builder/

A quote from the comments in the above:

"The style, function and structure changes made by Genesis Extender are hard coded files that are placed in a /wp-content/uploads/genesis-extender/plugin/ folder created by the Plugin. This keeps things separate from both the Plugin and the Child Theme folders to prevent loss of “data” upon updating either the Plugin or Theme"

I amend the .gitignore file to not exclude the site/web/uploads/genesis-extender folder. This ensures that my bitbucket repo does indeed contain this folder. However, the deployment playbook doesn't copy the same folder to my remote DO droplet. This is probably by design and would appreciate pointers on how to ensure the above folder is copied across. Thanks!

**Comment by kalenjohnson** [comment]
Please don't clear out the guidelines for contributing. We have set up a template to fill out for a reason. This is a personal request, not a bug with Trellis, and belongs on Discourse:

> This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums
