### ISSUE TITLE
Deploy can break sidebars/widgets if multiple sites defined

### ISSUE THREAD

**Issue by retlehs** [roots/trellis#718]
[Update WP theme paths](https://github.com/roots/trellis/blob/3e32e2ae9cc78010e8b36ba63cb52da52ed1582c/roles/deploy/hooks/finalize-after.yml#L10-L14) is the culprit.

needs investigating, related discourse threads:

https://discourse.roots.io/t/wordpress-4-7-update-moved-all-widgets/8277/6
https://discourse.roots.io/t/update-wp-theme-paths-what-does-this-hook-do/8296

**Comment by retlehs** [comment]
when a deploy occurs, the `sidebars_widgets` setting gets updated & the theme is re-activated

**Comment by swalkinshaw** [comment]
Is this 4.7 only?
