### ISSUE TITLE
Notes about mysql passwords

### ISSUE THREAD

**Issue by fullyint** [roots/trellis#73]
Could the `README.md` could use [these notes](https://github.com/fullyint/bedrock-ansible/commit/154a355ca2289d6511ad0c32c9448c9bdeb88a67) about the mysql passwords?

### `mysql_root_password` with roots/bedrock box
The "Set root user password" task (`roles/mariadb/tasks/main.yml`) fails when I make any change to `mysql_root_password` (in `group_vars/development`) while `config.vm.box = 'roots/bedrock'`. I'm guessing the roots/bedrock box has the `mysql_root_password` set already.

### Special characters in db_password
When `db_import=true` and `db_password` contains any of the characters `$ & ( )`, the "Import database" task (`roles/wordpress-sites/tasks/database.yml`) fails with messages such as `mysql ERROR 1045 (28000): Access denied for user...`.

Some characters were fine: `a-z 0-9 ! % * # @ ^ - `. I didn't test any others. It also failed with [escaping](http://jinja.pocoo.org/docs/dev/templates/#escaping): `login_password={% raw %}"{{ item.env.db_password }}"{% endraw %}` (also without the double-quotes).

I don't see any adjustments to make aside from having the `README.md` warn users about special characters. I think the problem is with ansible's [`mysql_db`](http://docs.ansible.com/mysql_db_module.html) module ([source](https://github.com/ansible/ansible-modules-core/blob/devel/database/mysql_db.py)) when `state=import` (or maybe the problem is with the MySQLdb Python package being used).

The problem doesn't occur when `state=present`, as in the bedrock-ansible's task "Create database of sites" (e.g., when `mysql_root_password` contains special characters), nor when the `login_password` parameter is used with ansible's [`mysql_user`](http://docs.ansible.com/mysql_user_module.html) module ([source](https://github.com/ansible/ansible-modules-core/blob/devel/database/mysql_user.py); used several times throughout the bedrock-ansible playbook).

A few potentially related notes over at ansible: [1](https://github.com/ansible/ansible/issues/7053), [2](https://github.com/ansible/ansible/issues/8137), [3](https://github.com/ansible/ansible/issues/8161).

**Comment by thiagodebastos** [comment]
Is this still supposed to be happening? I arrived here because I faced the same issue.

**Comment by ramielbarsoum** [comment]
Similar issue here when changing the Development mysql_root_password: from devpw to non special character one (Just upper case lower case custom pass), however, reverting the file to the devpw password seemed to allow the provisioning correctly.

This is the error output on vagrant provision / up:
TASK: [mariadb | Set root user password] ************************************** 
failed: [default] => (item=dev) => {"failed": true, "item": "dev"}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
failed: [default] => (item=127.0.0.1) => {"failed": true, "item": "127.0.0.1"}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
failed: [default] => (item=::1) => {"failed": true, "item": "::1"}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
failed: [default] => (item=localhost) => {"failed": true, "item": "localhost"}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials

FATAL: all hosts have already failed -- aborting

**Comment by louim** [comment]
I just wanted to chime in, I just helped one of my coworker with this problem. It happens because the base box already have a password. I believe the temporary fix would be to hide `mysql_root_password `  option from the `development` config, as someone seeing this setting may try to change it seeing it exposed.

**Comment by swalkinshaw** [comment]
Not valid anymore. See https://github.com/roots/trellis/pull/260.
