### ISSUE TITLE
Update WP theme paths task incorrectly checks wp_template_root var

### ISSUE THREAD

**Issue by tmdk** [roots/trellis#731]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [ ] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

## Bug report

The options `template_root` and `theme_root` are overridden on deploy even if `template_root` is empty or set to `/themes` . As a result, it can break the activated theme (see discourse discussion below)

It seems the fix for #718 contains a bug: i think it should compare `wp_template_root.stdout` instead of `wp_template_root` in the Update WP theme paths task.

**Please describe your local environment:**

Ansible version: 2.2.0.0

OS: Windows 10

Vagrant version: 1.9.1

**Where did the bug happen? Development or remote servers?**

Remote

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

Seems to be discussing the same bug: https://discourse.roots.io/t/the-theme-directory-theme1-does-not-exist/8485/12

**Comment by akovalyov** [comment]
I can confirm that I experience this bug. I have a custom theme in `site/web/app/themes` folder. Right now after each deployment I need to activate one of default themes and reactivate a custom one.

**Comment by retlehs** [comment]
you can try reverting https://github.com/roots/trellis/pull/719 in the meantime

**Comment by akovalyov** [comment]
@retlehs awesome, it worked! Thanks a lot! Probably the solution which was proposed via `wp option` is not complete.

**Comment by emanuelet** [comment]
Deploying with the latest code from master I encountered a similar problem where apparently the option was pointing to **web/wp-content/themes** while I have my theme in **web/app/themes** and so I had to manually change the configuration in _Update WP theme paths_
