### ISSUE TITLE
Could not find composer.json error

### ISSUE THREAD

**Issue by jbicha** [roots/trellis#738]
- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums
---

## Bug report

I am just getting started with trellis, following the docs. ansible gets stuck here:

```
TASK [wordpress-install : Install Dependencies with Composer] ******************
System info:
  Ansible 2.2.0.0; Linux
  Trellis at "Add `SKIP_GALAXY` env var to skip galaxy install in Vagrant"
---------------------------------------------------
Composer could not find a composer.json file in
/srv/www/toddandsarah.org/current To initialize a project, please create a
composer.json file as described in the https://getcomposer.org/ "Getting
Started" section
failed: [192.168.50.5] (item=example.com) => {"failed": true, "item":
"example.com", "stdout": "Composer could not find a composer.json file in
/srv/www/example.com/current\nTo initialize a project, please create a
composer.json file as described in the https://getcomposer.org/ \"Getting
Started\" section\n", "stdout_lines": ["Composer could not find a
composer.json file in /srv/www/example.com/current", "To initialize a project,
please create a composer.json file as described in the
https://getcomposer.org/ \"Getting Started\" section"]}
```

**Please describe your local environment:**

Ansible version: 2.2.0.0-4 on Ubuntu 17.04 Alpha. Also tested with ansible 2.1.1.0-1.

**Where did the bug happen? Development or remote servers?**

Development

**Comment by jbicha** [comment]
Hmm, similar issues have been reported. I guess there's a problem with my local NFS. Closing.

**Comment by jbicha** [comment]
Specifically, my problem was that NFS does not [work](http://serverfault.com/a/392232/126734) with ecryptfs. You have ecryptfs if you clicked the button in the Ubuntu installer to encrypt your home directory.

The solution is to move your trellis folder outside the ecryptfs directories.

The error messages I got were
```
mount.nfs: access denied by server while mounting
  192.168.50.1:/home/jeremy/example.com/site
rpc.mountd: refused mount request from 192.168.50.1 for
  /home/jeremy/example.com/site (/home/jeremy/example.com/site):
  unmatched host
exportfs: /home/jeremy/example.com/site does not support NFS export
```

**Comment by TheSycamore** [comment]
Hello, After following through the installation instructions here: https://roots.io/trellis/docs/installing-trellis/
I too get the following error when running "vagrant up" inside my trellis folder after configuring the relevant trellis files:
```
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
Error Output:
```
TASK [wordpress-install : Install Dependencies with Composer] ******************
System info:
  Ansible 2.4.1.0; Vagrant 2.0.0; Linux
  Trellis at "Update wp-cli to 1.4.0"
---------------------------------------------------
Composer could not find a composer.json file in
/srv/www/example.com/current To initialize a project, please create a
composer.json file as described in the https://getcomposer.org/ "Getting
Started" section
failed: [default] (item=example.com) => {"changed": false, "failed": true, "item": "example.com", "stdout": "Composer could not find a composer.json file in /srv/www/example.com/current\nTo initialize a project, please create a composer.json file as described in the https://getcomposer.org/ \"Getting Started\" section\n", "stdout_lines": ["Composer could not find a composer.json file in /srv/www/example.com/current", "To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ \"Getting Started\" section"]}
```


My hard drive scheme does use crypto_LUKS filesystem for the nvme0n1p3 partition as can be seen here:

$ lsblk -f
```
NAME                    FSTYPE               MOUNTPOINT
nvme0n1                                                                          
├─nvme0n1p3             crypto_LUKS          
│ └─nvme0n1p3_crypt     LVM2_member       
│   ├─ubuntu--vg-root   ext4              /
│   └─ubuntu--vg-swap_1 swap              [SWAP]
├─nvme0n1p1             vfat              /boot/efi
└─nvme0n1p2             ext2              /boot

```


So am I experiencing the same problem as the above users -> that NFS does not work with ecryptfs??
Is ecryptfs the same as crypto_LUKS fs which is what my partitions are using?
This is very upsetting as I would love to be able to utilise trellis as I do lots of work with Wordpress.
Is there any alternative workaround for someone in my position: someone using an encrypted device?
Or could this error be due to something else? Any help would be greatly appreciated.

**Please describe your local environment:**

Ansible version: 2.4.1.0 on Ubuntu 16.04.1.

**Where did the bug happen? Development or remote servers?**

Development


Thank you for your time and any help!

**Comment by kalenjohnson** [comment]
Mounting an encrypted folder, AFAIK, is an issue with NFS and not Trellis itself. It seems like something that's been an issue for years: https://serverfault.com/questions/200759/exportfs-warning-home-user-share-does-not-support-nfs-export#comment962193_392232

You can try modifying the Vagrantfile to mount everything with the standard Vagrant share instead: https://github.com/roots/trellis/blob/be0cd6baf3f90e8cb825d23ad6713bc3f814523f/Vagrantfile#L73-L78

**Comment by TheSycamore** [comment]
Thanks for your reply!
I am new to vagrant and am still learning the ins and outs. Do you what I would need to change in the above Vagrantfile to mount to the following directory?
`/home/me/example/ `

**Comment by stevenmunro** [comment]
I'm getting this same error. I've followed the installation guide word for word. The volume I'm putting this on isn't even encrypted.

Ansible version 2.6 on MacOS HS.
