### ISSUE TITLE
Generate salts automatically. Allow developer to override if they want.

### ISSUE THREAD

**Issue by mindfullsilence** [roots/trellis#746]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

Must manually generate salts for each site, and add them to the wordpress_sites.yml for each environment.

**What is the expected or desired behavior?**

Set these values to a default such as:
```
env:
  auth_key: {{ salt( 'auth_key' ) }}
  auth_salt: {{ salt( 'auth_salt' ) }}
...etc
```
Which would generate a salt on deploy. 

Or centralize them in `all/helpers.yml` or a new file `all/wordpress_sites.yml` or the like so they only need to be defined once, and used across all environments. 

Or both!

---

## Feature Request

**Please provide use cases for changing the current behavior:**

This removes an extra step that the developer must complete, but gives the ability to override with custom values if they choose. Automating this task can also improve security if a developer forgets or disregards setting up those variables, so that their salts aren't left to "generateme". 

**Other relevant information:**

I'm not sure how we would store the salts after generating them the first deploy, but may not need to anyway. Worst case, users of the site get logged out and must log back in after each deploy.

**Comment by swalkinshaw** [comment]
> I'm not sure how we would store the salts after generating them the first deploy, but may not need to anyway. Worst case, users of the site get logged out and must log back in after each deploy.

Logging users out on every deploy is not an option.

This means that any solution to this has to be persistent. These salts need to be stored somewhere and right now the easiest solution is in the files in source control. Any solution also needs to work across computers to support multiple deployers.

The simplest alternative to this is Trellis somehow generating the salts automatically at the start of a project.

See https://github.com/roots/trellis/tree/generate-vault-files/roles/vault for example of some in progress work.

**Comment by mindfullsilence** [comment]
Perfect! Thanks
