### ISSUE TITLE
Use wordpress_sites.yml.example and vault.yml.example files to make tracking changes with upstream easier.

### ISSUE THREAD

**Issue by apmarshall** [roots/trellis#749]
## Feature Request

Having read through previous issues, I'm aware that #76 and #120 address similar suggestions to this one, but it's been a while, the file structure has changed, and I think we can accomplish what those proposals were getting at with a much more narrow approach. 

The previous issues/pull requests required removing everything under group_vars/ from version control except for example templates. That would have added a lot of extra work to apply configuration updates pulled down from roots/trellis (copying and pasting those changes from the .example template into the live template), which in a way defeated the point of those changes (to make it easier to keep in sync with roots/trellis. Since then, the configuration options under group_vars have been split out into much more focused files that allows us to be more precise/specific about which files we are moving to example templates:
  - group_vars/environment/wordpress_sites.yml
  - group_vars/environment/vault.yml
  - group_vars/all/vault.yml
  - group_vars/all/mail.yml

These are the files that a user updates with their site-specific variables. They are already populated with dummy/example information that has to be overwritten by the user on set-up, so moving them to file.yml.example doesn't change much about the set-up process for a given user (you need to copy over the sample templates once on set-up). And since these files contain no universally applied logic/constants, just variables set by the user, they are somewhat protected from future updates: ostensibly variable names aren't going to be changed in future versions, and if new site-specific configuration options are added (hypothetically, let's say, there's a variable to enable or disable the wp-api that's added to Trellis someday), sensibly set defaults can ensure that old sites aren't "broken" by not having a variable set in wordpress_sites.yml.

Potential benefits:
1. Users can pull down changes from the roots/trellis repository, including changes to the sample templates (to see new configuration options) without worrying about overriding their local configs.
2. We prevent accidental committing of site configuration data to a public repository. Yes, I know there is git encrypt and Ansible vault, but when its this easy to offer an added layer of safety to users, why not?
3. (optional) Sample templates can be built out more elaborately to provide in-code documentation of all the configuration options available to users.

You could make very similar arguments regarding the environment files under hosts/. These are even less likely to see upstream updates since they are standard Ansible host files containing straight lists of registered hosts set by the user. Also, removing them from tracking allows users to take advantage of things like @fullyint's solution for deploying multiple sites ([https://discourse.roots.io/t/to-deploy-a-second-site/5229/6](https://discourse.roots.io/t/to-deploy-a-second-site/5229/6)) without needing to worry about their changes to the host configurations getting wiped out by pulling down upstream changes.

Will submit a pull request shortly showing the changes I've made for this.

**Comment by swalkinshaw** [comment]
There's two separate changes here.

1. Rename files that require modification to `.example`
2. Remove the destination files from Git

These aren't tied together either so I'd rather consider them separately. Let's just talk about the first one for now.

If the main benefit to this is to make tracking upstream changes easier, I'm not sure it's worth it. Ideally those files are pretty stable and don't change much. `wordpress_sites.yml` hasn't changed in 7 months for example.

**Comment by apmarshall** [comment]
I hear what you are saying about these files not changing very often. I actually think that's an argument in favor of making this change: by renaming the files with `.example`, we ensure that no user will get surprised by pulling down changes from roots/trellis and discovering that a file that hasn't been updated in 7 months was updated yesterday and now conflicts with their local branch.

**Comment by mindfullsilence** [comment]
What would the benefit of renaming each file with a `.example` extension be over renaming the folder `group-vars-example` or similar? Renaming the folder would be a lot less labor-intensive when kickstarting a project than renaming all group var files, though it does go slightly against the convention.

**Comment by apmarshall** [comment]
@mindfullsilence I would say there are probably two reasons to take the file approach instead of the directory approach:

First, there are a number of things in the directory that are more in the "application logic" category rather than the "strictly local configuration" category. Those are things that are more likely to be updated routinely as new features are added and refined, so having to copy and paste over changes from the example directory after every update would in the long-run be a lot more labor intensive than having to deal with copying multiple files at project kickstart. These "application logic" files are also the sorts of files that if you are making changes that deviate from upstream, you are doing so very intentionally and probably want that committed into your own branch/fork, so removing from git doesn't seem that helpful here. Taking the individual file approach lets us keep our focus only on the files that contain strictly local configurations that you probably don't want in git to begin with.

Second, I'm not convinced it will be that labor intensive. My experience (admittedly not nearly as extensive as a lot of folks here, so perhaps not worth mentioning) is that you update the local configuration files piecemeal rather than all at once. For example, when I'm starting a project, I update the local `wordpress_sites` and `vault` configs, then do a lot of local development work before I want a staging server. Then I update the staging stuff, but it may still be a while (especially if staging is primarily for showcasing to a client before launch) before I care about the production configs. So probably I'm copying over two files from `.example` when I first start, then a few more at each stage of development. I was going to have to rewrite basically everything in those files anyway, so adding a "copy from `.example`" step first doesn't seem to be a big addition.

**Comment by swalkinshaw** [comment]
Switching to `.example` files might be an improvement, but I'm going to pass on this for now. We still have plans to make a Trellis CLI tool for easily generating a project. This is something that would fit better in there instead of the project in Git.
