### ISSUE TITLE
Single and multisite on same box with host-manger and landrush

### ISSUE THREAD

**Issue by slackday** [roots/trellis#756]
- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a feature request
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**

I'm running multiple sites on the same vagrant box. Which works great when having multiple single domain sites.

Now I added a multisite installation to the box and followed the multisite docs when doing this.

Problem is that the vagrant file checks for either single site OR multisite and uses `vagrant-hostmanager` or `landrush` vagrant plugin.

I traced it down to this

```
  if Vagrant.has_plugin?('vagrant-hostmanager') && !multisite_subdomains?(wordpress_sites)
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.aliases = hostnames + redirects
  elsif Vagrant.has_plugin?('landrush') && multisite_subdomains?(wordpress_sites)
    config.landrush.enabled = true
    config.landrush.tld = config.vm.hostname
    hostnames.each { |host| config.landrush.host host, ip }
  else
```

Which is expected. But I think a better approach would be to check per site if it's single or multi. Vagrant applies the same configuration for all sites.

I tried rewriting this as multiple loops but my vagrant skills are not sufficient.

**What is the expected or desired behavior?**

Vagrant should set up multisites per host rather than `ELSEIF` for all hosts like all other configuration works.

**Please describe your local environment:**

Ansible version: 2.2.0.0

OS: 10.10.5

Vagrant version: 1.8.5

---

## Feature Request

**Please provide use cases for changing the current behavior:**

Both single and multisite installs on the same vagrant box.

**Other relevant information:**

I've read on both `vagrant-hostmanager` and `landrush` and from what I learned they can co-exist.

**Comment by slackday** [comment]
Another approach would be to skip `landrush` all together and add each site domain to `wordpress_sites.yml` and applying them with `host-manager`.

I'm in favour of this since it's much easier and keeps the dependencies limited. `landrush` seems to work differently depending on OS and can be incompatible with different version of Vagrant

**Comment by slackday** [comment]
I got it working. If I install `landrush` plugin vagrant doesn't fail on the IF ELSE check.

I don't have to use `landrush` it's just there to pass the check. I can then add the hosts to my host file. 

You can close this issue if you want. I still think there is room for improvement like adding multiple domains for `host-manager` to add for multiple sites instead of adding the manually.

But this works for me now.. sorry for taking your time :)

**Comment by swalkinshaw** [comment]
I'll leave this open. It does seem like we can handle it a little better regardless.

**Comment by swalkinshaw** [comment]
Closing since this is quite old
