### ISSUE TITLE
Include / require php files 

### ISSUE THREAD

**Issue by jonasostrom** [roots/trellis#763]
PHP Warning:  include(/srv/www/xxx-yyy.com/releases/20170217134323/web/app/themes/
sage-theme/src/lib/shop/shop-strings.php): failed to open stream: No such
file or directory in /srv/www/xxx-yyy.com/releases/20170217134323/web/app/themes/sage-
theme/functions.php on line 98

How should I include files with php in functions.php ?

**Comment by retlehs** [comment]
please don't ignore the whole issue template when you go to create a new issue. this is a personal support request that should be posted on https://discourse.roots.io/

![image](https://cloud.githubusercontent.com/assets/115911/23071569/0698f42a-f4ec-11e6-9de3-dc2f9a2a56f0.png)
