### ISSUE TITLE
trellis can not be run with openssh-client older than 6.8 (e.g. not on Ubuntu 14.04 trusty)

### ISSUE THREAD

**Issue by t0mk** [roots/trellis#768]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X]  This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**

Ansible provisioning fails when run from Ubuntu 14.04 (trusty). The newest version of openssh-client on trusty does not support the `-G` option and so it fails:

The commit that introduced the task where `ssh -ttG` is called on the ansible machine is  https://github.com/roots/trellis/commit/ec5c76832ef53389572f808116f93f3e8d110c09

**What is the expected or desired behavior?**

Just succeed with old openssh-client without the `-G` option.

The `-G` was added in 6.8 (https://www.openssh.com/txt/release-6.8). To resolve this means eiter fix the tasks, or mention openss-client >= 6.8 in the Requirements.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

```
tomk@ubuntu1404 ~/ $ cd mywp/trellis
tomk@ubuntu1404 ~/mywp/trellis $ vagrant up # or just vagrant provisions
[...]
TASK [common : Retrieve local SSH client's settings per host] ******************
unknown option -- G
usage: ssh [-1246AaCfgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-L [bind_address:]port:host:hostport] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port]
           [-Q cipher | cipher-auth | mac | kex | key]
           [-R [bind_address:]port:host:hostport] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]
System info:
  Ansible 2.2.1.0; Vagrant 1.9.1; Linux
  Trellis at "Allow for per-project packagist.com authentication"
---------------------------------------------------
An unhandled exception occurred while running the lookup plugin 'pipe'. Error
was a <class 'ansible.errors.AnsibleError'>, original message:
lookup_plugin.pipe(ssh -ttG 127.0.0.1 | grep hostkeyalgorithms) returned 1
fatal: [default]: FAILED! => {"failed": true}
	to retry, use: --limit @/home/tomk/wpex/trellis/dev.retry

PLAY RECAP *********************************************************************
default                    : ok=1    changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Please describe your local environment:**

Ansible version: 2.2.1.0

OS: Ubuntu Trusty 14.04

Vagrant version: 1.9.1

OpenSSH client version:

```
$ ssh -V 
OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8, OpenSSL 1.0.1f 6 Jan 2014
```

**Where did the bug happen? Development or remote servers?**

local

**Comment by fullyint** [comment]
Thanks @t0mk 

Would love it if you would test #769 

Till #769 (or other) is merged, you could disable the ssh client validation:

```yml
# group_vars/all/main.yml
validate_ssh: false
```

**Comment by t0mk** [comment]
@fullyint thanks. I will for sure test the PR tomorrow, it's way less effort than upgrading my laptop to Ubuntu 16.04, haha.
