### ISSUE TITLE
FastCGI caching on Multisite borked

### ISSUE THREAD

**Issue by nathanielks** [roots/trellis#772]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [ ] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**

Subsites on a subdomain multisite install are having caching enabled in the WP Admin, which should be disabled.

**What is the expected or desired behavior?**

No caching in the WP Admin

---

## Bug report

**Please provide steps to reproduce, including full log output:**

Install subdomain multisite with caching enabled.

**Please describe your local environment:**

Ansible version: 2.2.0

OS: 10.12.3

**Where did the bug happen? Development or remote servers?**

Remote

---

I'm testing this as we speak to see what's going on.

**Comment by nathanielks** [comment]
I've added a `Skip-Cache` header with the value of the `$skip_cache` variable. Technically, the `Fastcgi-Cache` header will tell me if the cache is enabled or disabled (it'll read `bypass` if it's disabled), but I added `Skip-Cache` for giggles.

What's particularly curious is the `Skip-Cache` header isn't being sent on subsites? 🤔  `Fastcgi-Cache` is being sent, but why not `Skip-Cache`?

**Comment by nathanielks** [comment]
You know, I wonder if nginx doesn't send headers with falsey values...

**Comment by greatislander** [comment]
My theory is that it has to do with this block:

https://github.com/roots/trellis/blob/master/roles/wordpress-setup/templates/wordpress-site.conf.j2#L32-L48

If the caching configs are excluding the conventional (by Trellis standards) admin path of `/wp/wp-admin/`, would the rewrite to `/wp-admin/` here break that configuration?

**Comment by nathanielks** [comment]
@greatislander I don't _think_ so because /wp-admin/network/ gets the caching applied just fine 🤔 

Another way to test this theory is to look at a subdirectory install I think...

**Comment by nathanielks** [comment]
The real kicker is https://github.com/roots/trellis/blob/master/roles/wordpress-setup/templates/wordpress-site.conf.j2#L93-L95 should cause caching to be disabled because the logged in cookie is present. That's the primary reason why I don't think it's rewrite-related.

**Comment by nathanielks** [comment]
re the /wp-admin/network/ comment: this gets rewritten to /wp/wp-admin/network/ behind the scenes

**Comment by nathanielks** [comment]
Ok, doubly weird: `$skip_cache` isn't being set for subdomains _at all_. I tested this using a very scientific method:

```
map $skip_cache $boogers {
  0 aw-poo;
  1 hooray;
}
server {
// skip some stuff
add_header Boogers $boogers;
// rest of the config
```

I then moved `$skip_cache` before and after the conditionals to see how it would behave on the root multisite network I knew it was working on. I was able to get the `Boogers` header to read both `hooray` and `aw-poo`. I was _not_ able to get this to work on a subdomain. It's almost as if it's reading another config file, but there isn't one? 🤔

**Comment by nathanielks** [comment]
Tested against a subdirectory site and it's applying the cache where it shouldn't either 😐

**Comment by nathanielks** [comment]
Current acting theory: `fastcgi_cache` is _always_ applied when the uri ends in `.php`

**Comment by nathanielks** [comment]
Testing on a vanilla single-site install, everything works as expected 😞

**Comment by nathanielks** [comment]
PHEW, I'm not crazy. Vanilla multisite install and the cache is hitting when it shouldn't 👍

**Comment by nathanielks** [comment]
The `.php` theory isn't 100% accurate... they work on the root blog, but not on sub-blogs.

**Comment by nathanielks** [comment]
More specifically, I tested `/wp/wp-admin/edit.php` on the root blog and it sends `Fastcgi-Cache: BYPASS`, but not on sub-blogs

**Comment by nathanielks** [comment]
Still trying to make sense of the logic behind which urls get cached and not:
```
http://example.dev/wp/wp-admin/: BYPASS
http://example.dev/wp/wp-admin/edit.php: BYPASS
http://example.dev/wp-admin/edit.php: HIT
http://example.dev/boogers/wp-admin/edit.php: HIT
http://example.dev/wp-admin/network/themes.php: HIT
http://example.dev/wp-admin/testing.php: HIT
http://example.dev/wp/wp-admin/testing.php: BYPASS
http://example.dev/boogers/wp-admin/testing.php: MISS
```

the `testing.php` file is to remove WordPress as a possible culprit:
```php
<?php

echo 'testing';
```

**Comment by nathanielks** [comment]
To reiterate: this doesn't make any sense because the WordPress logged in cookie is present, so _none_ of these should be hitting a cache.

**Comment by nathanielks** [comment]
turns out @greatislander was on to something! I moved the conditionals _before_ the rewrite block and it made a subdirectory install work as expected! Now to test a subdomain install

**Comment by nathanielks** [comment]
yup, that fixed it for subdomains as well!
