### ISSUE TITLE
mysql server: always restarted

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#775]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

MySQL Server restarts with each ansible-playbook run.
````
[...]
TASK [mariadb : Restart MySQL Server] ******************************************
changed: [web]
[...]
PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0
web                          : ok=92   changed=1    unreachable=0    failed=0
````

**What is the expected or desired behavior?**

MySQL Server restarts only when it makes sense 
(e.g. its config changed in a way that requires a full restart of it).

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

X Run ansible-playbook (staging)

**Please describe your local environment:**

Ansible version: 2.2.1.0

OS: Ubuntu 16.04.2 LTS

Vagrant version: 1.9.1

**Where did the bug happen? Development or remote servers?**

X Development

**Comment by swalkinshaw** [comment]
I guess we could modify the restart task to act as a handler.

Right now it's:

```yaml
  - name: Restart MySQL Server
    service:
      name: mysql
      state: restarted
      enabled: true
```

/cc @fullyint
