### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by salasmx** [roots/trellis#778]
## Submit a feature request or bug report

- [ X ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [ X ] This is a bug report
- [ X ] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [ X ] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

Every time I save changes from sage theme the response on the browser is a 502 Bad Gateway, so I have to reload vagrant (again and again) in order to reestablish my dev-env until nothing "fix the problem" and I need to reinstall trellis and bedrock again.

---

**Please describe your local environment:**

Ansible version: 2.2.1.0

OS: macOS Sierra 10.12.3

Vagrant version: 1.9.1

**Where did the bug happen? Development or remote servers?**

Development

**Comment by swalkinshaw** [comment]
Maybe try with another theme and see if it happens? You'd at least know if it's Sage or Trellis related issue.

Either way, this is more a support question for https://discourse.roots.io/. Maybe someone else has experienced this and can help.
