### ISSUE TITLE
Download WP-CLI fails in first ansible playbook run

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#781]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**

Task "Download WP-CLI" fails when ansible playbooks runs the first time, it was OK in the next run.
````
TASK [wp-cli : Download WP-CLI] ************************************************
System info:
  Ansible 2.2.1.0; Linux
  Trellis at "Allow for per-project packagist.com authentication"
---------------------------------------------------
Request failed
fatal: [web]: FAILED! => {"changed": false, "dest": "/tmp/wp-cli-1.1.0.phar", "failed": true, "response": "HTTP Error 500: Internal Server Error", "state": "absent", "status_code": 500, "url": "https://github.com/wp-cli/wp-cli/releases/download/v1.1.0/wp-cli-1.1.0.phar"}
````

**What is the expected or desired behavior?**

Task "Download WP-CLI" doesn't fail in first run.

---

## Bug report

**Please describe your local environment:**

Ansible version: 2.2.1.0

OS: Ubuntu 16.04.2 LTS

**Where did the bug happen? Development or remote servers?**

Remote

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

**Comment by swalkinshaw** [comment]
This was probably due to the AWS S3 outage today. Either way, that's a problem downloading from github's site, not a Trellis issue. We can't control every external site.
