### ISSUE TITLE
Allow customizing the default site's Nginx configuration

### ISSUE THREAD

**Issue by medfreeman** [roots/trellis#786]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a feature request
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**

While provisioning a server, the default site configuration is copied from [h5bp/server-configs-nginx no-default](https://github.com/h5bp/server-configs-nginx/blob/master/sites-available/no-default).
It is not editable by using a [child template](https://roots.io/trellis/docs/nginx-includes/#child-templates).

**What is the expected or desired behavior?**

The desired behavior is to be able to possibly override the default site configuration using a child template.

---

## Feature Request

**Please provide use cases for changing the current behavior:**

- Setting up a basic health check on an EC2 instance for Amazon ELB (Elastic Load Balancer), which fails since the default configuration drops requests with no host header, and that's what elb health checks do.
- Specific health checks for monitoring software (it can make sense if the machine is hosting more than one site, the number of sites is subject to changes)
- Showing a page when the server is accessed by ip
- Redirecting to an url when the server is accessed by ip

**Other relevant information:**

I already have a PR to submit if you think it is an interesting feature.

Thanks for your work !!

**Comment by swalkinshaw** [comment]
Seems useful since we'd like to encourage people to have better setups with load balancers (even though in this case it seems ELB is kind of broken).

What was your solution for the PR?

@fullyint came up with an idea to add an additional `nginx_sites_available_templates` variable which is an array that we'd just call `with_items` on to generate templates. By default it would contain `no-default.conf`.

Anyone could re-define that variable and add on their own templates or remove that one.

**Comment by medfreeman** [comment]
Ok nice !

It seems @fullyint solution covers a wider range of uses, i think it would be better than mine.

What i did:
  - roles/nginx/defaults/main.yml -> add ```nginx_default_server_conf: no-default.conf.j2```
  - create roles/nginx/templates/no-default.conf.j2 -> based on h5bp no-default config
    ```
# {{ ansible_managed }}

# Drop requests for unknown hosts
#
# If no default server is defined, nginx will use the first found server.
# To prevent host header attacks, or other potential problems when an unknown 
# servername is used in a request, it's recommended to drop the request 
# returning 444 "no response".

server {
  listen 80 default_server;

  {% block server_body %}{% endblock %}

  {% block http_return_code -%}
  return 444;
  {% endblock %}

}
    ```

  - roles/nginx/tasks/main.yml -> replace 'Enable better default site to drop unknown requests'
    ```
- name: Enable better default site to drop unknown requests
  template:
    src: "{{ nginx_default_server_conf }}"
    dest: "{{ nginx_path }}/sites-enabled/no-default.conf"
  notify: reload nginx
  tags: nginx-includes
    ```

- How i use it:
  - group_vars/all/main.yml -> add ```nginx_default_server_conf: nginx-includes/no-default.conf.child.j2```
  - create nginx_includes/no-default.conf.child.j2 ->
```
{% extends 'roles/nginx/templates/no-default.conf.j2' %}

{% block server_body -%}
  root  {{ www_root }};

  location = /health-check.php {
    # code to invoke php
    # but no redirection code
    try_files $uri =404;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    fastcgi_param DOCUMENT_ROOT $realpath_root;
    fastcgi_pass unix:/var/run/php-fpm-wordpress.sock;
  }
{% endblock %}

{% block http_return_code -%}
  location ~ / {
    return 444;
  }
{% endblock %}
```

  - In this specific case, i also created a new role (referenced on server.yml) that creates the 'health-check.php' file from a template, into www_root ('/srv/www/' on remote hosts), but this is out of the scope of this enhancement.

  - Set up the health check url on the elb to '/health-check.php'

**Comment by swalkinshaw** [comment]
That solution is good also, but agreed the general one is probably more useful.

Do you want to do a PR for it?

**Comment by medfreeman** [comment]
Sure,
i'll do this today or tomorrow.

**Comment by medfreeman** [comment]
Ok i managed to do something clean, basically @fullyint idea.

But i chose to have a 'nginx-sites-available' template folder, automatically copied to the host's sites-available folder, that auto cleans up in case you delete templates in the future.

And a 'nginx_sites_enabled_templates' array that symlinks the requested sites, removes sites templates no more defined, and cleans broken symlinks.

It has the added benefit of having some available but not enabled sites for whatever needed reason.
But unfortunately this approach requires being able to find broken symlinks, but symlinks don't register to the path module in the current version.

The commit that would fix this is [here](https://github.com/ansible/ansible/commit/85f6c26dfff53a0e71a0e983e89943781a0c4cd4), but won't be available until ansible 2.3 (as stated in the [docs](http://docs.ansible.com/ansible/find_module.html)), which has no release date.
Should i perhaps revert in the meantime to a simpler approach where the files are templated directly to sites_enabled without using symlinks ?

**Comment by medfreeman** [comment]
I meant symlinks are ignored by the 'find' module, not 'path'.

**Comment by medfreeman** [comment]
Finally i kept the announced behavior, but made sure to prune unmanaged sites-enabled files before pruning sites-available, thus avoiding the problem of broken symlinks not registering to ansible 'path' module.
I find the whole code a bit long, but didn't know how to do it better while keeping things simple for the user.
Comments completely welcome on the approach.

**Comment by medfreeman** [comment]
So with the PR, here's the revised addition of an elb health check template:

* group_vars/all/main.yml -> add

```
nginx_sites_enabled:
  - default-elb-health-check
```

* create nginx-sites-available/default-elb-health-check.conf.j2 ->

```
# {{ ansible_managed }}

# Drop requests for unknown hosts
#
# If no default server is defined, nginx will use the first found server.
# To prevent host header attacks, or other potential problems when an unknown 
# servername is used in a request, it's recommended to drop the request 
# returning 444 "no response".

server {
  listen 80 default_server;

  root  {{ www_root }};

  location = /health-check.php {
    # Amazon ELB php health check
    # code to invoke php
    # but no redirection code
    try_files $uri =404;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    fastcgi_param DOCUMENT_ROOT $realpath_root;
    fastcgi_pass unix:/var/run/php-fpm-wordpress.sock;
  }

  location ~ / {
    return 444;
  }

}
```

* In this specific case, i also created a new role (referenced on server.yml) that creates the 'health-check.php' file from a template, into www_root ('/srv/www/' on remote hosts), but this is out of the scope of this enhancement.

* Set up the health check url on the elb to '/health-check.php'

**Comment by medfreeman** [comment]
Usage didn't change with this PR.

**Comment by medfreeman** [comment]
So with this new PR, here's the revised addition of an elb health check template:

* group_vars/all/main.yml -> add

```
nginx_default_site_enabled: false
nginx_sites_enabled:
  - nginx-includes/default-elb-health-check.conf.j2
```

* create nginx-includes/default-elb-health-check.conf.j2 ->

```
# {{ ansible_managed }}

# Drop requests for unknown hosts
#
# If no default server is defined, nginx will use the first found server.
# To prevent host header attacks, or other potential problems when an unknown 
# servername is used in a request, it's recommended to drop the request 
# returning 444 "no response".

server {
  listen 80 default_server;

  root  {{ www_root }};

  location = /health-check.php {
    # Amazon ELB php health check
    # code to invoke php
    # but no redirection code
    try_files $uri =404;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    fastcgi_param DOCUMENT_ROOT $realpath_root;
    fastcgi_pass unix:/var/run/php-fpm-wordpress.sock;
  }

  location ~ / {
    return 444;
  }

}
```

* In this specific case, i also created a new role (referenced on server.yml) that creates the 'health-check.php' file from a template, into www_root ('/srv/www/' on remote hosts), but this is out of the scope of this enhancement.

* Set up the health check url on the elb to '/health-check.php'

**Comment by medfreeman** [comment]
side note about usage:
perhaps name the file 'nginx-includes/default-elb-health-check.conf.site.j2' (adding '.site' extension) instead of 'nginx-includes/default-elb-health-check.conf.j2', thus avoiding the file being templated to nginx includes.d directory (trellis only templates files ending in .conf.j2 to the includes.d directory).

**Comment by medfreeman** [comment]
So with this new PR, here's the revised addition of an elb health check template:

* group_vars/all/main.yml -> add

```
nginx_sites_confs:
  - src: no-default.conf.j2
    enabled: false
  - src: nginx-includes/default-elb-health-check.conf.site.j2
```

* create nginx-includes/default-elb-health-check.conf.site.j2 ->

```
# {{ ansible_managed }}

# Drop requests for unknown hosts
#
# If no default server is defined, nginx will use the first found server.
# To prevent host header attacks, or other potential problems when an unknown 
# servername is used in a request, it's recommended to drop the request 
# returning 444 "no response".

server {
  listen 80 default_server;

  root  {{ www_root }};

  location = /health-check.php {
    # Amazon ELB php health check
    # code to invoke php
    # but no redirection code
    try_files $uri =404;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    fastcgi_param DOCUMENT_ROOT $realpath_root;
    fastcgi_pass unix:/var/run/php-fpm-wordpress.sock;
  }

  location ~ / {
    return 444;
  }

}
```

* In this specific case, i also created a new role (referenced on server.yml) that creates the 'health-check.php' file from a template, into www_root ('/srv/www/' on remote hosts), but this is out of the scope of this enhancement.

* Set up the health check url on the elb to '/health-check.php'

**Comment by medfreeman** [comment]
Is it ok like this, by adding 'nginx-includes/default-elb-health-check.conf.site.j2' (adding '.site' extension before '.j2') in order for the conf file not to be also templated to 'nginx/includes.d' remote folder ?

I'm asking this because i'd like to take a stab at adding the feature to the [nginx-includes doc](https://github.com/roots/docs/blob/docs/trellis/nginx-includes.md).
It is similar to the child configuration examples, where one has to add the '.child' suffix to the file names, in order for them not to be also templated to the includes.d folder.
I know i shouldn't explain why, but just wanting to be consistent with the docs and previous features, while not complicating [this line](https://github.com/roots/trellis/blob/8666765785aa799cb6828dccf9c6f846eb975cba/roles/wordpress-setup/tasks/nginx-includes.yml#L7) with each exception.

**Comment by medfreeman** [comment]
Ok, i reread the docs properly, and the thing with adding a suffix ('.child' for child templates) while using 'nginx-includes' folder OR using another folder to avoid files being templated to includes.d, is properly explained in the docs ([here at the end of the line](https://github.com/roots/docs/blame/2638a1a4d6ed335ced9a4fee3a8f4a348ea2fbff/trellis/nginx-includes.md#L93)).
So my approach seems be ok, i'll base my doc addition on the actual one anyway.
