### ISSUE TITLE
Deprecated role

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#794]
The ferm role will be deprecated very soon, see: https://github.com/nickjj/ansible-ferm

The role has moved to debops playbooks repository:
https://github.com/debops/debops-playbooks/blob/master/playbooks/service/ferm.yml

**Comment by swalkinshaw** [comment]
This has come up before. That deprecation notice also hasn't changed since 2014. We didn't switch to new one because of GPL license although it might be fine if we just use it through Galaxy.
