### ISSUE TITLE
Leverage browser caching / h5bp basic config

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#800]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

Related to old PR discussion/comment https://github.com/roots/trellis/pull/37#issuecomment-53863182 .

Google PageSpeed Insights recommends (and gives a higher score for) 
[leveraging browser caching](https://developers.google.com/speed/docs/insights/LeverageBrowserCaching), notably for static files.

Trellis already uses h5bp nginx server config and it also offers 
[basic configuration](https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/basic.conf), useful for static files, notably [expiry](https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/location/expires.conf).

Note: Including this extra config can cause some side effects with the PHP related routing, see https://github.com/h5bp/server-configs-nginx/blob/master/doc/common-problems.md.

**Comment by swalkinshaw** [comment]
The original concern was that we can't guarantee assets that are included on a page contain cache busting information.

I guess if anyone uses the `wp_enqueue` methods, then they contain the version by default? Not entirely sure how trust worthy this is, or if we can assume people alway use those functions or some other method.

**Comment by mAAdhaTTah** [comment]
> I guess if anyone uses the wp_enqueue methods, then they contain the version by default?

Yes, version of WP if nothing is set, otherwise the string provided to the version parameter.

**Comment by swalkinshaw** [comment]
Should be noted that anyone can add this config by using Nginx include/child templates.

**Comment by strarsis** [comment]
Are there any plans for adding this in near future? It is also a handy way improving the PageSpeed score.

**Comment by swalkinshaw** [comment]
Nope. My original concern still stands and this can easily be done by anyone that needs it.

**Comment by strarsis** [comment]
One way to solve this could be by using a plugin that enforces cache busting parameters on all resources like [Busted](https://wordpress.org/plugins/busted/) .

**Comment by swalkinshaw** [comment]
Seems useful but Trellis can't depend on a specific WP plugin.

**Comment by strarsis** [comment]
I agree with this and will include the h5bp config file myself.
