### ISSUE TITLE
Add subdomains and all canonical names to self-signed certificates

### ISSUE THREAD

**Issue by medfreeman** [roots/trellis#809]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a feature request
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**

Self-signed certificates are only generated for the main domain canonical host name in a multisite subdomain installation.

**What is the expected or desired behavior?**

Self-signed certificates are generated for the main domain canonical host name, all other canonical host names, and wildcard entries.

---

## Feature Request

**Please provide use cases for changing the current behavior:**

A few reasons:
  - consistency with letsencrypt
  - simplifying redirection testing in complex scenarios (by avoiding adding exceptions for each subdomain)
  - simplifying development for teams with a lot of subsites (in a client's doc i have a few steps guide, ~ 4
terminal commands, to add the certs to the trust store in ubuntu and macOS, and avoid further exceptions, sites show as valid)
  - using browsersync in theme development (it needs to have the self-signed cert for the refresh to happen, i've added a dev.yml task that changes the permission of certs, allowing browsersync to read them)

**Other relevant information:**

Previous positions:
[Comment on Allow auto-generation of self signed SSL certificate. PR](https://github.com/roots/trellis/pull/279#issuecomment-122674423)

**Implementation**

Move [Get list of hosts in current Nginx conf](https://github.com/roots/trellis/blob/32a078ab09ea1fbe25f4daf1319b2a234e233242/roles/letsencrypt/tasks/nginx.yml#L7-L14) letsencrypt task to the `common` role, in a specific task.

Include it in letsencrypt and self-signed certs tasks.

Include the main domain canonical host name, the other canonical host names, and the wildcard entry as DNS subjectAltNames entries, as explained [here](http://blog.endpoint.com/2014/10/openssl-csr-with-alternative-names-one.html) like @swalkinshaw stated previously.
Down in this article's comments, there's a [link to an online certificate request generator](https://certificatetools.com/) that provides a clean one-liner (in `OpenSSL command (Linux)` after submitting the form).
Though it misses the point of also having ([as stated here](http://blog.endpoint.com/2014/10/openssl-csr-with-alternative-names-one.html?showComment=1414727230063#c5347857091415121519)) the main domain name as first DNS subjectAltName.

i.e. resulting command
```
openssl req -new -newkey rsa:2048 -nodes -sha256 -subj "/CN=www.test.com" -config <(
cat <<-EOF
[req]
req_extensions = req_ext
[ req_ext ]
subjectAltName = @alt_names
[alt_names]
DNS.1 = www.test.com
DNS.2 = test.com
DNS.3 = *.test.com
EOF
)
```

Side note: i understand that some issues can be viewed as (and are sometimes) corner cases, but i've stumbled on an important number of them on a single project. Since i know i'll encounter part of the same problems in subsequent projects (and obviously different ones), imho the most *sensible* approach for me is to try including them in trellis (especially with this one that is transparent to most users, and matches what i thought trellis would do by itself). Or facing maintenance hell.

**Comment by medfreeman** [comment]
It seems it is better to duplicate [Get list of hosts in current Nginx conf](https://github.com/roots/trellis/blob/32a078ab09ea1fbe25f4daf1319b2a234e233242/roles/letsencrypt/tasks/nginx.yml#L7-L14) task since the `when` conditions are different.

**Comment by medfreeman** [comment]
It seems i was a bit fast on the method again.
I now understand that the approach used in [let's encrypt challenge generation](https://github.com/roots/trellis/blob/32a078ab09ea1fbe25f4daf1319b2a234e233242/roles/letsencrypt/tasks/nginx.yml#L7-L14) is not relevant here, because it's sole use is to then make a difference with already existing challenge confs in a simple way.

Better to use `site_hosts` with an union of wildcard entries generated 
 from `canonical hosts`, without the `www` prefix, as in (my previous issue)[https://github.com/roots/trellis/issues/806].

**Comment by fullyint** [comment]
@medfreeman Such valuable research and explanation. Thank you.

This isn't my area of expertise so I'll defer to @swalkinshaw, but after considering your notes, I'd vote "yes" for a PR adding all domains/subdomains to SAN for self-signed certs.

I also agree with your latest implementation note:
>Better to use `site_hosts` with an union of wildcard entries generated
from `canonical hosts`, without the `www.` prefix, as in [my previous issue](https://github.com/roots/trellis/issues/806).

**Comment by swalkinshaw** [comment]
Seems useful 👍
