### ISSUE TITLE
Purpose of cert ID (also in filename)

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#826]
What is the purpose of the cert ID and why is it also used in the file name?
https://github.com/roots/trellis/blob/master/roles/letsencrypt/templates/renew-certs.py#L14
Some programs require a path to the cert and a changing ID (it changed for me suddenly for unknown reasons, probably config changes) would require steady readjusting the path to the new (current) cert file.

**Comment by strarsis** [comment]
@swalkinshaw: Thanks!
Some programs only support a path to a single file which is a problem when the cert ID changes in the file name. It would be a nice addition to add a "-current" cert file which is just a copy of the current cert. A soft symlink also doesn't always work (some programs don't support resolving soft symlinks either).

**Comment by swalkinshaw** [comment]
@fullyint is it possible to easily create a file with a static filename each time?

@strarsis the whole point for the cert ID was to easily support regenerating a certificate when the underlying context changes (like a domain).

**Comment by fullyint** [comment]
option in #834

**Comment by swalkinshaw** [comment]
Fixed by https://github.com/roots/trellis/pull/834
