### ISSUE TITLE
Add error_page 404 to cross-domain-fonts config

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#831]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**
Requests for URLs to files with font file extension result in nginx 404 instead WordPress site 404.

**What is the expected or desired behavior?**

WordPress handles the 404 instead.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

Request an URL to file with font file extension (e.g. `/font.ttf`).

## Fix
h5bp nginx documents a solution (see https://github.com/h5bp/server-configs-nginx/blob/master/doc/common-problems.md#define-error_page-in-each-location-block) 
by inserting `error_page 404 = /index.php;` into the location block(s).

**Comment by swalkinshaw** [comment]
I guess we'd have to define our own template for this then instead of just including h5bp's.

**Comment by strarsis** [comment]
Related issue: https://github.com/h5bp/server-configs-nginx/issues/176

**Comment by strarsis** [comment]
@swalkinshaw, @fullyint: 
From the related issue (https://github.com/h5bp/server-configs-nginx/issues/176#issuecomment-299652588):

> [...]
Re the problem that brought you here - I suggest using a 404 front controller - it's much less intrusive and matches how wordpress (or almost any cms) actually works.

Such a setup is described also in the h5bp nginx docs: https://github.com/h5bp/server-configs-nginx/blob/master/doc/common-problems.md#change-to-use-a-404-front-controller

Does it make sense to create a new issue for this, changing the current config to 404 font controller style?

**Comment by swalkinshaw** [comment]
Not exactly sure how that solution applies here. Does it let us continue to use the h5bp config unmodified? If so, yeah that sounds like a good change.

**Comment by strarsis** [comment]
Yes, with this 404 frontcontroller setup the original files wouldn't have to be modified.

**Comment by swalkinshaw** [comment]
Cool 👍 PR would appreciated
