### ISSUE TITLE
Slow watch with nfs

### ISSUE THREAD

**Issue by iwfmp** [roots/trellis#833]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a feature request
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---
## Feature Request

**What is the current behavior?**

I've been using vagrant for local development
using `gulp watch` I encounter a VERY long pause until changes are actually computed.

**What is the expected or desired behavior?**

Reading a bit about it I found this:
https://www.jverdeyen.be/vagrant/speedup-vagrant-nfs/
Trying it manually proved very efficient

I suggest to have the additional `mount_options` as default in the Vagrantfile
and also the `cachefilesd` applied in the VM itself

**Comment by swalkinshaw** [comment]
Vagrant + NFS is so hard to performance tune so I'd welcome anyone testing various options with benchmarks. Otherwise I'm hesitant to change defaults.
