### ISSUE TITLE
Vagrant ssh

### ISSUE THREAD

**Issue by OLFASALAH** [roots/trellis#835]
I try to install a devstack openEDX when i execute the command  vagrant ssh,it cause a" runTime error: please install the vagrant plugin" I installed the plugin correctly  with this command:"vagrant plugin install vagrant-vbguest" but this error still exists .
Any idea please

**Comment by scherii** [comment]
Please use https://discourse.roots.io/c/trellis for support. GitHub issues are for bug reports and feature requests only, as stated in the template you deleted. 😏 😉
