### ISSUE TITLE
[feature] add ssh key of host to trellis VM for windows user (for ssh forwarding to work)

### ISSUE THREAD

**Issue by dheerajbhaskar** [roots/trellis#839]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

This refers to the First time use of trellis on windows

1. You need `vagrant up`
2. you need to `vagrant ssh`, add your public key to the `authorized_keys`
3. logout and login with your ssh key
4. Then check ssh-forwarding

**What is the expected or desired behavior?**

1. `vagrant up` and your public key is already in authorized_keys

## Feature Request

(delete this section if not applicable)

**Please provide use cases for changing the current behavior:**

Existing project, new developer:
1. developer pulls trellis code base, does `vagrant up` and his keys are added so he's ready to go

PS: deploy, pull, push rights on developer's key, so this is handy

New Project:

1. clones trellis repo, and `vagrant up` and start working

**Other relevant information:**

Ansible doesn't work on windows, we need a VM. Making it a little more easy to use the VM would go a long way

**Comment by dheerajbhaskar** [comment]
I can work on a pull request if a contributor /maintainer says this is in scope

**Comment by dheerajbhaskar** [comment]
Based on https://github.com/roots/trellis/issues/654#issuecomment-280079858 I guess this would be a welcome PR?

PS: This was in reply to: https://github.com/roots/trellis/issues/654#issuecomment-279535314

**Comment by swalkinshaw** [comment]
I refreshed my memory a little and it seemed like @discopatrick had an [idea](https://github.com/roots/trellis/issues/654#issuecomment-280360115):

> add a dynamic inventory script called hosts/development which looks for the generated inventory file and, if it exists, outputs an exact copy of that inventory - otherwise, outputs an empty inventory. Writing dynamic inventory scripts is documented here: http://docs.ansible.com/ansible/dev_guide/developing_inventory.html. This solution will allow the feature to work in Trellis "out of the box" while avoiding the above error, and I think will provide the best user experience.

Is this an alternative to that? What are the pros/cons?

**Comment by QWp6t** [comment]
This isn't actually necessary. Not saying I'm against it, but it's not required. I develop exclusively on Windows, and I've never had an issue with SSH forwarding, nor do I have to add anything to VM's local authentication agent.

See also: https://roots.io/trellis/docs/windows/#ssh-forwarding
