### ISSUE TITLE
Provisioning files --- wordpress-setup: Create database of sites

### ISSUE THREAD

**Issue by cibulka** [roots/trellis#851]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

I've added a new project to my Trellis setup. When I want to re-provision my environment, I get this error (which I've never seen before):

```
TASK [wordpress-setup : Create database of sites] ******************************
System info:
  Ansible 2.2.0.0; Vagrant 1.9.1; Darwin
  Trellis at "Deploys: `--skip-themes` when updating WP `template_root`"
---------------------------------------------------
The conditional check 'site_uses_local_db and item.value.db_create |
default(true)' failed. The error was: {{ site_env.db_host == 'localhost' }}:
{{ wordpress_env_defaults | combine(item.value.env | default({}),
vault_wordpress_sites[item.key].env) }}: |combine expects dictionaries, got
Undefined

The error appears to have been in '/Users/XXXXX/web/trellis/roles
/wordpress-setup/tasks/database.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- block:
  ^ here

fatal: [default]: FAILED! => {"failed": true}
	to retry, use: --limit @/Users/XXXXX/web/trellis/dev.retry
```
I've found an issue at the Roots forum - https://discourse.roots.io/t/server-yml-failing-at-wordpress-setup-create-database-of-sites-after-upgrade-to-0-9-8/7861 - that would suggest, that I've overlooked something in my configuration (`vault_wordpress_sites[item.key].env` is undefined?). 

Everything seems to be set right though:
* `group-vars/development/wordpress_sites` contains an item for the new site
* `group-vars/development/vault.yml` contains an item for the new site
* `.env.example` file on Bedrock's project was renamed to `.env` and added with correct project's

Have I forgotten something? I am probably overlooking something obvious.

**What is the expected or desired behavior?**

Provisioning without problems.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

* Fill in project's config - `group-vars/development/wordpress_sites`, `group-vars/development/vault.yml`, `<PROJECT>/.env`
* hit `vagrant reload --provision` - some projects already exist on the environment and work without problems

**Please describe your local environment:**

Ansible version: 2.2.0.0

OS: OSX 10.12.6

Vagrant version: 1.9.1

**Where did the bug happen? Development or remote servers?**

Development

**Please provide a repository or your `wordpress_sites` config (if possible):**

**wordpress_sites**

```
  other-site.com
    site_hosts, etc., ...
  nest.cz:
    site_hosts:
      - canonical: nest.dev
        redirects:
          - www.nest.dev
    local_path: ../nest.dev
    admin_email: cibulka.me@gmail.com
    admin_user: cibulka
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
```

**vault**

```
# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: devpw

# Variables to accompany `group_vars/development/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  other-site.com
    admin_password: XXX
    env:
      db_password: XXX
  nest.cz:
    admin_password: XXX
    end:
      db_password: XXX
```

**.env**

```
DB_NAME=nest
DB_USER=nest
DB_PASSWORD=XXX

# Optional variables
# DB_HOST=localhost
# DB_PREFIX=wp_

WP_ENV=development
WP_HOME=http://nest.dev
WP_SITEURL=${WP_HOME}/wp

# Generate your keys here: https://roots.io/salts.html
AUTH_KEY='&/,_+M)2FKGg6B:u6=iq^z2IGayr7DYE@t4D5ZD]V2?)N.U(vlzZP`qf2LI>I?F2'
SECURE_AUTH_KEY='rrJGsvI:a`,P8G)2RQcH=(1Uijw/rS:vxOpNQ?[lzSz^H86B+PI1XIjd7((+Ik)['
LOGGED_IN_KEY='_E55<y!A*EkyI{UZQQbx+YO)g{N*Wp]va`xS{}NOSak=Ve_ZvL`JXI7D6L*3^Hh6'
NONCE_KEY='1lUpXdU<qBnrO{q{E>j)s;(Nj_mS1ZpvVKTf|:PMUB}/vRF6|iaSd=mz#uGoS^`7'
AUTH_SALT='ZRT3>$M3TY2[}N*IqrY<cGRQ#]!58,YiR=z-S&erl/e9dua;NO*yx]3T{<?9}:#8'
SECURE_AUTH_SALT='I{l6%!]Iv5_.|*Yf*ZkTmurX5KaVAkr8[t9/:LGFjP`7yPUg_fqm^Gxd4&ozyGCX'
LOGGED_IN_SALT='0rY9m+zlW*%j)J}oVwJC=p=154Mvl]s(,5jpKramU9G;{5|^kiS-*_j2ORS]TDQq'
NONCE_SALT='l(kwFquBF*gTZ?PYaU)dJr&G,LY=yjlPr;Ak8YE$W1JxFyo]8{:Q=R6EE*d2G{ZX'
```

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

https://discourse.roots.io/t/deploy-failing-at-task-deploy-get-wp-theme-template-root/10017

**Comment by fullyint** [comment]
```diff
  vault_wordpress_sites:
    other-site.com
      admin_password: XXX
      env:
        db_password: XXX
    nest.cz:
      admin_password: XXX
-     end:
+     env:
        db_password: XXX
```
😎 

----

Note that Trellis will create the `.env` file for you (probably overwriting the one you manually created by copying the Bedrock `.env.example`). See default `env` values [in the docs](https://roots.io/trellis/docs/wordpress-sites/#common) or [in trellis](https://github.com/roots/trellis/blob/3ca4166b5cc5a45f842a8720192fc7aa434eb1e4/group_vars/all/helpers.yml#L1-L10).

You can override the default `env` values using your existing `env` section of `vault_wordpress_sites` (for secrets) or add an `env` section to the regular `wordpress_sites` for non secret values, e.g., 
```
wordpress_sites:
  nest.cz:
    ...
    env:
      db_name: nest
      db_user: nest
```

**Comment by cibulka** [comment]
Oh god. Thank you. :) Maybe the provisioning script could look for those kinds of stupid user errors (such as checking the existence of variables)? Or maybe not, I should probably just sleep more.

About `.env` - thanks for clarification, I wasn't sure about that. The overwriting feature is pretty cool! Thanks for a very quick reply.
