### ISSUE TITLE
Trellis even easier - supereasy mode [x] feature request

### ISSUE THREAD

**Issue by MaximPro** [roots/trellis#853]
Hey,

I greatly appriciate that developers came out and created a super fast modern server stack, like it should be!
**GREAT WORK!!** 

I'm not an developer, but more a webdesigner & Brainstormer to get Solutions for my Clients.
We life in a World where everyone wants to have things easy and fast, even without thinking.

Actually I find the setup still a little bit of a hustle everytime, dispite many automations & clever shortcuts already implemented.

Why everyone who wants to use it, must first become almost an server developer?
If you want to turn the light on, you won't become a electritian first and watch 1 hour tutorials to turn it on, don't you? Just push a switch. (just copy & paste a line)

Basically I want to create a server on digital ocean or vultr with just few lines and everything else should be done by a script. 

Why not just do it like easyengine. 2 Lines, Boom, done, you go straight into designing your wordpress page, without 20 Minutes of installing Trellis and all that comes with it on a server.

Why not just do another easier mode to beginn with.
Generate everything by it's own and spit the most important stuff out at the end. Wordpress Login & PW.
Everything else should be done by itself and if we want to change it or see it, we can do that afterwards.
Or with the normal installation process at the beginning.

Not generate all your passwords with an extra password generator and copy it one by one into the settings.
Not manually copy and paste it from here.
https://roots.io/salts.html
And not do the other stuff.

Basically what everyone wants at end of the day is a superfast Wordpress installation with good management and optimization right out of the box!

I would like to have something like this, as a customer of Roots Products.

$ GET TRELLIS +good stuff +cache +optimization (+plugins +theme)
> or even better

$ GET TRELLIS PRO
INSTALL
DONE!

or like here :D https://easyengine.io
But with your server stack & optimizations!

Final Goal would be something like this:
Have a working fast & optimized Website with nice Design.

Go to Vultr/Digital Ocean > deploy new server > drop a line > let it install > have wordpress with all speed & optimization (+most needed plugins)

**Optimal: 1 Click Solution - wich is possible to do these days!**

I know I sound a little bit like a newbie or lazy ass dude, but believe me, I just talk from experience and the real world. Almost every Customer want's it quick and easy or they just leave it!

Why do you think amazon is so successful?
Choose Product > 1 Click > done!

Why google is so successful?
Google > Info > done!
Youtube > clickplay > done!
Gmail > login > done!

Apple?
IOS lol done!
Macbook 2017 lol done!
(at least for me;)

**Ok, you are Roots! You are the cause of how customers get your nice stuff. Hard Mode or Easy Mode?**

Please think about it and add a solution to this - something like easyengine for your customers & webdesigners.

You're great! :)
Make it even greater! :1st_place_medal: 

Thanks alot ♥ and have a great Day :+1: 
Best regards
Maxim

**Comment by swalkinshaw** [comment]
We mostly agree with you and our end goal is to have something as close to a single command process as we can.

Reminder: this is an open-source project that we work on in our spare time for free.
