### ISSUE TITLE
can't clone the repo 

### ISSUE THREAD

**Issue by astrocycles** [roots/trellis#857]
## Submit a feature request or bug report

- [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x ] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

X

**What is the expected or desired behavior?**

X

---

## Bug report

Cloning into 'trellis'...
Permission denied (publickey).
fatal: Could not read from remote repository.
**Please provide steps to reproduce, including full log output:**

X

**Please describe your local environment:**

Ansible version: X

OS: X

Vagrant version: X

**Where did the bug happen? Development or remote servers?**

X

**Please provide a repository or your `wordpress_sites` config (if possible):**

X

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

X

---

## Feature Request

(delete this section if not applicable)

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

X

**Comment by TangRufus** [comment]
What is your command?

Try `git clone https://github.com/roots/trellis.git`

**Comment by umohpyro** [comment]
This works flawlessly, no need for the ssh keys issues

**Comment by QWp6t** [comment]
User error. Check out github support or something, bud.
