### ISSUE TITLE
Feature Request: Add Nginx Brotli

### ISSUE THREAD

**Issue by TangRufus** [roots/trellis#863]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

No Brotli support

**What is the expected or desired behavior?**

Add [Brotli module](https://github.com/google/ngx_brotli) to Nginx

---

## Feature Request

What I have in mind is more less the same as [this article](https://certsimple.com/blog/nginx-brotli):

1. Install ngx_brotli 
2. Load ngx_brotli filter module to nginx
3. Load ngx_brotli static module to nginx
3. Add brotli directives to nginx.conf
4. Compress *.br files during deploy

**Comment by swalkinshaw** [comment]
This isn't really possible right now unfortunately. We don't compile Nginx from source so we can't add compiled modules like these.

There's been some threads on our forum about various modules. Here's an example: https://discourse.roots.io/t/trellis-build-nginx-from-source-ngx-pagespeed-enjoy/6391

The more basic feature request would be: support compiling Nginx from source. Then anyone could specify other modules they want.

**Comment by partounian** [comment]
This guide has some great tips and on top #2 it links a PPA you can use and dynamically link the brotli module which seems like a better idea than compiling. Note: I did not verify the PPA so there may be better alternatives.
https://certsimple.com/blog/nginx-brotli

**Comment by swalkinshaw** [comment]
Nginx just got support for customizing the ppa and package name: https://github.com/roots/trellis/pull/858/files

So you can easily try this yourself now :)

**Comment by partounian** [comment]
Yup I wrote that comment with that PR in mind but I never thought to link it, oops.

**Comment by strarsis** [comment]
@TangRufus: Wouldn't this be included in mod_pagespeed?

**Comment by TangRufus** [comment]
Closed in 2021.

It is 2021. This should be handled by a CDN or similar.
