### ISSUE TITLE
Multiple Trellis Projects at once

### ISSUE THREAD

**Issue by samburgers** [roots/trellis#873]
## Feature Request

Currently, working on multiple Trellis projects at the same time is tricky due to Vagrant ip's clashing. Wonder if something like this would be a good addition to the stack?

https://github.com/oscar-stack/vagrant-auto_network

Cheers

**Comment by TangRufus** [comment]
Maybe native vagrant solution:

https://www.vagrantup.com/docs/networking/public_network.html#using-the-dhcp-assigned-default-route

However, using DHCP make box IP dynamic. Accessing vagrant machine via FTP/mysql become tricky: https://github.com/Chassis/SequelPro

**Comment by kalenjohnson** [comment]
You can use a site's actual URL generally for Sequel Pro, IE `example.dev`.

Originally the hard coded IP's were necessary to make NFS sharing possible. I haven't checked in quite a while but I assume that's still the case.

With the `vagrant.local.yml` file you can change the box's IP, I generally assign a random IP for each project I work on.

**Comment by TangRufus** [comment]
Vagrant 1.4 fixed the DHCP and NFS issues
See: https://github.com/hashicorp/vagrant/pull/2560 and https://github.com/hashicorp/vagrant/pull/2674

Would Trellis consider moving to DHCP (or something like that), so that we can run multiple Trellis vm at the same time?
