### ISSUE TITLE
Feature Request: Add cache busting nginx location block

### ISSUE THREAD

**Issue by TangRufus** [roots/trellis#875]
Nginx location block to cache `http://example.com/wp-content/plugins/abc/xyz.js?ver=1.2.3` for a very long time.

It should cache:
- plugins files
- theme files
- WP core files
- user uploaded files

**Comment by swalkinshaw** [comment]
Just to confirm, you're saying Trellis should have a `location` block which matches *versioned* assets from WP sites?

This has come up here as well: https://github.com/roots/trellis/issues/800

However I never really thought of only matching on a pattern like `?ver=x.x.x` which I *think* should eliminate that concern.

**Comment by TangRufus** [comment]
> you're saying Trellis should have a location block which matches versioned assets from WP sites?

Yes

After a second thought, matching `?ver=x.x.x` won't resolve your concerns in #800 because WP adds its version number if `wp_enqueue_script`'s `$ver` is `false`

> If version is set to false, a version number is automatically added equal to current installed WordPress version.
> https://developer.wordpress.org/reference/functions/wp_enqueue_script/

This will be a problem if we use [Cache-Control: Immutable](https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/)

Question: How we can add `Cache-Control: Immutable` to assets that actually versioned?

**Comment by swalkinshaw** [comment]
> Question: How we can add Cache-Control: Immutable to assets that actually versioned?

It would have to be user supplied? They could provide an Nginx location formatted variable.

**Comment by roots-ladybug** [comment]
Hi @TangRufus,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).

**Comment by franzliedke** [comment]
After being pointed to this issue by running Chrome's Lighthouse audit on my Trellis-powered WP site, I'd like to see this improve as well.

Maybe we can tackle a simple issue first - surely uploads can be hit with a rather generic caching rule, as they aren't versioned?

**Comment by TangRufus** [comment]
Sadly, I dont think of a simple / *pure-Trellis* solution.

One possible solution is to use [busted](https://wordpress.org/plugins/busted/)(or similar) to add `?b-modified=xxxx` to JS & CSS urls. Then, on Nginx, match `?b-modified=xxxx` and add `Cache-Control: Immutable`(or similar).
The key here is not to use `?ver=` to aovid WP core version is added.

----

About `location` block:

It was a mistake when I say adding a Nginx `location` block to match versioned assets URLs. The implementation would probably some `if` within [cache-busting.conf](https://github.com/roots/trellis/blob/f293d7aed7389805ddfe8e69346df5e9d2894de4/roles/nginx/templates/h5bp/location/cache-busting.conf)
See: https://serverfault.com/a/811981

**Comment by franzliedke** [comment]
What about adding a simple far-away expiry date for all files **in the upload directory**? `Immutable` is nice, but as it isn't supported that widely, it shouldn't be the only solution.

**Comment by TangRufus** [comment]
Closed in 2021.

It is 2021. This should be handled by a CDN or or a proxy or similar.
