### ISSUE TITLE
The requested PHP extension ext-soap * is missing from your system

### ISSUE THREAD

**Issue by albertonieto** [roots/trellis#878]
I am installing trellis on a Windows machine and getting this error on `vagrant up`:

```
TASK [wordpress-install : Install Dependencies with Composer] ******************
System info:
  Ansible 2.3.0.0; Vagrant 1.8.6; Linux
  Trellis at "Add ansible_local support for non-Windows"
---------------------------------------------------
Loading composer repositories with package information Installing
dependencies (including require-dev) from lock file Your requirements could
not be resolved to an installable set of packages. Problem 1 - The requested
PHP extension ext-soap * is missing from your system. Install or enable PHP's
soap extension.
failed: [default] (item=mysite.org) => {"failed": true, "item": "mysite.org", "stdout": "Loading composer repositories with package information\nInstalling dependencies (including require-dev) from lock file\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - The requested PHP extension ext-soap * is missing from your system. Install or enable PHP's soap extension.\n\n", "stdout_lines": ["Loading composer repositories with package information", "Installing dependencies (including require-dev) from lock file", "Your requirements could not be resolved to an installable set of packages.", "", "  Problem 1", "    - The requested PHP extension ext-soap * is missing from your system. Install or enable PHP's soap extension.", ""]}
```

I have added the following on my `composer.json` file on `site/composer.json`:

```
"require-dev": {
    "ext-soap": "*"
  },
```

Obviously I am missing something here. Any ideas?

**Comment by swalkinshaw** [comment]
Set `php_extensions_custom` in a group vars file (maybe `group_vars/all/main.yml`:

```yaml
php_extensions_custom:
 - php7.1-soap
```

Then run `vagrant provision`.

**Comment by abhaymaurya** [comment]
Hello everyone, I had same issue. I am running php via xampp and recently I tried installing a Laravel project (Windows). When running `composer install` I ran into this very same issue.
In my case I just had to go to:
C:\xampp\php\php.ini
as thats the config file which gets loaded for php. You can find out yours by running:
php --ini
(I use GitBash for command line operations)
So in my php.ini file I found following line:  
`;extension=php_soap.dll`
I had to remove the ";" from the start of the line as it means commented,
Then running `composer install` went smooth as butter.
Hope it helps some of the fellow devs.
