### ISSUE TITLE
Trellis does not include yarn

### ISSUE THREAD

**Issue by MasonFI** [roots/trellis#897]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ]  This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [ ] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

## Feature Request

Yarn should be installed for VM.

**Please provide use cases for changing the current behavior:**

When using Trellis with Sage 9, yarn is required.

**Comment by MasonFI** [comment]
Oh, I think this requirement is only for Window hosts, because if have Windows, you are running the deploy command from inside the Trellis VM machine.

**Comment by partounian** [comment]
I think node and/or gulp are also missing from the Trellis VM.

**Comment by alexandcote** [comment]
I think you can only add it if you need it 😄

**Comment by QWp6t** [comment]
It's not needed in the VM for Sage, regardless of the host machine.

Also, I don't think BrowserSync would work right from within the VM.

**Comment by eshimischi** [comment]
@QWp6t BrowserSync will work within VM, i have my own trellis with node.js, yarn installation and all good. 

@MasonFI you should look to other ansible roles: node.js and yarn here
[nodejs-role](https://github.com/geerlingguy/ansible-role-nodejs)
[yarn-role](https://github.com/ocha/ansible-role-yarn)
