### ISSUE TITLE
not working customizer with trellis

### ISSUE THREAD

**Issue by 9585999** [roots/trellis#899]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**

I'm using `trellis/bedrock/sage`

Does not work customizer
![img 2017-09-28 0 54 40](https://user-images.githubusercontent.com/16165904/30940296-46cb5b26-a3e9-11e7-8693-b10e08897eab.PNG)

Tried with the theme of **Twenty Seventeen**, also does not work.

I tried running the project `bedrock/sage` on Mamp PRO, everything works as it should.

Therefore, I concluded that the problem is somewhere in the trellis ...

**Comment by greatislander** [comment]
See:

https://discourse.roots.io/t/safari-conflicting-multiple-x-frame-options/10077/5
https://core.trac.wordpress.org/ticket/40020

**Comment by 9585999** [comment]
@greatislander thx.
