### ISSUE TITLE
Performance can be improved dramatically with ioapic

### ISSUE THREAD

**Issue by jdevalk** [roots/trellis#900]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**

No enabling `ioapic` by default.

**What is the expected or desired behavior?**

Enabling it by default.

**Comment by swalkinshaw** [comment]
Closed by https://github.com/roots/trellis/pull/913
