### ISSUE TITLE
DHCP + NFS fails on initial `vagrant up`

### ISSUE THREAD

**Issue by TangRufus** [roots/trellis#902]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

`vagrant up` the first time would give:
```
Unmounting Virtualbox Guest Additions ISO from: /mnt
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
No guest IP was given to the Vagrant core NFS helper. This is an
internal error that should be reported as a bug.
```

**What is the expected or desired behavior?**

It should start up the VM without error.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

`vagrant up` In a freshly cloned trellis repo.

**Please describe your local environment:**

Ansible version: 2.4.0.0

OS: 10.13

Vagrant version: 2.0.0

**Where did the bug happen? Development or remote servers?**

Local machine.

**Other relevant information:**

Related pull requests: #898, #892

**Comment by TangRufus** [comment]
More info: If you have `vagrant up` previously, you won't encounter this issue.

Related vagrant issue: https://github.com/hashicorp/vagrant/issues/7070

Current workaround: Use static IP on initial `vagrant up`, then change it back to `dhcp`

**Comment by swalkinshaw** [comment]
I just tried this again. The one additional step I did which I didn't before when testing was to delete the local `.vagrant`.

Tried twice and both times got stuck at `Installing NFS client...`.

I'm going to revert that PR for now.

**Comment by swalkinshaw** [comment]
Should note I'm using Vagrant 1.9.7

**Comment by TangRufus** [comment]
Culprit: Me not tested the PRs thoroughly. Third bug within a month, i feel ashamed of myself. Sorry guys.

Complicity:
```
 INFO retryable: Retryable exception raised: #<Vagrant::Errors::VirtualBoxGuestPropertyNotFound: Could not find a required VirtualBox guest property:
  /VirtualBox/GuestInfo/Net/1/V4/IP
```
Vagrant tries to [read](https://github.com/hashicorp/vagrant/blob/master/plugins/providers/virtualbox/action/prepare_nfs_settings.rb#L133-L150) this property during before NFS mounting. However, this property is not set on new VM.
Related: https://github.com/hashicorp/vagrant/issues/3792

Should we revert #892 as well? I don't find a good solution to use DHCP without `vagrant up` with static IP first.

**Comment by swalkinshaw** [comment]
It's no big deal 😄 . I'm the one who merged them and supposedly tested too.

I don't mind leaving dhcp support in there... but I guess if it's that broken it might be better to remove it. Let's wait a bit on it for now.

I posted here too looking for input: https://github.com/geerlingguy/drupal-vm/pull/1559#issuecomment-334329486

**Comment by oxyc** [comment]
Seems `vagrant-vbguest` is the culprit https://github.com/dotless-de/vagrant-vbguest/issues/243

See my two comments at https://github.com/geerlingguy/drupal-vm/pull/1559#issuecomment-334756183
