### ISSUE TITLE
H5BP expires conf missing try_files

### ISSUE THREAD

**Issue by retlehs** [roots/trellis#905]
if you enable the h5bp expires conf, the `location` blocks that end up being added to your server conf are missing `try_files`, which results in an nginx 404 message being served instead of the WP 404 template

ref https://github.com/h5bp/server-configs-nginx/issues/174

ref #876

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)

**Comment by dreamon11** [comment]
Same problem here.

Fix this by write this code in nginx-includes/site.conf.child:

`{% block h5bp -%}
  location ~* \.(?:manifest|appcache|html?|xml|json)$ {
    try_files $uri /index.php;
  }
  {{ super() }}
{% endblock %}`

In wordpress_sites.yml:
`nginx_wordpress_site_conf: nginx-includes/site.conf.child`

**Comment by easybi-mv** [comment]
> Same problem here.
> 
> Fix this writing this code in nginx-includes/site.conf.child:
> 
> `{% block h5bp -%} location ~* \.(?:manifest|appcache|html?|xml|json)$ { try_files $uri /index.php; } {{ super() }} {% endblock %}`
> 
> In wordpress_sites.yml:
> `nginx_wordpress_site_conf: nginx-includes/site.conf.child`

block h5bp is no longer available?
