### ISSUE TITLE
Support any PHP + Composer based application

### ISSUE THREAD

**Issue by retlehs** [roots/trellis#914]
with some modifications to trellis we can support more than just a wordpress setup

i've personally modified trellis to support a laravel app and it didn't take too much effort. trellis itself is a very valuable project and it would be nice to be more CMS/app-agnostic out of the box

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)

**Comment by retlehs** [comment]
see #187 for previous initial attempt by @nathanielks

**Comment by inthedeepend** [comment]
I have a fork of Trellis working with Symfony - I'd be happy to contribute on this.

**Comment by partounian** [comment]
I would love this as I am currently tearing up trellis to support my php app.

**Comment by nlemoine** [comment]
Would love to see that happen. There's not many differences between a WordPress and any other PHP application.

**Comment by hemangajmera** [comment]
This one is open from very long time. There are some pull request too which does the work.

@swalkinshaw are you aware what is blocking it?

**Comment by swalkinshaw** [comment]
No I'm not. @retlehs would be the person to ask but it's been so long I'm not sure he'd remember 😓

**Comment by baradhili** [comment]
would be happy to test this @swalkinshaw
