### ISSUE TITLE
Local development server bug

### ISSUE THREAD

**Issue by yudistiraAshadi** [roots/trellis#930]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**

Can't access development server on Google Chrome Browser. It gives me `This site can't be reached`. Able to access on Firefox.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

Fresh installation of the newest Trellis and bedrock

`git clone --depth=1 git@github.com:roots/trellis.git && rm -rf trellis/.git`
`git clone --depth=1 git@github.com:roots/bedrock.git site && rm -rf site/.git`

then i change development's `wordpress_sites.yml` and `vault.yml` (See below)

**Please describe your local environment:**

Ansible version: 2.4.1.0

OS: ubuntu 16.04

Vagrant version: 2.0.0

**Where did the bug happen? Development or remote servers?**

Development

**My `wordpress_sites` and `vault` config:**

```# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  asihsuryani.com:
    site_hosts:
      - canonical: asihsuryani.dev
        redirects:
          - www.asihsuryani.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@asihsuryani.dev
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
```
```# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: devpw

# Variables to accompany `group_vars/development/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  asihsuryani.com:
    admin_password: admin
    env:
      db_password: example_dbpassword
```

---

**Comment by alwaysblank** [comment]
This is probably a result of Chrome (and eventually other browsers) no longer allowing .dev urls because that TLD belongs to google and they're forcing HSTS on it in the browser. More info here: https://medium.engineering/use-a-dev-domain-not-anymore-95219778e6fd

If that's the case, the fix is simple: Just change `.dev` to something else (`.test` seems to be a good choice) and re-provision your stuff.

**Comment by retlehs** [comment]
> Fresh installation of the newest Trellis and bedrock

you're missing the newest trellis which has this fixed (#923)

you can also simply enable SSL on your local dev to get `.dev` working

**Comment by yudistiraAshadi** [comment]
Thank you, it solves my problem! It's weiird tho, i literally used `.dev` on another project like two days ago.

**Comment by brocheafoin** [comment]
> you can also simply enable SSL on your local dev to get .dev working

In case anyone reads this later on, I don't think this would work. SSL on your dev machine will be self-signed. HSTS errors on Chrome 63+ don't allow you to "continue anyway". In theory, you could add the self-signed certificate in your trust store, but I haven't been able to get Chrome to agree with my trust settings when an HSTS error occurs. So your best bet is still to stop using .dev as a TLD for local development.

**Comment by retlehs** [comment]
^^ yeah i was totally wrong with that statement, thanks for following up :)
