### ISSUE TITLE
Add "Assumed Server Specs" to readme

### ISSUE THREAD

**Issue by partounian** [roots/trellis#934]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues) (didn't check)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums.
---

I think this would be great so we know that trellis is/should be optimized for.

**Comment by swalkinshaw** [comment]
Are you currently running Trellis in production? Can you provide us with some specs you've been successfully using?

One reason this was never really spelled out is because we assume pretty low specs. $5-10 Digital Ocean server for example. But we can add that somewhere. It would also belongs in our docs as well.

**Comment by partounian** [comment]
Yes I am running it in production. I have run Trellis on multiple servers on different packages of DO, $5, $10, $15 and $20. Though haven't benchmarked or load tested anything though. They are client servers that I only work on every so often. 

Honestly, I might be overcomplicated/overthinking things as I have that bad habit, however if people are having scaling issues maybe we can have some general "run these commands to find your bottleneck" and then also what values to start adjusting.

**Comment by swalkinshaw** [comment]
> however if people are having scaling issues maybe we can have some general "run these commands to find your bottleneck" and then also what values to start adjusting.

This is very different from assumed server specs though. I'd welcome any contribution to our docs/README with a small note about baseline server specs.
