### ISSUE TITLE
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated.

### ISSUE THREAD

**Issue by runofthemill** [roots/trellis#943]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

```
- extracting geerlingguy.daemonize to /home/vagrant/trellis/vendor/roles/geerlingguy.daemonize
- geerlingguy.daemonize (1.2.0) was installed successfully
    default: Running ansible-playbook...
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [WordPress Server: Install LEMP Stack with PHP 7.1 and MariaDB MySQL] *****
```

**What is the expected or desired behavior?**

No deprecation warning for "`The use of 'include' for tasks`"

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

X

**Please describe your local environment:**

Ansible version: 2.4.2.0

OS: macOS 10.13.3

Vagrant version: 2.0.1

**Where did the bug happen? Development or remote servers?**

Development

**Please provide a repository or your `wordpress_sites` config (if possible):**

N/A

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

No

**Comment by runofthemill** [comment]
I'll try and submit a PR against this to fix in the next few days :)

**Comment by fullyint** [comment]
Thank you for the initiative to look into this. However, the last I looked (in #895) the problematic includes were in an upstream dependency:
>- update `include` to `import_tasks`, `include_tasks` or `import_playbook` ([docs](https://docs.ansible.com/ansible/devel/playbooks_reuse.html) and [docs](https://docs.ansible.com/ansible/devel/playbooks_reuse_includes.html)).
>  This avoids deprecation warning. However, `server.yml` will still show deprecation warning till the composer galaxy role changes these [two `includes`](https://github.com/geerlingguy/ansible-role-composer/blob/1e9c94423584b6eb0e5b4f4cba5d730beb24d822/tasks/main.yml#L54-L58).

The upstream has an open issue: geerlingguy/ansible-role-composer#42

**Comment by runofthemill** [comment]
So it appears!

I see there's an open PR for a partial fix (https://github.com/geerlingguy/ansible-role-composer/pull/43), so hopefully that gets merged soon. Apologies for not seeing your previous note in #895 - I did a search in the repo before submitting the issue, but somehow didn't catch that.

**Comment by abentley** [comment]
It would be really helpful if this message indicated _where_ the includes were.

**Comment by runofthemill** [comment]
@abentley the warning is generated by Ansible, so not really a Trellis issue. You could try running a playbook with `-v/-vv/-vvv` and see if the verbose output identifies where the warning's being triggered?

**Comment by geerlingguy** [comment]
@runofthemill - The composer role fix is merged, will be pushed to a new tag shortly!

**Comment by runofthemill** [comment]
woohoo! thanks @geerlingguy

**Comment by fullyint** [comment]
I forgot to mention (or notice?) another upstream:
* Issue: geerlingguy/ansible-role-ntp#44
* PR: geerlingguy/ansible-role-ntp#46

**Comment by geerlingguy** [comment]
@fullyint NTP is now updated as well; use the 1.6.0 release.

**Comment by fullyint** [comment]
@geerlingguy :star2: Thanks so much!
