### ISSUE TITLE
Adding additional site to setup

### ISSUE THREAD

**Issue by 87pancakes** [roots/trellis#946]
Hi,

I can't add a site to the local development setup and have trellis recognise it.

The only way seems to be to` vagrant destroy` and then` vagrant up`.

Is there a way to add additional sites and keep the local database changes without exporting and reimporting each site?

**Comment by 87pancakes** [comment]
For reference, I've tried the following;

`vagrant reload` & `vagrant provision`

Still doesn't recognise the additional site.

**Comment by 87pancakes** [comment]
Sorry, I don't understand why this was closed.

I'd like to use trellis but if I'm unable to add additional sites and keep DB changes after the VM is created without destroying it and starting again, it doesn't work for what I need.

Having multiple VM's for each site is nonsensical.

**Comment by retlehs** [comment]
sorry, i don't understand why you cleared out the issue template where you would have noted where to go for support. please head over to https://discourse.roots.io/.
