### ISSUE TITLE
Fail on 

### ISSUE THREAD

**Issue by claridgeandco** [roots/trellis#947]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

On vagrant provision this happens.

TASK [common : Verify dict format for apt package component variables] *********
System info:
  Ansible 2.4.1.0; Vagrant 2.0.1; Linux
  Trellis at "Fix `raw_vars` functionality for Ansible 2.4.1"
---------------------------------------------------
The conditional check 'package_vars_wrong_format | count' failed. The error
was: error while evaluating conditional (package_vars_wrong_format | count):
[{% for k,v in package_vars.iteritems() if v | type_debug != 'dict' %}'{{ k
}}',{% endfor %}]: {u'apt_packages_custom': u'{{ apt_packages_custom }}',
u'memcached_packages_custom': u'{{ memcached_packages_custom }}',
u'sshd_packages_default': u'{{ sshd_packages_default }}',
u'sshd_packages_custom': u'{{ sshd_packages_custom }}',
u'php_extensions_custom': u'{{ php_extensions_custom }}',
u'apt_packages_default': u'{{ apt_packages_default }}',
u'php_extensions_default': u'{{ php_extensions_default }}',
u'memcached_packages_default': u'{{ memcached_packages_default }}'}: {u
'openssh-server': u'{{ apt_security_package_state }}', u'openssh-client':
u'{{ apt_security_package_state }}'}: 'apt_security_package_state' is
undefined

The error appears to have been in
'/home/vagrant/trellis/roles/common/tasks/main.yml': line 15, column 3, but
may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Verify dict format for apt package component variables
  ^ here

fatal: [default]: FAILED! => {"failed": true}
        to retry, use: --limit @/home/vagrant/trellis/dev.retry

PLAY RECAP *********************************************************************
default                    : ok=1    changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**What is the expected or desired behavior?**

complete playbook successful

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

Install vanilla trellis - vagrant up - Boom

**Please describe your local environment:**

Ansible version: 2.4.1.0

Win 10

Vagrant version: 2.0.1

**Where did the bug happen? Development or remote servers?**

Dev - Vagrants are inoperative

**Please provide a repository or your `wordpress_sites` config (if possible):**

# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  ael.org.au:
    site_hosts:
      - canonical: ael.test
        redirects:
          - www.ael.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@example.test
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

None

---

**Comment by fullyint** [comment]
Hi @claridgeandco! I'm closing because this looks like the "incomplete updates" scenario discussed on the support forum at https://discourse.roots.io/t/package-vars-wrong-format-error-with-ansible-trellis/10659/2. Could you try out the steps at that link?

If you'd like to discuss further, feel free to post a topic over at discourse.roots.io

If this starts looking more like a bug instead, we can reopen this issue here on the bug tracker.
