### ISSUE TITLE
Vagrant up errors out due to unresolved dependenxy

### ISSUE THREAD

**Issue by pajtai** [roots/trellis#952]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [X] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

```
mkdir example.com && cd example.com
git clone --depth=1 git@github.com:roots/trellis.git && rm -rf trellis/.git\n
git clone --depth=1 git@github.com:roots/bedrock.git site && rm -rf site/.git
sudo vim /etc/hosts
cd trellis
vagrant up
```

results in:

```
Installing plugin vagrant-bindfs
Fetching: vagrant-bindfs-1.1.0.gem (100%)
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-vbguest (= 0.14.2)'
```

**What is the expected or desired behavior?**

Vagrant up doesn't error out and the VirtualBox instance is provisioned.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

X

**Please describe your local environment:**

Ansible version: 2.4.3.0

OS: MacOS 10.13.2

Vagrant version: 2.0.2

**Where did the bug happen? Development or remote servers?**

Local Machine

**Please provide a repository or your `wordpress_sites` config (if possible):**

Full steps to repro are above.

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

**Comment by pajtai** [comment]
Looks like a vagrant plugin configuration issue. Resolved as follows:

```
--- example.com/trellis » vagrant plugin list
vagrant-bindfs (1.1.0)
vagrant-exec (0.5.2)
vagrant-hostmanager (1.8.7)
vagrant-vbguest (0.15.1)
--- example.com/trellis » vagrant plugin uninstall vagrant-vbguest
```
 
Now vagrant up runs. Looks like it was looking for an older version.

**Comment by clondon** [comment]
Hi, I know this is a late entry.  
I have been trying Trellis and Root again after giving up with it a year ago.
I managed to overcome this error 
"Unable to resolve dependency: user requested 'vagrant-hostmanager (= 1.8.7)'" by deleting the _~/.vagrant.d_ folder and running ### vagrant up again.
In this case, vagrant up installed the correct plugins and versions.
It then asks that you run **vagrant up** again and the magic started to happen successfully.

**Comment by kafoso** [comment]
Necro, but still relevant.

I fixed this by manually uninstalling "vagrant-hostmanager". I.e.:

```bash
vagrant plugin uninstall vagrant-hostmanager
```

Running `vagrant destroy` or `vagrant up` should install a working version of "vagrant-hostmanager".

-----

Windows 10 Enterprise version 1809.
Vagrant 2.2.5.
