### ISSUE TITLE
Feature Suggestion : fastcgi_cache_background_update

### ISSUE THREAD

**Issue by inthedeepend** [roots/trellis#961]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [ ] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

FastCGI cache responds as intended by the Trellis defaults.

**What is the expected or desired behavior?**

Users can opt in for `fastcgi_cache_background_update`. 

## Feature Request

**Please provide use cases for changing the current behavior:**

Can dramatically improve response time if serving highly dynamic content is not the highest priority.

**Comment by swalkinshaw** [comment]
Sounds like a good idea.

For reference: http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_cache_background_update

Is this something you could implement?

**Comment by inthedeepend** [comment]
Yep - I'll submit PR shortly.

**Comment by swalkinshaw** [comment]
Closed by https://github.com/roots/trellis/pull/962
