### ISSUE TITLE
push to_env to upstream Ansible

### ISSUE THREAD

**Issue by drzraf** [roots/trellis#965]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

**Please describe your local environment:**

Ansible version: 2.4.3.0

OS: Debian 9

Vagrant version: none

## Feature Request

I would like to deploy bedrock using my own Ansible playbooks (no Trellis).
Having the `to_env` filter built-in inside upstream Ansible would be a nice addition.
Don't you think it would be appropriate to offer a PR to Ansible to include this filter which may be of use for several other PHP-project relying upon phpdotenv?

**Comment by TangRufus** [comment]
Trellis' deploy role already creating `.env` file. What is your use case?

https://github.com/roots/trellis/blob/f948df133c92cf13516c5f0cc00cdde773068e47/roles/deploy/defaults/main.yml#L19-L22

https://github.com/roots/trellis/blob/5199022f772a729e79aa6838cddf1af3ff790579/roles/deploy/tasks/build.yml#L8-L13

**Comment by drzraf** [comment]
I would like to deploy bedrock using my own Ansible playbooks (without Trellis).

**Comment by straight-shoota** [comment]
You don't really need to ask here for adding something to ansible. Just suggest the feature there and if it gets included in ansible, the custom implementation can later be removed from trellis.

**Comment by TangRufus** [comment]
I believe copying the 10 lines form Trellis to your playbook would be the easiest option

**Comment by drzraf** [comment]
Sure, I did. But using a role with ansible-container rather than a playbook, out-of-tree filter is something I'd prefer not to have in the long-run.

**Comment by drzraf** [comment]
This works:

```jinja
- copy:
    dest: ".env"
    content: |
      {% for key, value in site_env %}
          {{ key | upper }}='{{ value | string | replace("'", "\'") }}'
      {% endfor %}
```

**Comment by straight-shoota** [comment]
@dzraf it only works if no value contains an escaped `\'`
