### ISSUE TITLE
Feature request: Add AWS CodeCommit Repo support

### ISSUE THREAD

**Issue by newloong** [roots/trellis#969]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**

No AWS CodeCommit Repo support

**What is the expected or desired behavior?**

Add AWS CodeCommit Repo support

---

## Bug report

Please provide steps to reproduce, including full log output:

Got the following error using AWS CodeCommit as Repo(repo: ssh://git-codecommit.us-west-2.amazonaws.com/v1/repos/bedrock.example.com)

TASK [Ensure repo is valid] 
System info:
  Ansible 2.4.2.0; Darwin
  Trellis at "Git: Ignore `vagrant.local.yml`"

Invalid Git repository.
Ensure that your site's `repo` variable is defined in
`group_vars/staging/wordpress_sites.yml` and uses the SSH format (example:
git@github.com:roots/bedrock.git)
More info:
> https://roots.io/trellis/docs/deploys/

fatal: [staging_host]: FAILED! => {"changed": false}
	to retry, use: --limit @/Users/name/sites/example.com/trellis/deploy.retry

PLAY RECAP 
localhost                  : ok=0    changed=0    unreachable=0    failed=0
staging_host               : ok=2    changed=0    unreachable=0    failed=1

**Please describe your local environment:**

Ansible version: 2.4.2.0

OS: macOS 10.13.3 (17D102)

Vagrant version: 2.0.2

**Where did the bug happen? Development or remote servers?**

Staging

## Feature Request

Add AWS CodeCommit Repo support

**Comment by swalkinshaw** [comment]
I'm assuming CodeCommit doesn't work if you append the `.git` extension?

**Comment by newloong** [comment]
@swalkinshaw Yes, it doesn't work, both append .git extension and without .git extension. The URI of CodeCommit repo like:
`ssh://Your-SSH-Key-ID@git-codecommit.us-east-2.amazonaws.com/v1/repos/MyDemoRepo`

So we need to improve the regular expressions, see #975

**Comment by fullyint** [comment]
Closed in #975 
Thanks @newloong!
