### ISSUE TITLE
Show Log Info When Git Clone Fail on Deployment

### ISSUE THREAD

**Issue by MikeiLL** [roots/trellis#970]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**

When Git Clone task fails in `roles/deploy/tasks/update.yml` it returns a _likely_ error suggesting that the user make sure they can connect to the repository and that ssh agent forwarding is used. 

I spent a lot of time trying to _fix_ something that wasn't a problem, as my repository actually _was_ being successfully cloned. The problem was with differences between a local (my devbox) and github submodule.

**What is the expected or desired behavior?**

I want an error message that is more accurate to the actual error.

---

## Bug report

```
---------------------------------------------------
fatal: [...]: FAILED! => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", 
    "changed": false
}
...ignoring
```

X

**Please describe your local environment:**

Ansible version: ansible 2.4.3.

## Feature Request

**Please provide use cases for changing the current behavior:**

I wonder if either of the following would make sense:

    1. Set `no_log: false`
    2. Suggest in the `msg` that setting `no_log: false` might offer some insight.

Another idea would be to have another task happen which would be including the following in a fail task routine:

```
- name: See If I can Connect
  command: ssh -T git@bitbucket.org
  register: git_ssh_test

- debug: msg="{{ git_ssh_test.stdout }}"
- debug: msg="{{ git_ssh_test.stderr }}"
```

**Comment by swalkinshaw** [comment]
`no_log` can be ignored if you use the `ANSIBLE_DEBUG=true` env var.

But maybe removing `no_log` isn't so bad either. I'd have to see what the normal output was we were trying to suppress. You can try that out if you want.

Your other idea is good as well though. That would go before the clone project files I assume? I'd be open to either change.
