### ISSUE TITLE
Nginx Critical Error with fastcgi_cache_background_update

### ISSUE THREAD

**Issue by devotoare** [roots/trellis#994]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

Replace any `X` with your information.

---

**What is the current behavior?**

When provisioning a server I'm getting a new error, looks related to #962. It's actually a breaking bug that stops Nginx from working.

`nginx: [emerg] invalid value "True" in "fastcgi_cache_background_update" directive, it must be "on" or "off" in /etc/nginx/sites-enabled/example.com.conf:82`

I can't figure out why since the default in main.yml is indeed "on", but the value in the final file is "True". I even attempted to fix it by adding the below to my wordpress_sites.yml, but to no avail.

`cache:
      enabled: true
      background_update: on`

**What is the expected or desired behavior?**

Default value of "on" is respected and Nginx functions.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

1. Provision a server with Trellis.

**Please describe your local environment:**

Ansible version: X

Windows 10

Vagrant version: 2.0.1

**Where did the bug happen? Development or remote servers?**

Both.

**Comment by swalkinshaw** [comment]
Just to confirm, you have this commit right: https://github.com/roots/trellis/commit/54a108e2a5d9a9e0cf2c9c7c13e136b256622460

**Comment by devotoare** [comment]
Huzzah!

I missed that commit apparently. That fixes it. Thanks @swalkinshaw
